### ISSUE TITLE
開発者向けのインストール方法を記載

### ISSUE THREAD

**Issue by hsmt** [baserproject/basercms#1001]
テーマやプラグインの開発のときはローカル環境にインストールする事が多いと思うのですが、ホスティングサーバーにインストールするための手順しかないので、ひとまずMAMPを使ったときのインストール方法などが記載されていたほうが良さそうです。

**Comment by ryuring** [comment]
Issue ありがとうございます！ @hsmt 
ちなみに、docker のドキュメントはこちらにあります。
https://github.com/baserproject/basercms/tree/dev-4/docker
