### ISSUE TITLE
【ページ】固定ページに「index.html」でもアクセスが可能なのでカノニカルを出力する

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1013]
（このIssueはRedmineのチケットから移行されています）

作成者: 江頭 竜二
作成日: 2019/04/11 19:05

**Comment by yama** [comment]
@tommy6073 こちらの件、詳細をご案内いただいてよいでしょうか？
`https://example.com/sample` というURLの固定ページがあったとして、
`https://example.com/sample/index.html` というURLでも同じページを開くことが
できるということと思いましたが、手元の開発環境で再現しませんでした。

**Comment by ryuring** [comment]
@yama 
tommy6073 は、Redmineからのチケット移行を担当しただけで内容を把握していません。
僕の方で週明け確認しますね。

**Comment by ryuring** [comment]
@yama 確認しました。 `https://example.com/sample` の場合、`https://example.com/sample.html` でもアクセス可能ということですね。

**Comment by yama** [comment]
@ryuring `https://example.com/sample` としてカノニカルURLを出力するとよいですね。後ほどプルリクをまとめます。

**Comment by ryuring** [comment]
@yama そうですね。 `https://example.com/sample` をメインとする前提でカノニカル出力をお願いします。

**Comment by yama** [comment]
@ryuring 
手元の環境で久しぶりに確認してみたら、カノニカルURLが出力されませんでした。
よく調べてみたら、サブサイトがあることが前提となっていました。昨年の夏頃から、
スマホ表示用のサブサイトを作らないようになってましたね、、

とりあえず修正しますが、サブサイトの有無に関係なくカノニカルURLを取得できる
仕組みを、別issueを立てるなどして考えてみます。
