### ISSUE TITLE
【テーマ】PHP7.2 & baserCMS 4.1.5 で管理画面のテーマアップロードページよりZIP形式のテーマファイルをアップロードすると"不正なリクエスト"と判断される

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1018]
（このIssueはRedmineのチケットから移行されています）

作成者: 瀬戸 優一
作成日: 2019/01/16 12:37

フォーラムからの報告です。
http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=3263&forum=8

以下の環境で再現しました。
PHP 7.2.10
baserCMS 4.1.6-dev

手順
1. 管理画面のテーマアップロードページ(admin/themes/add) からテーマファイルをZIP形式でアップロード
2. "不正なリクエストと判断されました。" と表示される

**Comment by tommy6073** [comment]
投稿者: 瀬戸 優一
投稿日: 2019/01/16 05:16:06

- **ステータス** を 担当 から 終了 に変更
php.ini の post_max_size の値を増やしたら解決したためクローズします。

**Comment by tommy6073** [comment]
投稿者: 瀬戸 優一
投稿日: 2019/01/16 05:19:14

- **ステータス** を 終了 から 担当 に変更
でもエラーメッセージが表示されないのはおかしいですね。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2019/01/19 08:28:50

こちら、7.2 環境で再現できました。




	アップロードするファイルのサイズが、post_max_size を超える場合、$_POSTが空になり、SecurityComponent::_validateCsrf() にて、_Token.key がないという事でエラーになるようです。




	空になる原因はわかっていないです。




	また、ブラウザ側で `<input type="hidden" name="MAX_FILE_SIZE" value="2000000" />` を利用して制限しても同様の症状でした。




	取り急ぎ報告まで。

**Comment by yama** [comment]
![image](https://user-images.githubusercontent.com/73999/82753967-de9b5100-9e04-11ea-8de7-ccbffdaacc6d.png)

@ryuring 画面上で、適用可能なファイルサイズについて分かりやすい注記があるといいかも？

`$_SERVER['REQUEST_METHOD']` や `$_SERVER['CONTENT_TYPE']` の値と、 $_POST が
空かどうかで判定できるかな・・と思いましたが、よく考えるとあまり大きなファイルを
受け取ってしまえるのは、何が起きるか分からないのでこわいですね。
JavaScriptのfileオブジェクトなどを使ってブラウザ側で事前に蹴ってしまうのがスマート
かもしれません。

**Comment by ryuring** [comment]
@yama こちら確認したところ、https://github.com/baserproject/basercms/commit/28c0ed5e149bc8e7aaed1865a9594d348c0f325a や、 https://github.com/baserproject/basercms/commit/cb389a92c3328dacfc5b001729d6c15ff325bb05 のコミットで解消しているようでした。

**Comment by ryuring** [comment]
![スクリーンショット 2020-05-26 11 29 33](https://user-images.githubusercontent.com/90106/82854950-e3ffb500-9f44-11ea-9ab9-be1a31f95d2a.png)
ちなみに、post_max_size を超えた場合の挙動はこちらになります。

**Comment by kaburk** [comment]
こちら解決済みでしたのでクローズします。
