### ISSUE TITLE
【検索インデックス】フォルダ編集時にURL（フォルダ名）を変更しても、検索インデックスに登録されているURLが変わらない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1019]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2019/01/10 21:35

h3. 再現手順

・フォルダを sample_check で登録して、公開状態にする
・sample_check の中で sample_page ページを作り、公開状態にする
・検索機能で検索する → /sample_check/sample_page で検索結果にヒットする
・フォルダ（URL）を sample_check_change に編集して保存する
・検索機能で検索する → /sample_check/sample_page で検索結果にヒットする
　→ sample_check が sample_check_change に変わっていない点

**Comment by kaburk** [comment]
こちらの件はhttps://github.com/baserproject/basercms/commit/2d6c107a9b3ea3e1382b96d00bc616ffe7789e46なので現在は改修済みで発生しないようでしたので、クローズしたいと思います。
