### ISSUE TITLE
【メール】メールフォーム基本設定のWebサイト名が未入力の場合、メール送信時にエラーが出る

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1022]
（このIssueはRedmineのチケットから移行されています）

作成者: 安部 友啓
作成日: 2018/11/02 12:25

baserCMS 4.1.0.1 で現象を確認しております。
エラーログは下記となっております。

@Notice (8): Undefined index: MailConfig [CORE/Baser/Plugin/Mail/Controller/MailController.php, line 432]
Notice (8): Undefined index: MailConfig [CORE/Baser/Plugin/Mail/Controller/MailController.php, line 442]
Warning (2): Cannot modify header information - headers already sent by (output started at /〇〇/lib/Cake/Utility/Debugger.php:795) [CORE/Baser/Plugin/Mail/Controller/MailController.php, line 178]
Warning (2): Cannot modify header information - headers already sent by (output started at /〇〇/lib/Cake/Utility/Debugger.php:795) [CORE/Baser/Plugin/Mail/Controller/MailController.php, line 179]
Warning (2): Cannot modify header information - headers already sent by (output started at /〇〇/lib/Cake/Utility/Debugger.php:795) [CORE/Baser/Plugin/Mail/Controller/MailController.php, line 180]
@

エラー自体を解消する、
もしくはメールフォームを利用する時はメールフォーム基本設定のWebサイト名を入力必須にする
等の対応を検討する必要がありそうです。

**Comment by tommy6073** [comment]
投稿者: 安部 友啓
投稿日: 2018/11/02 03:26:06

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/74417?detail_id=83746

**Comment by tommy6073** [comment]
投稿者: 安部 友啓
投稿日: 2018/11/02 03:26:39

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/74418?detail_id=83747

**Comment by kaburk** [comment]
baserCMS4.4.8にて確認しましたが、現在は発生しないようでしたので一旦クローズいたします。
