### ISSUE TITLE
【メール】テキストエリアの最大入力文字の制限を追加

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1031]
（このIssueはRedmineのチケットから移行されています）

作成者: 安部 友啓
作成日: 2018/08/06 15:00

メールフォームのテキストエリア項目に対し、
テキスト項目のように最大入力文字の制限を追加できないか

**Comment by ryuring** [comment]
https://github.com/baserproject/basercms/issues/1029

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/pull/1726 にて実装予定です

**Comment by kaburk** [comment]
マージされたのでクローズします。
