### ISSUE TITLE
[要望]メールフォームの項目に全角、半角、ふりがな、フリガナのバリデーション追加

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1034]
（このIssueはRedmineのチケットから移行されています）

作成者: 安部 友啓
作成日: 2018/08/06 14:58

メールフォームのテキスト項目に対し、
・全角、半角のバリデーション
・ふりがな、フリガナのバリデーション
を追加できないか。

現状、全角フリガナについてはバリデーションオプションがあるのですが、半角でも入力が可能になっています。

**Comment by tommy6073** [comment]
投稿者: 安部 友啓
投稿日: 2018/08/06 07:29:53

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/73718?detail_id=82920

**Comment by ryuring** [comment]
マージ済
