### ISSUE TITLE
【ウィジェット】SSL環境でbaserをサブフォルダにインストールした際に、ブログのウィジェットのリンク先がおかしい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1036]
（このIssueはRedmineのチケットから移行されています）

作成者: 瀬戸 優一
作成日: 2018/07/19 16:27

以下のウィジェットで確認しています。
* カレンダー
* 月別アーカイブ一覧
* ブログ投稿者一覧
* 年別アーカイブ一覧

上記のウィジェットで、URLの生成時に使用しているBcBaser->getBlogContentsUrlという関数の第2引数の$baseに対してfalseを渡すと解決することを確認しました。
しかし、BcBaserHelper->getLinkの方の挙動を修正することが正しい気がします。

**Comment by tommy6073** [comment]
投稿者: 加藤 朗
投稿日: 2018/07/19 09:42:51

- **コピー先** [TODO #22082][1] : スクラッチコンテンツなどでcontent_idが存在しない物でもsearchindexに保存できるようにする。 を追加
    

  [1]: /issues/22082

**Comment by kaburk** [comment]
baserCMS 4.5.0にて確認したところ、すでに解消されているようでしたのでクローズします。
