### ISSUE TITLE
【フォーラム】管理画面 SSL切替時の確認メッセージの<br>タグがそのまま表示されている

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1037]
（このIssueはRedmineのチケットから移行されています）

作成者: 瀬戸 優一
作成日: 2018/07/17 17:01

フォーラムにて報告がありました。4.1.2で確認しています。
http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=3189&forum=8

ご確認をよろしくお願いします。

**Comment by ryuring** [comment]
解消済
