### ISSUE TITLE
【システム】テーマフォルダ内にElementsフォルダが存在しないとテーマ内のBlog/posts.phpファイルが読み込めない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1042]
（このIssueはRedmineのチケットから移行されています）

作成者: 江頭 竜二
作成日: 2018/05/27 12:50

**Comment by kaburk** [comment]
baserCMS4.5.0で確認したところ現在は解消されている不具合のようでしたので、クローズします。
