### ISSUE TITLE
［フォーラム要望］メールフォームのinputとlabelをラップする設定が欲しい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1044]
（このIssueはRedmineのチケットから移行されています）

作成者: 瀬戸 優一
作成日: 2018/04/23 10:17

フォーラムからの要望です。
ラジオボタンのinputとlabelをワンセットでラップする設定があると、CSSの設定がしやすいかと思います。

http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=3129&forum=6

**Comment by ryuring** [comment]
4.2 で対応済です
