### ISSUE TITLE
【ブログ】投稿中のプレビューでCSRF対策によるエラー

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1047]
（このIssueはRedmineのチケットから移行されています）

作成者: 瀬戸 優一
作成日: 2018/04/04 13:17

ブログ投稿時に、本文用に画像をアップロードし、プレビューボタンを押すと正常に動作しません。
baser 4.0.9 及び 4.1.0.1 で再現しました。
ご確認をよろしくお願いします。

4.0.9 ブログ投稿中のプレビューでCSRF対策によるエラー
http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=3119&forum=8

**Comment by seto1** [comment]
4.3.6-devでは改善されているようです。

**Comment by ryuring** [comment]
確認ありがとうございますっ！
