### ISSUE TITLE
固定ページの保存時、コンテンツの同一階層に、同一名のフォルダが存在する場合、アラートを表示させる

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1048]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2018/02/19 22:17

※この件からの発生課題
http://project.e-catchup.jp/issues/20494#note-2

＜案＞
■「自動的にリネームする」仕様を活かし、そのままの保存とする場合
・編集画面の場合、リネームされた場合、編集画面にその旨を表示させる
　→ アラート文、色は緑「ページ名は、同一階層に同名のコンテンツが存在するためリネームされました」
・課題: ajax処理時はどうするか？
■「自動的にリネームする」仕様を、エラーを出す仕組み切り換える場合
・編集画面の場合、バリデーションで弾いてエラーとする
・課題: ajax処理時はどうするか？

**Comment by ryuring** [comment]
実装済
