### ISSUE TITLE
descriptionタグ のデフォルトを空に

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1050]
（このIssueはRedmineのチケットから移行されています）

作成者: 江頭 竜二
作成日: 2018/03/13 17:47

* 各ページにて入力したら出力する、なければ、タグも出さない
* システム管理の説明文は利用しない方向に（キーワードも同様）

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/03/13 08:50:43

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/70704?detail_id=79569

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/03/13 08:52:39

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/70705?detail_id=79570

**Comment by ryuring** [comment]
実装済
