### ISSUE TITLE
【システム】/update コンテンツに誰でもアクセスできてしまう

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1058]
（このIssueはRedmineのチケットから移行されています）

作成者: 坂口 昌己
作成日: 2017/12/06 10:58

公開中のサイトで誰でも /update のアップデート用のURLにアクセスできてしまうので、
何らかの制限をかけたほうが良いのではないでしょうか。

例
http://trial.basercms.net/update
など

※ baserCMS2系?4系全部/updateにアクセスできるようです。

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2017/12/06 01:58:55

- **題名** を /update コンテンツのアクセスに誰でもアクセスできてしまう から /update コンテンツに誰でもアクセスできてしまう に変更

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2017/12/06 02:06:42

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/66273?detail_id=74554

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/12/06 05:12:53

補足です。update の URLは、setting.php で変更できる仕様となっています。

**Comment by tommy6073** [comment]
投稿者: 瀬戸 優一
投稿日: 2018/05/24 01:58:53

更新ページのURLを変更するための、BcApp.updateKeyを設定する場合app/Config/setting.phpでなく、app/Config/install.phpに記載しないと不都合が発生するようです。




	[http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=3162&forum=8][1] 

    

  [1]: http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=3162&#38;forum=8

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/05/27 04:40:49

読み込み順序を調整しようとしてみたのですが、慎重にテストを行わねば色々と弊害が起きそうでした。




	- 基本的には、app/Config/setting.php で全ての設定を上書きしたい- app/Config/setting.php あまり早く読み込むと設定の上書きができない設定が出てきそう




	Configureで設定しているものを整理して調整する方向でしょうか。取り急ぎは、install.php での対応をアナウンスした方がよさそうです。

**Comment by yama** [comment]
いつもお世話になっております。

@tommy6073 
@ryuring 

アップデートできる状態になければ404 not foundのビューを返すというのはどうでしょうか？

https://github.com/baserproject/basercms/blob/basercms-4.3.4/lib/Baser/Controller/UpdatersController.php#L162-L163
上記部分の `$this->getBaserVersion()` と `$this->getSiteVersion()` の値を比較し、
違っている場合にアップデートページを返します。
もしよろしければプルリク作ります。

**Comment by ryuring** [comment]
@yama ご提案ありがとうございます。そちらの方向でお願いします。
`clearAllCache();` の下に処理を書いて頂けるとありがたいです。外部からキャッシュ削除する方法をのこしておきたくて😅

**Comment by yama** [comment]
https://github.com/baserproject/basercms/blob/basercms-4.3.4/lib/Baser/Controller/UpdatersController.php#L99

@ryuring 見たところ99行目に `clearAllCache()` があるようです。なので、キャッシュは削除できると思いますが、いかがでしょうか？(すみません、意図をよく理解できてないかも？)

/update/ ページを開くだけでキャッシュがクリアされますが、これはこれでよいのでしょうか？

**Comment by ryuring** [comment]
@yama 意図を伝えておらずすみません。実は、トラブルシューティングの一つとして、ログイン情報を知らない場合にサーバーキャッシュを削除したい場合がありまして。それで update 画面を使うことが多々あったのです。
なので、裏機能として残しておきたいなと思いましたが、わかりにくいですよねw
