### ISSUE TITLE
管理画面の入力項目で入力必須チェックでエラー表示後にヘルプの中身が空になる

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1059]
（このIssueはRedmineのチケットから移行されています）

作成者: 坂口 昌己
作成日: 2017/07/28 15:00

入力必須項目にヘルプアイコンがある箇所全部のようです。

baserCMS4.0.5.1にて確認しました。

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2017/07/28 06:00:35

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/61236?detail_id=68805

**Comment by ryuring** [comment]
こちら再現できず。
@kaburk こちら最新版で再現できるか確認お願いします。

**Comment by rabbitchang** [comment]
@ryuring 
閉じたイシューですが、只今baserCMS5テスト仕様書作成中に同じ動作を発見しました。
メールフィールドの新規メールフィールド登録画面で何も入力せずに保存ボタンを押すと「フィールド名」＆「項目名」のヘルプの中身が空となっていました。

![スクリーンショット 2024-01-05 16 37 54](https://github.com/baserproject/basercms/assets/84309553/a0c06d86-36ac-4b98-bc09-60c9b01a1a6b)

![スクリーンショット 2024-01-05 16 38 04](https://github.com/baserproject/basercms/assets/84309553/2c47b8db-0b2f-4315-b802-9a27b609854b)

baserCMSバージョン： 5.0.8-dev

**Comment by ryuring** [comment]
@rabbitchang 報告ありがとうございます。こちらのコミットで解消しておきました。
https://github.com/baserproject/basercms/commit/0a483b0873985c0934dd4406b58fd2962ccce183
