### ISSUE TITLE
PHP_CodeSnifferによるフォーマットチェック導入の検討

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1060]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2017/07/19 21:15

https://book.cakephp.org/2.0/ja/contributing/cakephp-coding-conventions.html
https://github.com/cakephp/cakephp-codesniffer

viewファイルの拡張子がphpのためフォーマットチェックが走らないよう除外をどうするかも含めて導入検討をする。

**Comment by ryuring** [comment]
5系で検討する
