### ISSUE TITLE
【システム】.editorconfig の導入を検討する。

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1061]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2017/07/19 19:05

下記などを想定。

<pre>
root = true

[*]
#文字コード
charset = utf-8
#改行コード
end_of_line = lf
#最終行に改行を追加
insert_final_newline = true
#行末のスペースを除去
trim_trailing_whitespace = true
#タブインデント
indent_style = tab
</pre>

CakePHPのeditorconfigも参考に取り入れる等
https://github.com/cakephp/cakephp/blob/master/.editorconfig

**Comment by tommy6073** [comment]
投稿者: 渕上 将和
投稿日: 2017/07/19 11:30:00

そういえば以前に作ってみたものがありました。
root = true

[*]
end_of_line = lf
charset = utf-8
indent_style = tab
indent_size = 4
trim_trailing_whitespace = false
insert_final_newline = false

[*.md]
insert_final_newline = true

[*.php]
insert_final_newline = true

[{package.json,*.yml}]
indent_style = space
indent_size = 2

[*.py]
indent_style = space
indent_size = 4

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/commit/9895f24dc8fa83450b0e643661f7a73c11ac1d5f の改修時に導入されたようですので、クローズします。
