### ISSUE TITLE
baserCMS 3.0.12にてVagrantが起動しない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1065]
（このIssueはRedmineのチケットから移行されています）

作成者: 坂口 昌己
作成日: 2017/02/14 20:16

phpMyAdminのバージョンが上がったみたいで、
PHP5.5以上を要求されているようですが、PHP5.4がインストールされているのが
原因のようでした。

<pre>
==> default: [2017-02-14T20:01:17+09:00] ERROR: yum_package[phpMyAdmin] (httpd::default line 3) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install phpMyAdmin-4.6.6-1.el6.remi returned 1:
==> default: STDOUT:  You could try using --skip-broken to work around the problem
==> default:  You could try running: rpm -Va --nofiles --nodigest
==> default: 
==> default: STDERR: Error: Package: phpMyAdmin-4.6.6-1.el6.remi.noarch (remi)
==> default:            Requires: php(language) >= 5.5
==> default:            Installed: php-common-5.4.45-12.el6.remi.x86_64 (@remi)
==> default:                php(language) = 5.4.45
==> default:            Available: php-common-5.3.3-47.el6.x86_64 (base)
==> default:                php(language) = 5.3.3
==> default:            Available: php-common-5.3.3-48.el6_8.x86_64 (updates)
==> default:                php(language) = 5.3.3
==> default:            Available: php-common-5.4.45-11.el6.remi.x86_64 (remi)
==> default:                php(language) = 5.4.45
==> default: [2017-02-14T20:01:17+09:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
</pre>

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2017/02/15 01:59:41

Vagrantで導入するPHPのバージョンを5.6にするように検討

**Comment by ryuring** [comment]
こちらバージョンが古いのでクローズします。
