### ISSUE TITLE
【ブログ】ブログ投稿日の時間欄をコロン無しで入力すると、表示のみコロン付きになり、保存するとエラー

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1068]
（このIssueはRedmineのチケットから移行されています）

作成者: 内場 龍彦
作成日: 2016/10/04 14:12

3.0.10、3.0.11で発生を確認

投稿日の「時間」欄を「数字4桁（コロン無し）」で入力すると、「投稿日の形式が不正です。」とのエラーが返ってきます。
画面表示上ではコロン付きに置換されるが、input hiddenの値がコロン無しの状態となっているのが原因のようです。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/10/04 05:26:03

- **対象バージョン** を削除 (3.0.11)
対象バージョンは、リリースするバージョンを指定します。一旦外しますね。

**Comment by kaburk** [comment]
4系にて日付のjsでの自動フォーマット、バリデーション強化が入っているため現在は発生しないようです。
こちらのチケットはクローズしたいと思います。
