### ISSUE TITLE
【システム】windows + xamppの対応願い

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1072]
（このIssueはRedmineのチケットから移行されています）

作成者: 加藤 朗
作成日: 2016/06/16 11:21

フォーラムより改善要望が上がっています。

http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=2226&forum=9

windowsにxamppを使った環境でbeserCMS ver.3.0.8?3.0.10がエラーが出て、インストールができません。

**Comment by tommy6073** [comment]
投稿者: 加藤 朗
投稿日: 2016/06/16 02:22:12

- **ファイル** sukusyo.png を追加
社内のPCでも同様の現象が発生します。

**Comment by tommy6073** [comment]
投稿者: 加藤 朗
投稿日: 2016/06/16 02:27:20

- **ファイル** [sukusyo.png][1]  を追加
    

  [1]: /attachments/download/1593/sukusyo.png

**Comment by tommy6073** [comment]
投稿者: 加藤 朗
投稿日: 2016/06/16 02:27:31

- **ファイル** を削除 (sukusyo.png)

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2016/06/16 03:43:39

- **担当者** を削除 (江頭 竜二)
調査したところ、app/webroot/index.phpの25行目で
$fileName = $_SERVER['SCRIPT_FILENAME'];
にてファイル名を取得しているが、WindowsのXAMPP環境で$_SERVER['SCRIPT_FILENAME']を取得すると内容が
C:/xampp/htdocs/ 
という形で取得されその後の処理でROOT定数にセットされます。




	しかし、他の定数組み立て時はDS定数を使いパスの区切りが¥でセットされるので、TMP定数などが
C:/xampp/htdocs\app\tmp\
という形で定義されてしまいます。




	インストールの途中でlib/Baser/basics.php の checkTmpFolders の中で$folder->create(TMP . 'logs', 0777); などが実行される時にTMPが/と¥が混在しているのが原因でフォルダが作成できず、今回のエラーになっているようです。




	元々は
define('ROOT', dirname(dirname(dirname(__FILE__))));
で取得していたのを何かの対策（2012/10/27,  2013/12/24）で
$fileName = $_SERVER['SCRIPT_FILENAME'];
           :
define('ROOT', dirname(dirname(dirname($fileName))));
に改修されているのが原因なのですが、何のための改修かわからずどのように対応したら良いのか現状不明な状態です。




	他に影響がなければ、
$fileName = $_SERVER['SCRIPT_FILENAME'];
を
$fileName =  __FILE__;
に戻したいところです。




	色々他に影響がありそうでしたら、Windows環境では/と¥を混在しないように置換する処理を追加するとか、ですかね。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/06/21 12:55:44

FILE を利用せず、$_SERVER['SCRIPT_FILENAME'] に変更しているのは、どこかのサーバーで、__FILE__ が期待を返さなかった事に起因します。




	できれば、$_SERVER['SCRIPT_FILENAME'] で、置換処理をかました方が安全かと思います。

**Comment by kaburk** [comment]
baserCMS4.4.8 / Windows 10 / XAMPP 7.4.20 （PHP7系最新）で問題なく動作しているようですので、こちらは一旦クローズしたいと思います。（別途発生時に改めてissue立てていただければと思います）
