### ISSUE TITLE
【ブログ】isSingleがプレビューで動作しない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1073]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2016/06/13 15:33

BlogHelper::isSingleのLine 885あたりにプレビュー判別を入れたら対応可能だと思うがテストが必要。
<pre>
		if ($this->request->params['plugin'] == 'blog' &&
			$this->request->params['controller'] == 'posts' &&
			$this->request->params['action'] == 'archives'){
			return true;
		}
</pre>

**Comment by seto1** [comment]
4.3.6-devだと改善されているようです。

**Comment by ryuring** [comment]
確認ありがとうございます！
