### ISSUE TITLE
【メール】メールフォームの和暦入力で年号が一桁の和暦が入力できない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1074]
（このIssueはRedmineのチケットから移行されています）

作成者: 安部 友啓
作成日: 2016/04/27 11:14

フォーラムよりバグ報告がありました。

メールフォームの和暦入力で年号が一桁の和暦を入力すると、確認画面では空欄で表示されてしまいます。
http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=2176&forum=8

よろしくお願いします。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/04/27 03:57:00

- **プロジェクト** を baserCMS機能要望 から baserCMS に変更
安部さん、報告ありがとうございます。バグなので本体プロジェクトに移動しておきますね。

**Comment by seto1** [comment]
https://github.com/baserproject/basercms/pull/868 にて対応されています。

**Comment by kaburk** [comment]
対応済みでしたので、クローズいたします。
