### ISSUE TITLE
【システム】管理画面のプレフィックスをadmin以外にした場合でも/admin/にアクセスできてしまう

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1078]
（このIssueはRedmineのチケットから移行されています）

作成者: 内場 龍彦
作成日: 2016/02/17 15:32

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2017/02/15 01:46:52

- **プロジェクト** を baserCMS機能要望 から baserCMS に変更

**Comment by ryuring** [comment]
現在は再現できず
