### ISSUE TITLE
【ブログ】アイキャッチ画像が常にブラウザキャッシュを利用されないQUERY_STRINGを発行している

### ISSUE THREAD

**Issue by tnagatomi** [baserproject/basercms#1081]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2015/09/09 13:59

高速化のため、キャッシュされないQUERY_STRINGのりよう可否オプションの追加か、実ファイルをみて自動的にon/offの機能のようなものが必要ではないでしょうか。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2015/09/09 05:02:57

管理画面でだけクエリストリングを利用する仕様にしてはどうでしょ？確か、管理画面でアップロード直後に反映されない問題の対策だったと思うので。
