### ISSUE TITLE
REST対応

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1089]
（このIssueはRedmineのチケットから移行されています）

作成者: 江頭 竜二
作成日: 2015/02/20 16:54

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2015/02/20 07:55:01

- **トラッカー** を TODO から 課題 に変更

**Comment by ryuring** [comment]
baserCMS5系で検討予定
