### ISSUE TITLE
【ページ】ページテンプレートの書き出し時、キャッシュされているようで書き出しが上書きされないことがある

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1091]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2015/01/23 01:08

以下、届いた件になります。

<pre>
一点、Pageのテンプレート書き出しですが、どうもキャッシュされるようです。
一度サーバキャッシュをしないと、書き出しが上書きされないことが分かりました。
管理画面内の処理はキャッシュを効かないようにするか、事あるごとに関係のあるキャッシュファイルを削除するような処理を仕込む必要があるかと思います。
</pre>

**Comment by tommy6073** [comment]
投稿者: 木田 亮介
投稿日: 2015/05/20 14:20:00

- **プロジェクト** を baserCMS機能要望 から baserCMS に変更 - **カテゴリ** を削除 (固定ページ)
調査が必要

**Comment by tommy6073** [comment]
投稿者: 権藤 隆行
投稿日: 2015/08/07 08:29:49

おそらくパーミッションの問題。１．ローカルで作成２．サーバにアップロード３．アップロードユーザのファイルとなり、WEBサーバユーザから/theme/{利用テーマ}/Pages/以下に書き出しが出来ない問題と想定




	書き込みが出来ない場合は、警告・エラーメッセージを表示する。

**Comment by kaburk** [comment]
> 書き込みが出来ない場合は、警告・エラーメッセージを表示する。

baserCMS4.5.0にて確認したところ、固定ページ書き出しできない場合はエラーメッセージが表示されるようになっていましたので、こちらはクローズしたいと思います。
