### ISSUE TITLE
パンくずリストをタグで出力できるように

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1097]
（このIssueはRedmineのチケットから移行されています）

作成者: 岩崎 洋平
作成日: 2014/04/11 16:00

フォーラムからのご要望。

http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=1486&forum=9&post_id=5581#forumpost5581

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2014/11/27 13:59:02

- **カテゴリ** を フロント全般 にセット

**Comment by tommy6073** [comment]
投稿者: 木田 亮介
投稿日: 2015/05/20 14:12:15

- **プロジェクト** を baserCMS機能要望 から baserCMS に変更 - **説明** を更新 ([diff][1] ) - **カテゴリ** を削除 (フロント全般)
    

  [1]: /journals/diff/29261?detail_id=32880

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2015/05/20 14:12:39

公式で用意する分は、Google推奨フォーマットで出力ヘルパーで配列で出力できるようにするとか検討する

**Comment by ryuring** [comment]
改善済のためクローズ
