### ISSUE TITLE
【システム】Windows 10上の特定ブラウザで時刻フィールドに値を直接入力できない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1107]
（このIssueはRedmineのチケットから移行されています）

作成者: 永冨 隆之
作成日: 2018/01/26 18:41

Windows 10において、管理画面のブログや固定ページ編集で、投稿日の時刻フィールドに値を直接入力できない問題を発見しました。
（プルダウンからしか値を選択できない）
Google Chromeでこの現象を確認しましたが、調査してみたところ入力できるブラウザも存在するようです。

以下に入力できないブラウザ、できるブラウザを列挙します:

入力できないブラウザ
* Google Chrome (バージョン: 64.0.3282.119 64bit)
* Firefox (バージョン: 58.0 64bit)

入力できるブラウザ
* Internet Explorer (バージョン: 11.192.16299.0)
* Edge (バージョン: 41.16299.15.0)
* Opera (バージョン: 12.17 x64, フィーチャーフォン動作検証用)

OS環境
* エディション: Windows 10 Home
* バージョン: 1709
* OSビルド: 16299.192

なお、Mac上のGoogle Chromeでは入力できることを確認しています。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:55

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:33

- **対象バージョン** を削除 (4.1.0)

**Comment by kaburk** [comment]
確認したところ、2021/7 現在 Windows10  Firefox/ chromeどちらも入力可能になっておりましたのでこちらはクローズしたいと思います。
