### ISSUE TITLE
【検索インデックス】サブフォルダに設置した際に検索インデックス再構築でNot Foundとなる

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1108]
（このIssueはRedmineのチケットから移行されています）

作成者: 加藤 朗
作成日: 2017/08/02 12:26

フォーラムにて問い合わせがございました。
http://forum.basercms.net/modules/newbb/viewtopic.php?topic_id=2925&forum=8#forumpost9750

同様の現象が再現できましたので、チケットを切らせていただきます。
baserCMSをサーバーのサブフォルダにインストール設置

システム管理 - 検索インデックス管理 - 検索インデックス再構築
　↓
現在の検索インデックスを消去して、再構築します。本当にいいですか？
　↓
OK

Not Found

Error: The request sent to the address '/サブフォルダ名/m/index?force=true&host=?force=true&host=' was invalid.

サブサイト管理→ケータイ（エイリアス「m」）を有効にすると、エラーは表示されなくなります。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/20 07:56:37

- **対象バージョン** を 4.0.6 から 188 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/22 05:45:11

- **対象バージョン** を 188 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:55

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:33

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
@katokaisya 最新版で再現するか確認をお願いしてもいいですか？

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/commit/7a63026d8fb18a319ac31a0c8b1e330e8d076e02 にて解消済みなのでクローズします。
