### ISSUE TITLE
【ブログ】ブログカテゴリにてアクセスできないカテゴリが作成出来てしまう。

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1112]
（このIssueはRedmineのチケットから移行されています）

作成者: 坂口 昌己
作成日: 2016/12/27 14:46

原因が2種類あるようでした。

* 空白が入力された時

カテゴリに空白を入力できないようにするか、URLアクセス時のチェックを改修する必要がありそうです。
（URLに使えない文字で登録されないように入力チェックするか、カテゴリのリンクについての処理をURLエンコードを考慮した処理にする必要がありそうです。）

* 記事詳細のカテゴリ追加から長めの文字列でマルチバイト文字でカテゴリを作成した時

登録時にマルチバイト文字がURLエンコードされるのですが、その時に長い場合にDBのカラムの長さの最大を超えてしまい途中で切れてしまうようです。
その為、リンクアクセス時にデコードできないようです。

スキーマを確認すると該当のカラムがVARCHAR(50)になっているので、TEXTなど、長い文字に対応できるようにする必要がありそうです。

（何方の現象もbaserCMS 3.0.12, baserCMS4.0.2にて確認しました）

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/07/16 09:29:09

- **対象バージョン** を 4.0.6 にセット
中榮さんが言っているように、日本語カテゴリを許可するようにした方が早そうですね。[https://github.com/baserproject/basercms/pull/638][1] 

    

  [1]: https://github.com/baserproject/basercms/pull/638

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/20 07:56:34

- **対象バージョン** を 4.0.6 から 188 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/22 05:45:08

- **対象バージョン** を 188 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:50

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:28

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
同一内容のチケットがあるのでクローズ
https://github.com/baserproject/basercms/issues/1129
