### ISSUE TITLE
[サブサイト一覧]非公開サブサイトに確認ボタンがある

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1114]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/18 17:56

・4.0.0
・さくらスタンダード
・SQLight
・テンプレート：baserCMSサンプルテーマ ( bc_sample )
・端末： iPhone 6 Plus 

非公開なんだから確認ボタンはいらない

**Comment by tommy6073** [comment]
投稿者: kagasawa _
投稿日: 2016/09/18 10:02:03

- **対象バージョン** を 正式版リリース準備 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/22 16:01:05

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **対象バージョン** を 正式版リリース準備 から 4.0.1 に変更
この件、管理画面全体に言える事なので、4.0.1 に持ち越します。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:15:09

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 04:41:03

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:49

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:27

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
最新バージョンではなおってます
