### ISSUE TITLE
固定ページ編集画面UI変更

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1115]
（このIssueはRedmineのチケットから移行されています）

作成者: 河野 哲哉
作成日: 2016/09/18 16:40

* 固定ページテンプレート
* コード

を上のオプション内に移動したいが

* オプションが多すぎるので分割？
* 逆に下に色々移動する？

管理画面調整時に再検討

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/18 10:35:34

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **カテゴリ** を削除 (その他) - **対象バージョン** を 4.0.1 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:15:08

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 04:29:23

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:49

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:26

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
4.2.0では改善しています。
