### ISSUE TITLE
【要望】[よく使う項目]デフォルトで「アップロード管理」の必要性

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1116]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/18 16:01

・4.0.0
・さくらスタンダード
・SQLight
・テンプレート：bcColumn 

ブログの新規記事登録にも新しい固定ページ作成にもアップロード機能があるため、単独のアップロード管理を[よく使う項目]にデフォルトである必要性を感じられない。

**Comment by tommy6073** [comment]
投稿者: kagasawa _
投稿日: 2016/09/18 10:16:00

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **対象バージョン** を 4.0.1 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:17:18

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 04:27:35

- **対象バージョン** を 4.0.2 から 4.1.0 に変更
WordPressのメディア管理の導線のようなものですが、一旦検討が必要そうですね。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:48

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:26

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
4.2.0 では改善します。
