### ISSUE TITLE
【要望】[BLOG]BLOG管理メニュー項目の下に「（他の）ブログ一覧」を表示させてほしい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1118]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/18 12:36

・4.0.0
・さくらスタンダード
・MySQL

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/18 10:05:46

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **対象バージョン** を 4.0.1 にセット
4.0.1で調整か未来の機能要望とする。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:56

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:55:32

- **対象バージョン** を 4.0.2 から 4.0.3 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/03/23 06:08:24

- **対象バージョン** を 4.0.3 から 4.0.4 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/05/03 05:42:12

- **対象バージョン** を 4.0.4 から 4.0.5 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/07/02 16:22:55

- **対象バージョン** を 4.0.5 から 4.1.0 に変更
この件、管理画面リニューアルと合わせて考える方向でいきましょう。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:47

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:25

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
4.2.0 で改善されます。
