### ISSUE TITLE
【要望】[BLOG]よく使う項目＞ブログ管理＞コンテンツ管理メニュー に「新規ブログ作成」リンクがほしい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1119]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/18 12:28

・4.0.0
・さくらスタンダード
・MySQL

インストールしてブログ管理に入った際に、複数ブログが設置できることが分かりづらいため、コンテンツ管理メニュー に「新規ブログ作成」リンクを設置し、複数ブログが設置できる認識を持たせたい

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/18 10:16:06

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **対象バージョン** を 4.0.1 にセット
コンテンツ管理メニューは、全体のコンテンツ管理のフィールドのためそこに、ブログの要素をいれるのは、役割がことなると思われる。




	現在、メニュー周りの調整は別途おこなっているので、そちらにあわせて、意見として残しておきます。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:55

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:54:57

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:46

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:24

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
こちら一旦クローズします。
