### ISSUE TITLE
メールフォームで[ファイル]を送信時、オプション指定時のエラーメッセージの改善

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1125]
（このIssueはRedmineのチケットから移行されています）

作成者: - garyuten
作成日: 2016/09/02 17:55

メールフォームで[ファイル]を指定し、オプションでファイルサイズ上限や拡張子指定した時のエラーメッセージの改善をお願いします。

h2. 拡張子が違った場合
!https://goo.gl/photos/rbZUKhjcqkcLu7Nw8!

<pre>
【入力エラーです】
入力内容を確認して再度送信してください。
</pre>

何のエラーだったのかわかりづらいです。

h2.ファイルサイズの上限を超えた場合
!https://goo.gl/photos/rUQySDRKPEyeKuZK6!

<pre>
ファイルのアップロードサイズが上限を超えています
</pre>

エラーメッセージはいいのですが、入力フォームのどこがエラーだったかがわかりづらいです。

これらの対策として、
該当したファイルのinputの下にも必須エラー時と同様のエラーを表示し、

*「ファイルサイズ上限：10MB、拡張子：JPG,PNG形式でお願いします」

などオプション指定したパラメーターの内容を表示させるとわかりやすいと思います。

**Comment by tommy6073** [comment]
投稿者: - garyuten
投稿日: 2016/09/02 08:56:10

- **ファイル** [エラー_ファイルタイプ.png][1]  を追加
    

  [1]: /attachments/download/1666/%E3%82%A8%E3%83%A9%E3%83%BC_%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%95%E3%82%9A.png

**Comment by tommy6073** [comment]
投稿者: - garyuten
投稿日: 2016/09/02 08:56:24

- **ファイル** [エラー_ファイル容量制限時.png][1]  を追加
    

  [1]: /attachments/download/1667/%E3%82%A8%E3%83%A9%E3%83%BC_%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%AE%B9%E9%87%8F%E5%88%B6%E9%99%90%E6%99%82.png

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/25 10:27:59

- **対象バージョン** を 3.0.11 から 4.0.1 に変更
上部のエラーメッセージを変更するには色々と仕組みの調整が必要です。3系は見送って、４系での対応予定に入れますね。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:21:57

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 04:44:44

- **対象バージョン** を 4.0.2 から 4.0.3 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/03/23 06:08:11

- **対象バージョン** を 4.0.3 から 4.0.4 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/05/03 05:42:00

- **対象バージョン** を 4.0.4 から 4.0.5 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/07/02 17:10:31

- **対象バージョン** を 4.0.5 から 4.0.6 に変更
今回、見送ります。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/20 07:56:31

- **対象バージョン** を 4.0.6 から 188 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/22 05:45:04

- **対象バージョン** を 188 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:37

- **優先度** を 低め から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:15

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
改善済。クローズ
