### ISSUE TITLE
【システム】AMPへの対応を検討する

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1126]
（このIssueはRedmineのチケットから移行されています）

作成者: 江頭 竜二
作成日: 2016/09/01 18:30

対応するにしてもどのような実装にするかも検討が必要
* 元のページに関連する別ページが生成できる仕組みにするか？（dev-4では対応済）
* 自動変換する仕組みにするか？
* ベースとなるテンプレートを提供するだけとするか？

《参考ページ》
"Accelerated Mobile Pages プロジェクトについて -- 導入ガイド日本語版を本日公開しました":https://googlewebmastercentral-ja.blogspot.jp/2016/01/accelerated-mobile-pages.html
"AMPとは～対応HTMLを作ってみてわかったこと～":http://www.brain-solution.net/blog/seo/amp-html/

誰か教えて偉い人

**Comment by kaburk** [comment]
Google方針変更に伴いAMPはあまり重要度が下がったので、2021/7現在 対応は不要かと思われます。
https://9to5google.com/2021/04/19/google-search-page-experience/
https://gigazine.net/news/20210519-google-amp-no-longer-preferential-treatment/
https://digital-marketing.guide/seo/googleamp/

一旦チケットクローズしたいと思います。（必要なときが出たら再度issue立ててください）
