### ISSUE TITLE
【メール】問い合わせフォームのデフォルト項目

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1137]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/17 17:36

≪要望≫問い合わせフォームのデフォルト項目で「どうやってこのサイトをお知りになりましたか？」はストレスになるからデフォルトから外してほし

**Comment by tommy6073** [comment]
投稿者: - bluestyle
投稿日: 2016/09/17 08:40:41

- **ファイル** [f.png][1]  を追加
    

  [1]: /attachments/download/1713/f.png

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/17 08:48:55

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **題名** を ≪要望≫問い合わせフォームのデフォルト項目で「どうやってこのサイトをお知りになりましたか？」はストレスになるからデフォルトから外してほし から ≪要望≫問い合わせフォームのデフォルト項目 に変更 - **対象バージョン** を 4.0.1 にセット
「どうやってこのサイトをお知りになりましたか？」はストレスになるからデフォルトから外してほしい。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:49

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:50:58

- **対象バージョン** を 4.0.2 から 4.0.3 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/03/23 06:08:18

- **対象バージョン** を 4.0.3 から 4.0.4 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/05/03 05:42:06

- **対象バージョン** を 4.0.4 から 4.0.5 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/07/02 16:11:39

- **担当者** を - bluestyle にセット - **対象バージョン** を削除 (4.0.5)
外谷さん、このデフォルトの項目は、実際に使う項目を想定しているわけでなく、あくまで「こういった使い方もできますよ」という事を制作者に伝えたい為のものでした。それでも外した方がいいですかね？

**Comment by kaburk** [comment]
こちらの件は各テーマのデフォルト値の問題かと思われますので、一旦クローズしたいと思います。
