### ISSUE TITLE
コンテンツ管理を一括変更に仕様変更

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1140]
（このIssueはRedmineのチケットから移行されています）

作成者: - 清末直
作成日: 2016/09/18 10:34

現状だと、コンテンツ一つずつの変更になって
誤操作をまねいて、サイトを崩す可能性が高い。

変更後、反映ボタン等で、まとめて最終状態を変更として
反映させたい。

仕様の都合上、一端 tmpテーブルにデータをコピーして
そちらをリアルタイムupdate. 反映ボタンで tmpの内容を
contents テーブルにコピーという、仕様で調整中。

これは、4.0.1にて実装予定だが、仕様だけリリース時に調整したい。

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/18 02:58:59

複数で触ったときに、だれかが作業中ですとのアラートをだす仕様とかも必要かも

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/22 17:16:39

- **担当者** を - 清末直 にセット
＞清末さん複数で触ったときのロックの仕組みは実装済です。（D&#38;D）こちら4.0.1 で実装するかどうかも踏まえてチケット持っておいてくださいー

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/24 11:34:24

- **カテゴリ** を 追加要望 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/10/04 04:56:16

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **カテゴリ** を削除 (追加要望) - **対象バージョン** を 正式版リリース準備 から 4.0.1 に変更
こちらスケジュールないんで見送りましょう。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:51

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/11/27 04:37:50

並び順の入れ替えの場合にtmpにコピーしてロックをかける。ロックとは新規追加・修正ができないということ。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:53:04

- **対象バージョン** を 4.0.2 から 4.0.3 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/03/23 06:08:19

- **対象バージョン** を 4.0.3 から 4.0.4 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/05/03 05:42:08

- **対象バージョン** を 4.0.4 から 4.0.5 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/07/02 16:13:49

- **対象バージョン** を 4.0.5 から 4.0.6 に変更
清末さん、いかがでしょう？取り急ぎ見送っておきますね。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/20 07:56:33

- **対象バージョン** を 4.0.6 から 188 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/08/22 05:45:06

- **対象バージョン** を 188 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:44

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:21

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
移動時にアラートを出す仕様に変更したのでクローズ
