### ISSUE TITLE
URLなどを実体参照化して出力する基本関数 hurl の追加

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1153]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2018/11/14 13:31

**Comment by ryuring** [comment]
@gondoh こちらは実装検討からですかね

**Comment by gondoh** [comment]
@ryuring 不要かなと思ってます。
クローズしてもいいでしょうか。

**Comment by ryuring** [comment]
では！
