### ISSUE TITLE
システム設定の保存時に不要なcallbacks処理が呼ばれる

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1155]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2017/03/24 19:32

**Comment by ryuring** [comment]
@gondoh 詳細plz

**Comment by gondoh** [comment]
これ確かコンテンツツリーの再生成かなにかが走ってデータ量が多くなると終了せずにメモリオーバーになるようなものだったかと思います。

そのあたり修正入ってますのでクローズします。
