### ISSUE TITLE
【システム】プラグインが想定するフォルダ名以外でインストールされた場合プラグインが正しく動作しない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1158]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2016/08/10 14:07

ExampleNameプラグインをExampleName-masterというフォルダでインストールすると動かない。
githubで配布しているプラグインにて多発する。

**Comment by ryuring** [comment]
@gondoh CakePHPが、プラグインをフォルダ名で認識する仕様のため、対応が難しいと思います。

**Comment by gondoh** [comment]
@ryuring 
baser側の対応はしないということでクローズでいいですかね。

**Comment by ryuring** [comment]
@gondoh 正式なプラグイン名を認識できれば、リネームしてくださいとアラートぐらいは出せるかもですね。

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/pull/1292 にてマージされているようでしたのでクローズします。
