### ISSUE TITLE
マイページ機能にてtoolbarをfalseにしても表示される

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1160]
（このIssueはRedmineのチケットから移行されています）

作成者: 権藤 隆行
作成日: 2015/11/13 03:06

マイページprefix利用時に、公開側固定ページを確認すると、front prifixとして判別されtoolbarをfalseにしていもツールバーが表示されてしまう。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2015/11/19 03:24:22

- **担当者** を 権藤 隆行 にセット
権藤ちゃん、この件、環境準備して確認したんだけど、再現できないです。




	
	 - フロントとマイページのプレフィックスを設定
		 - ユーザーグループをマイページに設定しユーザーを追加
		 - マイページにログイン
		 - ツールバーは表示されない
		 - プレフィックス設定にてツールバーを true に設定するとツールバーが表示される
	



	もうちょっと詳細情報をください。

**Comment by ryuring** [comment]
@gondoh 再現方法のレクチャーをお願いします。

**Comment by gondoh** [comment]
@ryuring 過去発生してましたが現在修正されている問題のためクローズします。
