### ISSUE TITLE
【検索インデックス】サイト内検索でカテゴリ選択に利用していないサブサイトのカテゴリが表示されてしまう

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1162]
（このIssueはRedmineのチケットから移行されています）

作成者: 坂口 昌己
作成日: 2017/12/19 14:11

非公開のサブサイトのカテゴリがでてしまっているようです。
サイトのステータスをチェックする必要がありそうです。

※ baserCMS4.0.9 / baserCMSサンプルテーマ ( bc_sample ) で確認しました。

**Comment by tommy6073** [comment]
投稿者: 坂口 昌己
投稿日: 2017/12/19 05:37:43

管理画面ログイン中の時の、フロント側の検索結果一覧で発生するようです。

**Comment by kaburk** [comment]
baerCMS4.4.8で確認したところ現在は解消されている不具合のようでしたので、クローズします。
