### ISSUE TITLE
サイト内検索でブログカテゴリを指定して検索できるようにする

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1170]
（このIssueはRedmineのチケットから移行されています）

作成者: 江頭 竜二
作成日: 2017/02/12 13:59

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:51

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:29

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
キー「content_filter_id」で検索可能なのでクローズします。
