### ISSUE TITLE
コンテンツツリー表示から編集画面への遷移がわかりづらい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1171]
（このIssueはRedmineのチケットから移行されています）

作成者: 河野 哲哉
作成日: 2016/09/17 15:52

・・・　の左に編集アイコンを設置

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/17 07:38:22

- **対象バージョン** を 正式版リリース準備 にセット
大川さんのチケットと重複あり、見つけられない。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/22 17:37:43

- **担当者** を - 清末直 にセット
清末さん、こないだ話してた時、ボタンの設置は4.0.0 でやるって言ってましたっけ？

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/23 01:03:20

<content type="html">
&lt;ul&gt;&lt;li&gt;&lt;strong&gt;担当者&lt;/strong&gt; を &lt;i&gt;- 清末直&lt;/i&gt; から &lt;i&gt;江頭 竜二&lt;/i&gt; に変更&lt;/li&gt;&lt;/ul&gt;&lt;blockquote&gt;

	&lt;p&gt;ボタンの設置は4.0.0 でやる&lt;/p&gt;


&lt;/blockquote&gt;

	&lt;p&gt;そこまでは、言ってないですね。実際この修正だいぶきついと思うので&lt;br /&gt;4.0.1でもいいかと思います。&lt;/p&gt;    </content>

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/23 02:30:29

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **対象バージョン** を 正式版リリース準備 から 4.0.1 に変更
では見送りましょう。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:45

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:48:25

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:40

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:17

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
一旦、クローズします。必要があればリオープンしてください。
