### ISSUE TITLE
【要望】[管理画面]よく使う項目の「コンテンツ一覧」は他のメニューとは表示を変えてほしい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1173]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/18 12:19

・4.0.0
・さくらスタンダード
・MySQL

コンテンツ一覧以外は「コンテンツ一覧」の子項目になるので、「コンテンツ一覧」メニューはよく使う項目内で太字など通常の項目とは表示を変えて親であることを認識できるようにしてほしい。
もしくはよく使う項目ブロックの上などに配置し、別表示にしてほしい

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/18 09:42:22

- **担当者** を 河野 哲哉 にセット
内容の精査お願いします。

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/18 09:42:31

- **対象バージョン** を 正式版リリース準備 にセット

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/18 10:18:30

- **対象バージョン** を削除 (正式版リリース準備)
これは管理画面やり替えまで持ち越しで

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/18 10:19:00

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **対象バージョン** を 4.0.1 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:54

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:54:08

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:45

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:23

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
v4.2 でメニューの仕組みが変わるのでクローズします。
