### ISSUE TITLE
コンテンツツリー　クリックで色が変わる

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1174]
（このIssueはRedmineのチケットから移行されています）

作成者: 河野 哲哉
作成日: 2016/09/17 17:07

メニューアイコンを押して編集対象になったときだけ色を付ける

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/17 08:29:08

- **対象バージョン** を 正式版リリース準備 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/24 08:09:13

- **カテゴリ** を 追加要望 にセット - **担当者** を 河野 哲哉 にセット
＞河野さん




	こちら、先日少し話しましたが、クリックでこれから操作する対象という事を知らせるという事ではダメでしょうか？クリックして色が変わり混乱を招くという事なのかもしれませんが、どういった認識となるかを教えてください。




	ちなみに、調整しようとしてみましたが、jsが絡んでいるのと、ソースのcss を直接触りたくないという理由もあり、簡単にはいきませんでした。そういうと、jsTreeを使うかどうかの問題にも話が行っちゃいそうですね。。




	うーん、jsTreeのバージョンアップを追わない前提で、ソースのcss触っちゃいますかね。。。悩みどころです。

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/10/03 02:48:53

次に回しましょう

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/10/03 03:02:47

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **カテゴリ** を 追加要望 から 管理画面全般 に変更 - **対象バージョン** を 正式版リリース準備 から 4.0.1 に変更
了解です。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:48

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:50:16

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:43

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:20

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
こちら、目的があいまいなので、一旦クローズします。
