### ISSUE TITLE
コンテンツ一覧 でドラッグアンドドロップできることが分かりづらい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1175]
（このIssueはRedmineのチケットから移行されています）

作成者: - bluestyle
作成日: 2016/09/17 16:20

ちょっとしたものでいいので、ドラッグアンドドロップできることの注意書きがほしい。
ついでに右クリックでメニュー表示も注意書きあったらうれしい。

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/17 07:35:25

- **担当者** を 河野 哲哉 にセット - **対象バージョン** を 正式版リリース準備 にセット

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/17 07:46:59

右クリックは隠し機能ぐらいのイメージで。




	編集アイコンとメニューアイコンを並べて、クリックでの操作を推奨する。メニューアイコンをわかりやすくするのとセット。




	ドラッグがわかるようにするアイデアが出なければテキストで説明追加・・・。できれば避けたい

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/17 07:51:49

- **担当者** を 河野 哲哉 から - garyuten に変更
あ、そうだ無茶振りだ。




	ドラッグアンドドロップできることを視覚的にわかるようにするアイデアありませんか？

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/17 08:09:00

ひとまず




	コンテンツツリー ドラックアンドドロップ可能な領域にマウスが入ったときにつかむアイコンに変える




	は思いつきました。

**Comment by tommy6073** [comment]
投稿者: 大川 松樹
投稿日: 2016/09/17 09:09:56

- **ファイル** [contentsList.png][1]  を追加
    

  [1]: /attachments/download/1717/contentsList.png

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/17 09:13:39

ひとまず思いついたところまでを大川さんに絵にしてもらいました。




	
	 - 確認　編集　その他メニュー　のアイコン
		 - オンマウスでドラッグ・アンド・ドロップのアイコンが出る
	



	今より良くなったとは思うのですが、まだベストではないような・・・

**Comment by tommy6073** [comment]
投稿者: 大川 松樹
投稿日: 2016/09/17 11:23:27

- **ファイル** [タテに広がる.png][1]  を追加 - **ファイル** [アイコンを全表示（小）.png][2]  を追加 - **ファイル** [マウスオーバーで表示.png][3]  を追加 - **ファイル** [アイコンを全表示.png][4]  を追加
    

  [1]: /attachments/download/1730/%E3%82%BF%E3%83%86%E3%81%AB%E5%BA%83%E3%81%8B%E3%82%99%E3%82%8B.png
  [2]: /attachments/download/1731/%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%82%92%E5%85%A8%E8%A1%A8%E7%A4%BA%EF%BC%88%E5%B0%8F%EF%BC%89.png
  [3]: /attachments/download/1732/%E3%83%9E%E3%82%A6%E3%82%B9%E3%82%AA%E3%83%BC%E3%83%8F%E3%82%99%E3%83%BC%E3%81%A6%E3%82%99%E8%A1%A8%E7%A4%BA.png
  [4]: /attachments/download/1733/%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E3%82%92%E5%85%A8%E8%A1%A8%E7%A4%BA.png

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/17 11:24:42

色々とアイデアベースで作ってみてもらっています。

**Comment by tommy6073** [comment]
投稿者: - garyuten
投稿日: 2016/09/18 04:37:26

無茶振りされました。




	編集アイコン位置は、 マウスオーバーで表示.png が個人的にいいと思いました。




	そしてドラッグアンドドロップをわかりやすくする件は、以下の2点でどうでしょうか？




	・最初から全行左端(トップページ以外）に触れる感じのアイコンを表示　例）http://fontawesome.io/icon/bars/　大川さんのデザイン案で上下矢印の分




	・ドラッグアンドドロップのアイコン、及び編集メニュー以外の行背景にマウスカーソルが載った時、　*CSSでカーソルを move (移動カーソル)に変更*　参考） [http://www.htmq.com/style/cursor.shtml][1] 




	・トップページ行はドラックさせないので、 マウスカーソルは not-allowed(禁止)でいいかも

    

  [1]: http://www.htmq.com/style/cursor.shtml

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/18 05:27:59

トップページ移動できる仕様らしいです。ブログをトップにしたりできるとか！自由度高くなってます。




	マウスオーバーで出す、かっこいいのですが、押しにくい人が結構いそうな点が気になっています。




	うまく横方向にマウスを動かせないとフォーカス外れてアイコンが消えるという動きになりそう。

**Comment by tommy6073** [comment]
投稿者: - garyuten
投稿日: 2016/09/18 07:06:14

- **ファイル** [backlog_ドラック中.png][1]  を追加 - **ファイル** [backlog_メニューにカーソル時.png][2]  を追加 - **ファイル** [backlog_行にマウスオーバー(何もできない）.png][3]  を追加
河野 哲哉 は書きました:




> トップページ移動できる仕様らしいです。ブログをトップにしたりできるとか！自由度高くなってます。





	自由度高い！！




> マウスオーバーで出す、かっこいいのですが、押しにくい人が結構いそうな点が気になっています。





	それじゃ最初から全部表示させておく感じですかねー




	ドラッグアンドドロップのアイコンと判定の参考例でBacklogのプロジェクト設定のカテゴリ管理のスクショをアップしますね。

    

  [1]: /attachments/download/1747/backlog_%E3%83%88%E3%82%99%E3%83%A9%E3%83%83%E3%82%AF%E4%B8%AD.png
  [2]: /attachments/download/1746/backlog_%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%81%AB%E3%82%AB%E3%83%BC%E3%82%BD%E3%83%AB%E6%99%82.png
  [3]: /attachments/download/1748/backlog_%E8%A1%8C%E3%81%AB%E3%83%9E%E3%82%A6%E3%82%B9%E3%82%AA%E3%83%BC%E3%83%8F%E3%82%99%E3%83%BC(%E4%BD%95%E3%82%82%E3%81%A6%E3%82%99%E3%81%8D%E3%81%AA%E3%81%84%EF%BC%89.png

**Comment by tommy6073** [comment]
投稿者: - garyuten
投稿日: 2016/09/18 07:09:50

- **ファイル** [tweetdeck.png][1]  を追加
参考までにtweetdeckのスクショも。僕個人的に、ドラック中はマウスカーソルをmove(十字の矢印)にするのがしっくりきます。

    

  [1]: /attachments/download/1749/tweetdeck.png

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/24 06:47:06

- **担当者** を - garyuten から 河野 哲哉 に変更
＞河野さん




	こちら、4.0.1 でという事でよかったでしょうか？

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/24 06:47:25

- **カテゴリ** を 追加要望 にセット

**Comment by tommy6073** [comment]
投稿者: 河野 哲哉
投稿日: 2016/09/26 07:30:04

良いと思います＜4.0.1

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/26 07:44:44

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **カテゴリ** を 追加要望 から コンテンツ管理 に変更 - **対象バージョン** を 正式版リリース準備 から 4.0.1 に変更
では次に見送りますー

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:20:47

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:49:17

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:41

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:18

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
ドラッグについては移動アイコンに変更となったためクローズ
