### ISSUE TITLE
「コンテンツ一覧」画面のメニューアイコンが分かりづらい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1176]
（このIssueはRedmineのチケットから移行されています）

作成者: 大川 松樹
作成日: 2016/09/17 12:19

「コンテンツ一覧」画面のメニューアイコンが「…」というカタチで、サブメニューが表示されることに気がつきにくい。
タイトルが長くて短縮されている、という印象を受ける可能性も…。

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/17 03:59:00

- **関連している** [TODO #12939][1] : 管理画面全体のアイコンを調整 を追加
    

  [1]: /issues/12939

**Comment by tommy6073** [comment]
投稿者: - 清末直
投稿日: 2016/09/17 05:26:19

- **担当者** を 河野 哲哉 にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/24 03:42:37

- **プロジェクト** を baserCMSベータテスト から baserCMS に変更 - **カテゴリ** を その他 から 管理画面全般 に変更 - **対象バージョン** を 正式版リリース準備 から 4.0.1 に変更
ツリー構造のUI改善については、4.0.1 に見送ります。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/11/15 06:21:59

- **対象バージョン** を 4.0.1 から 4.0.2 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2017/02/20 03:38:56

- **対象バージョン** を 4.0.2 から 4.1.0 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:01:39

- **優先度** を 通常 から 急いで に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2018/07/09 06:02:16

- **対象バージョン** を削除 (4.1.0)

**Comment by ryuring** [comment]
こちら、4.2 で改善される予定としてますのでクローズします。
