### ISSUE TITLE
メールフォームでマルチチェックボックス時のdivを外すオプション指定が効かない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1177]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2018/06/02 21:31

ここで実装済のチェックボックスから div枠を外すオプション指定が効かない。
http://project.e-catchup.jp/issues/21903

h3. 原因

BcFormHelper.php::select() 内でオプション指定がなされているが、_selectOptions() 内での $attributes['div]値判定が boolean値となっており、オプション指定で div|false、div|0 としても効かせることができない。

h3. 対策

BcFormHelper.php::select() 内 での $div = $this->_extractOption('div', $attributes); で設定している $divをキャストすると良い。
また、メールフィールド設定でのオプション指定は「div|0」とすること。
フィールドオプション指定の記述はあくまで文字列なので、false を書いても処理箇所では「文字列が存在するからtrue」判定される。
よってオプション指定での記述は「0」とし、キャスト時にboolean値＝falseとさせる必要がある。

**Comment by tommy6073** [comment]
投稿者: 渕上 将和
投稿日: 2018/06/02 12:43:40

- **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/72803?detail_id=81889

**Comment by tommy6073** [comment]
投稿者: 渕上 将和
投稿日: 2018/06/02 12:48:26

- **カテゴリ** を メール にセット - **担当者** を 渕上 将和 にセット

**Comment by ryuring** [comment]
改善されていたのでクローズ
