### ISSUE TITLE
公開側サイト内検索に content_id を指定できるようにしたい

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1179]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2018/04/19 17:56

利用場面としては「ブログコンテンツのどれかのみを検索したい」といった点で、ご要望に応えられるため。

**Comment by tommy6073** [comment]
投稿者: 渕上 将和
投稿日: 2018/04/21 06:31:24

- **カテゴリ** を サイト内検索 にセット - **担当者** を 渕上 将和 にセット

**Comment by ryuring** [comment]
@materializing わかりにくいですが、「f」というキーに、content_id を指定すると、絞り込めるはずです。クローズします。
