### ISSUE TITLE
フィード設定編集画面において、フィード一覧のキャッシュ時間が正しく表示されていない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1180]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2015/03/16 23:37

/index.php/admin/feed/feed_configs/edit/1 のフィード一覧のキャッシュ時間の箇所は、
Model の getControlSource() を利用しているが、表示のための配列一覧（選択リスト）が取得できていないため表示されない状態となっている。

**Comment by ryuring** [comment]
再現できず、クローズ
