### ISSUE TITLE
固定ページテンプレート読込時、固定ページプレビューでレイアウトが外れてプレビューされる

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1181]
（このIssueはRedmineのチケットから移行されています）

作成者: 渕上 将和
作成日: 2015/02/02 17:24

* 固定ページカテゴリのデータにレイアウト指定がない場合に起こる
* レイアウト指定がないカテゴリが生成される場面は、固定ページテンプレート読込時

動作仕様として、固定ページカテゴリのデータ内に、レイアウト指定が入っている状態が正しいため、固定ページ取込時に生成される固定ページカテゴリに、レイアウト情報が入るように改修する必要があります。

**Comment by tommy6073** [comment]
投稿者: 渕上 将和
投稿日: 2015/02/03 06:02:51

- **トラッカー** を 問題点 から 課題 に変更 - **題名** を 固定ページプレビュー時、レイアウトが外れてプレビューされる場合がある点を修正 から 固定ページ取込時に生成される固定ページカテゴリに、レイアウト情報が入るようにする に変更

**Comment by tommy6073** [comment]
投稿者: 渕上 将和
投稿日: 2015/02/03 07:46:03

- **トラッカー** を 課題 から 問題点 に変更 - **題名** を 固定ページ取込時に生成される固定ページカテゴリに、レイアウト情報が入るようにする から 固定ページプレビュー時、レイアウトが外れてプレビューされる場合がある に変更 - **説明** を更新 ([diff][1] )
    

  [1]: /journals/diff/26799?detail_id=30171

**Comment by ryuring** [comment]
baserCMS４から仕様が変わったのクローズします。
