### ISSUE TITLE
メンテナンス→バックアップ＆リストアで、スマートフォン設定が引き継げていない

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1182]
（このIssueはRedmineのチケットから移行されています）

作成者: 滝下 真玄
作成日: 2016/08/05 17:48

3.0.7で発生した不具合。
スマートフォンを「対応する」サイトでバックアップ＆リストアを行った場合、PC版しか表示出来なくなります。

もし対応が過去にされていない場合はまだ残っていると思います。
(ぱっと過去チケットを見ましたがなさそうです)

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2016/09/25 10:42:59

- **担当者** を 滝下 真玄 にセット - **対象バージョン** を削除 (3.0.11)
＞滝下さん




	３系において、モバイル、スマートフォンの有効設定の保存先は、DBではなく、install.php となります。なので、リストアで復元されないのが仕様となります。




	ちなみに、４系では、DBに保存する仕様に変更していますので、リストアで復元できるようになっています。




	こちら問題なければクローズお願いします。

**Comment by ryuring** [comment]
クローズします。
