### ISSUE TITLE
[docs] セッション設定の仕組みを新しいものに

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1184]
（このIssueはRedmineのチケットから移行されています）

作成者: 滝下 真玄
作成日: 2013/05/16 01:10

CakeSessionHandlerInterfaceを利用する

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2013/08/11 02:12:53

- **カテゴリ** を その他 にセット - **担当者** を 滝下 真玄 にセット
この件、できれば対応をお願いしたいです。




	セッション設定は、現在、




	/lib/Baser/Config/session.php




	に書いてあり、




	/app/Config/session.php




	で変更する仕組みにしています。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2013/11/10 10:29:48

- **プロジェクト** を baserCAMP から baserCMSベータテスト に変更 - **カテゴリ** を削除 (その他)

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2013/11/10 10:48:59

- **対象バージョン** を 3.0.0 beta にセット

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2013/11/10 10:50:45

- **優先度** を 通常 から 今すぐ に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2013/11/10 17:27:45

- **プロジェクト** を baserCMSベータテスト から baserCMS機能要望 に変更
この件、現状でも特に問題なさそうなので、一旦、機能要望プロジェクトに移します。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2013/11/24 11:46:06

- **対象バージョン** を削除 (3.0.0 beta)
一旦、３のリリースタスクから外しますね。

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2014/11/27 13:10:34

- **優先度** を 今すぐ から 通常 に変更

**Comment by tommy6073** [comment]
投稿者: 江頭 竜二
投稿日: 2014/11/28 12:05:50

- **カテゴリ** を リファクタリング にセット - **開始日** を削除 (2013/05/16)

**Comment by tommy6073** [comment]
投稿者: 木田 亮介
投稿日: 2015/05/20 13:55:46

- **プロジェクト** を baserCMS機能要望 から baserCMS に変更 - **カテゴリ** を削除 (リファクタリング)

**Comment by ryuring** [comment]
CakePHP4系対応があるためこちらはクローズ
