### ISSUE TITLE
スマートフォンサイトでお問い合わせを送信した際、リダイレクトでパソコンサイトに飛ぶ

### ISSUE THREAD

**Issue by tommy6073** [baserproject/basercms#1185]
（このIssueはRedmineのチケットから移行されています）

作成者: 阿部 拓弥
作成日: 2017/09/29 13:26

bc_sampleテーマで、スマートフォンサイトでお問い合わせを送信した際、リダイレクトでパソコンサイトに飛ぶので、デフォルトの設定を「パソコンサイト」から「スマートフォンサイト」に変更する必要あり

現在
スマホサイトお問い合わせ→パソコンサイト

期待
スマホサイトお問い合わせ→スマホサイト

**Comment by tommy6073** [comment]
投稿者: 阿部 拓弥
投稿日: 2017/09/29 04:27:42

- **優先度** を 低め から 通常 に変更

**Comment by ryuring** [comment]
スマホサイトのお問い合わせフォームについて、パソコンサイトのお問い合わせのエイリアスで作成しているのが原因。

ただし、スマートフォンでアクセスしている場合は、一旦、パソコンサイトにリダイレクトした上で、ユーザーエージェントで判断してスマホのサイトにリダイレクトするため問題ない。

クローズします。
