### ISSUE TITLE
【システム】メインサイトがSSLで、サブサイトがSSLを使用していない場合に "BcEnv.siteUrl" にhttpsから始まるURLを設定するとメールフォームの送信エラーになる

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1189]
## 概要
あまり起きない状況かと思いますが、以下の条件が揃った時にサブサイトのみメールフォームの送信エラーになります。

- メインサイトがSSLを使用している
- サブサイトが別ドメインを使用しておりSSLを使用していない
- "BcEnv.siteUrl" にhttpsから始まるURLを設定している

具体的には、メールフォームのindexページにアクセスしても "BASERCMS" cookieが発行されず、そのまま確認ボタンを押すと不正なリクエストと判断され、エラーになります。
 
## 環境
baser4.1.5

**Comment by ryuring** [comment]
@seto1 開発環境で同じ状況を作ってみたのですが、再現できず、メール送信できてしまいました。
環境に依存する問題かもしれないですね。

**Comment by seto1** [comment]
@ryuring ご確認ありがとうございます。
発生したサイトがカスタマイズが入ったものだったので、再度素のbaserの4.1.5と4.1.9-devで確認したところ、再現できました。
なにか条件が分かったら記載しますね。

**Comment by seto1** [comment]
4.9.0-devだと再現しないためクローズします。
