### ISSUE TITLE
【メール】テキストエリア項目について、未入力にて送信した場合送信メールに見出しが表示されない（他の項目については、未入力の場合見出しのみ表示される）

### ISSUE THREAD

**Issue by morishita1222** [baserproject/basercms#1196]
## 概要
メールフォームにて、テキストエリア（入力非必須）の内容を未入力にて送信すると、
問い合わせ受付メール・自動返信メール双方でテキストエリア項目が項目名ごと非表示となる。
（テキスト項目・ラジオボタン項目等、他タイプの入力項目については未入力にて送信すると項目名のみメールに表示される）

baserCMS version : baserCMS 4.1.8
 
## TODO

- 未入力項目のメール表示での扱いを統一したいです。
他項目に合わせて、テキストエリア項目未入力の場合メールに項目名を表示する
テキストエリア項目に合わせて、他項目未入力の場合メールに何も表示しない

 
 
## 備考

**Comment by ryuring** [comment]
@morishita1222 統一したほうがよさそうですね。プルリク作ってみてください。
