### ISSUE TITLE
メールフォームでマルチチェックボックス時のdivを外すオプション指定が効かない

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1206]
## 概要
以前まで使用できていたマルチチェックボックス時のdivを外すオプション
div|
が4.2.0にバージョンアップすると効かなくなる。
（BcFormヘルパーの仕様が変わったため）

baserCMS version : 4.2
 
## TODO
 $divに$attributes['div']を渡す時に、falseを渡せるようにする。

後方互換を考えて、$div == ''の場合と $div == '0'どちらでもfalesが返るようにする。
/lib/Baser/View/Helper/BcFormHelper 1019行目付近
```
if ($div == '' || $div == '0' ) {
	$div = false;
}
```

**Comment by ryuring** [comment]
@katokaisya こちらの件、 https://github.com/baserproject/basercms/commit/706b1ea03999926e11fee96f32617d449766e4c6 で解消していたのでクローズします。
