### ISSUE TITLE
urlのアクション部分に"://"があるとトップページにリダイレクトしてしまう問題

### ISSUE THREAD

**Issue by CUiwamoto** [baserproject/basercms#1207]
## 概要
自分のローカル環境にて、通常であれば
`http://basertest.localhost:8888/http://`
のようなurlが指定された時404が表示されて然るべきですが、トップページに飛んでしまいます。
これはhttpに限ったことではなく、aaaa://でも発生し、://が悪さしているものと思われます。

404となる例
`http://basertest.localhost:8888/http://basercms-dev4.localhost:8888`
→8Controller が見つかりません。
`http://basertest.localhost:8888/http:`
→HttpController が見つかりません。（遷移時に:は消える）

404とならない例
`http://basertest.localhost:8888/http://http://`
`http://basertest.localhost:8888/aaaa://`

baserCMS version : 4.2.0
 
## TODO
ルーティングで弾けていないもしくはトップにリダイレクトする記述があるのであれば変更し404を表示する。
 
 
## 備考

別途記載する内容があれば書きます。

**Comment by ryuring** [comment]
@CUiwamoto `http://localhost/aaaa://` というURLを入力する事自体は可能性として高くないと思います。その手前の段階となる、「違うURLにリダイレクトしてしまう」という事象の再現方法を教えて下さい。

**Comment by CUiwamoto** [comment]
@ryuring クライエント様によるurl手打ちでのバグチェックの際に発見されたものになります。
通常起こりえないurlでの遷移ですが、クライエント様からのリクエストがあり報告させていただきました。

**Comment by ryuring** [comment]
@CUiwamoto これって先日一緒に調査しましたよね？CakePHPの仕様でしたっけ？？

**Comment by gondoh** [comment]
@ryuring @CUiwamoto これみたけど、REQUEST_URI にフルパスが入った場合のBaser/Nerwork/CakeRequest::__url() [Line: 251] が判断おかしいっすね。
http://koseki.hatenablog.com/entry/20120210/phpuri

://がある場合フルパスでRquestがあったととみなして基本URLからURIを出そうとしてるけど合致してないんで内部判別のURIがfalseになってトップページへのアクセス判別になる。

> トップページにリダイレクトしてしまう問題
リダイレクトではないですよね？これ

> CakePHPの仕様でしたっけ？？
バグと仕様の曖昧な点ですがCakePHPが動作している箇所ですね。
これを404としたい場合は下記ですかね。

[Line: 254]
```
- $uri = substr($_SERVER['REQUEST_URI'], strlen(Configure::read('App.fullBaseUrl')));
+ if (strpos($_SERVER['REQUEST_URI'], Configure::read('App.fullBaseUrl')) === 0) {
+   $uri = substr($_SERVER['REQUEST_URI'], strlen(Configure::read('App.fullBaseUrl')));
+ } else {
+   $uri = $_SERVER['REQUEST_URI'];
+ }
```

**Comment by ryuring** [comment]
@gondoh Cake修正しないといけないよね。
こちらに則って修正お願いします。
https://github.com/baserproject/basercms/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84#cakephp%E3%81%8C%E6%8F%90%E4%BE%9B%E3%81%99%E3%82%8B%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E4%BF%AE%E6%AD%A3%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88%E3%81%AE%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%83%AB%E3%83%BC%E3%83%AB

**Comment by ryuring** [comment]
@CUiwamoto @gondoh ↑どちらかお願いします

**Comment by gondoh** [comment]
@CUiwamoto よしまかせた
