### ISSUE TITLE
[フォーラム]ブログの編集画面でアップローダーを開くと、画像が折り返されず、画面内に収まらない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1214]
## 概要
フォーラムからの改善要望です。
https://forum.basercms.net/t/topic/134

admin-thirdテーマを適用中に、ブログでアップローダーのウィンドウを開くと、アップロードした画像が折り返されず、横に10枚並んだ状態となします。
IEでのみ再現しました。
ご確認よろしくお願いします。

## 環境
baserCMS version : 4.2.1
ブラウザ: IE11

**Comment by ryuring** [comment]
@seto1 再現はできたのですが、IE11の開発ツールがうまく動かず、、、一度見てもらえませんか？

**Comment by ryuring** [comment]
こちらでフィックスですね。
https://github.com/baserproject/basercms/pull/1226
