### ISSUE TITLE
[フォーラム]ブログ編集画面から画像をアップロードする際のデフォルトの画像サイズを選択できるようにしてほしい

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1215]
## 概要
フォーラムからの改善要望です。
https://forum.basercms.net/t/topic/134

> サイズが常に「小」が初期選択されていますので、
ほかのよく使うサイズを初期設定で選択できるような仕掛けがあると
いいなと考えます。（元サイズを常に選択した状態で使いたいです。）

Cookieなどに選択したサイズを保存しておいて、前回選択した画像サイズを参照できるような形だと便利かと思います。

**Comment by ryuring** [comment]
@seto1 機能要望は掲載先が違いますね。
https://github.com/baserproject/basercms/wiki/%E8%A6%81%E6%9C%9B%E3%81%AE%E3%83%95%E3%82%A3%E3%83%BC%E3%83%89%E3%83%90%E3%83%83%E3%82%AF

**Comment by seto1** [comment]
@ryuring 了解です。移動しておきます。
