### ISSUE TITLE
ブログ記事詳細画面で、オートリダイレクトが効かない

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1237]
## 概要
コンテンツとしてブログコンテンツが /news/ で存在する場合として、
サブサイトとして、スマートフォン用サイトをエイリアスを /s/ で作成しているとする。
サブサイト設定内の「デバイス・言語」項目内「メインサイトから自動的にリダイレクト」を有効化しているとき、とする

スマホで /news/archives/1 にアクセスすると、/s/ 側にリダイレクトしない。
期待するのは、/news/archives/1 にスマホでアクセス時、/s/news/archives/1 に遷移すること。

baserCMS version : 4.2.2
 
## 想定される原因のところ

/lib/Baser/Lib/BcSite.php::shouldRedirects() 内の existsUrl() による判定時、コンテンツの存在チェックを行っているが、ブログ記事の場合、コンテンツのURLではなく、存在判定のURLとして「/news/archives/1」（$this->here）が利用されているため、コンテンツが存在しない＝リダイレクトしない、となっている

**Comment by ryuring** [comment]
@materializing 余力ありましたら調査お願いしますー

**Comment by ryuring** [comment]
@materializing 
こちらのコミットで解決しました。
https://github.com/baserproject/basercms/commit/e8fe36dd23c156c7b19209a3c6ef0aec05bd3cc8
https://github.com/baserproject/basercms/commit/10399e01c210f94ff5b61316f5d6d5ab52584e0a
