### ISSUE TITLE
admin-thirdテーマでコンテンツが重複して表示される

### ISSUE THREAD

**Issue by morishita1222** [baserproject/basercms#1242]
## 概要

admin-thirdテーマで同じコンテンツが重複して表示される。

baserCMS version :
baserCMS 4.2.1 

<img width="222" alt="スクリーンショット 2019-09-18 20 42 50" src="https://user-images.githubusercontent.com/46368572/65146243-491a1700-da56-11e9-91ec-05dfee97eabc.png">

## TODO
- ゴミ箱に入ったコンテンツをメニューから除外する
- コンテンツごとにメニューに表示するかどうかと表示名称の設定機能を実装

**Comment by ryuring** [comment]
@morishita1222 再現できません。再現方法を教えて下さい。

**Comment by kaburk** [comment]
@ryuring 
おそらく同一名称のコンテンツが別フォルダやサブサイトにある場合に発生する件と思われます。
不具合というより仕様ですが、実際にありえる使い方で、そういう場合に分かりづらいのでなんとかしたいところですね。
---------------------------------------------------
<img width="636" alt="スクリーンショット 2019-09-19 10 38 39" src="https://user-images.githubusercontent.com/310333/65206545-b5822e00-dac9-11e9-96a2-7c23e036bce0.png">

**Comment by ryuring** [comment]
@kaburk ありがとうございます。コンテンツごとにメニューに表示するかどうかと表示名称の設定機能が必要ですね。
取り急ぎは、設定ファイルで対応する方法があります。

```
$config['BcApp.adminNavigation.Contents.BlogContent2.menus.BlogCategories2.disable'] = true;
```

**Comment by morishita1222** [comment]
こちら、再現状況を確認できましたので報告します。
削除済みのコンテンツが表示されてしまう（ゴミ箱内のコンテンツが表示される）ことが原因のようです。
ゴミ箱を空にしたところ、コンテンツの重複表示は解決しました。

@kaburk
> おそらく同一名称のコンテンツが別フォルダやサブサイトにある場合に発生する件と思われます。

こちらも自環境で再現しました。サブフォルダであっても、名前は重複させない方が管理画面の見た目的にはいいですね。

**Comment by kaburk** [comment]
@ryuring @morishita1222 

> 削除済みのコンテンツが表示されてしまう（ゴミ箱内のコンテンツが表示される）ことが原因

あ、こっちは仕様ではなく不具合ですね、、、

**Comment by ryuring** [comment]
@kaburk @morishita1222 ですね。TODO にまとめました。↑

**Comment by ryuring** [comment]
@morishita1222 @kaburk 取り急ぎ、ゴミ箱に入っているものが表示されてしまう問題は改善しました。
サブサイトやサブフォルダの問題は、別途 Issue を作成しました。
https://github.com/baserproject/basercms/issues/1276
