### ISSUE TITLE
【admin-thirdテーマ】ウィジェット管理 ウィジェット内のラジオボタンが押せない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#1246]
## 概要
ウィジェット管理 にて年別アーカイブ等を追加後、記事件数表示のラジオボタンが押せないようです。

baserCMS version : 4.2.2
  
## 備考

一度保存後、画面をリロードすると選択できるようになるようです。

---------------------------------------------------
<img width="555" alt="スクリーンショット 2019-09-18 21 39 52" src="https://user-images.githubusercontent.com/310333/65149618-68687280-da5d-11e9-8e87-84ceb11096ff.png">

**Comment by ryuring** [comment]
軽く調査。
おそらく、bootstrapで、イベント登録され、クリック時にクラスが切り替わる仕様だが、
配置直後にDOMの名称がリネームされる仕様となっているのが影響している様子。
DOMの特定がうまくいっておらず、左ペインの隠されたラジオボタンが切り替わってしまっている。
