### ISSUE TITLE
更新日時を自動更新するようにして欲しい

### ISSUE THREAD

**Issue by h3zjp** [baserproject/basercms#1249]
## 概要
現状、記事の作成日時と更新日時を手動で書き換え出来るようになっているかと思いますが、
記事の更新日時を自動で更新出来るように設定を追加して頂けると、非常に嬉しいです。

下記備考のような感じで記事毎に設定が出来ると良いかなと思っています。

以上、宜しくお願いします。

baserCMS version : 4.2.2
 
## 備考
更新方法
◉ 通常更新 (自動で更新する)
○ 手動で更新する
[2019-09-23] [00:00]

**Comment by ryuring** [comment]
@h3zjp こんにちは。まず確認させてください。
ブログ記事のことでしょうか？固定ページのことでしょうか？
どちらにしても手動で書き換えることができそうな「更新日時」というフィールドはないのですが、正式名称は、「更新日時」でしょうか？

**Comment by h3zjp** [comment]
失礼しました。
｢固定ページ｣  の編集ページの "オプション" タブの中の "作成者" の項目に、
[更新日] と書かれた欄があり、その "更新日" を自動で書き換えたいというのが
今回の issue の内容です。

![](https://ul.h3z.jp/BZprYxTY.png)

以上、宜しくお願いいたします。

**Comment by ryuring** [comment]
@h3zjp なるほど、こちらですね。調整します。

**Comment by ryuring** [comment]
@h3zjp 検討したところ、記事ごとで設定できるのが一番いいですが、記事ごとに設定できるようにする場合、データベース構造を変更せねばならず、リリース版に入れ込むのが時間がかかりそうなので、暫定策として、全体設定を設定ファイルでできるようにしました。
デフォルトは「更新する」になります。これであれば、次のバージョンに取り込めます。
https://github.com/baserproject/basercms/commit/ca2cb4890667b4791551862d885a2c99a631eac3

**Comment by ryuring** [comment]
反応がないので一旦、クローズ

**Comment by h3zjp** [comment]
返事が遅くなってしまい、申し訳ありません。
バージョン 4.2.4 で反映して下さっていたのですね (気付きませんでした)
アップデートして確認しましたが、確かに「更新日」が編集ページを表示した時間に変わっていました。
有難うございました。
