### ISSUE TITLE
コンテンツ一覧画面でコンテンツを移動した際に、どこのURLからどこへ移動したのか、が判る形式で操作ログを取るようにする

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1254]
## 概要
ユーザからの要望のためissue発行。
移動前のURLと移動後のURLがわかるようになる仕組みをご要望。
操作ログとして残るようにしておくことで、あとで確認できるようにするため。

baserCMS version : 4.2.2
 
## TODO
- [ ] コンテンツ移動操作をdblogs に保存し「最近の動き」でわかるようにする

**Comment by ryuring** [comment]
@materializing 仕様いいと思います。アサインしておきますね。
