### ISSUE TITLE
【システム】admin-thirdテーマ：同じ名称のコンテンツを作成した場合メニューに重複して表示されてしまう

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1276]
## 概要
サブサイトや、サブフォルダ等で同じ名称のコンテンツを作成した場合、メニュー重複して表示されてしまいわかりにくい。

baserCMS version : 4.2.4

## 備考

サブサイトごとにメニューを切り替えるか、メニューの名称を変更できるようにするなど、仕様検討要。

**Comment by kaburk** [comment]
こちら別課題で解決済みのようでしたのでクローズします。

**Comment by ryuring** [comment]
@kaburk 確認ありがとうございます！
