### ISSUE TITLE
ブログのカテゴリアーカイブで、閲覧中のブログカテゴリ情報をビュー側で取得したい

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1279]
## 概要
カテゴリアーカイブで、閲覧中のブログカテゴリ情報が欲しいなーって思うときがあるため。

baserCMS version : 4.2.3

**Comment by ryuring** [comment]
@katokaisya 「欲しいなーっ」てときの具体例を教えてくださいw

**Comment by materializing** [comment]
@ryuring ブログカテゴリのカスタマイズで、プラグイン等でブログカテゴリに対して関連情報（例: BlogCategoryImage）をもたせているときが該当します。
現在のブログカテゴリのid情報がビュー側に在れば、関連情報を取りやすくてカスタマイズしやいので欲しいなーって内容であります。
