### ISSUE TITLE
【ブログ】タグアーカイブで、閲覧中のブログタグ情報をビュー側で取得したい

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1280]
## 概要
ブログタグアーカイブで、閲覧中アーカイブのブログタグ情報が欲しいなーって思うときがあるため。

baserCMS version : 4.2.3

**Comment by ryuring** [comment]
@katokaisya 欲しいなーって時の具体例を教えてくださいw

**Comment by materializing** [comment]
@ryuring こっちの件（#1279）と似てまして、ブログタグのカスタマイズで、プラグイン等でブログタグに対して関連情報（例: BlogTagImage）をもたせているときが該当します。
現在のタグアーカイブのタグのid情報がビュー側に在れば、関連情報を取りやすくてカスタマイズしやいので欲しいなーって内容であります。

**Comment by ryuring** [comment]
@materializing なるほど了解です。実装する方向ですすめましょうか。

**Comment by kaburk** [comment]
マージ済みのようでしたのでクローズします。
