### ISSUE TITLE
管理画面においてWEBとWebの表記が混在している

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1306]
## 概要
管理画面においてWEBとWebの表記が混在している

baserCMS version : 4.3.0-dev
 
- 「Webサイト」で全文検索すると59箇所
- 「WEBサイト」で全文検索すると101箇所
- 一括置換後に翻訳ファイルの生成が必要

**Comment by ryuring** [comment]
@seto1 ネットで検索すると「Webサイト」の方が圧倒的に多いですね。

**Comment by seto1** [comment]
Webですかね
https://note.com/gita_mw/n/n8db22d918b93

**Comment by ryuring** [comment]
Webですね
