### ISSUE TITLE
ブログタグアーカイブページで存在しないタグを指定した場合404ページに遷移してほしい

### ISSUE THREAD

**Issue by t-uchiba** [baserproject/basercms#1312]
## 概要
ブログタグアーカイブページURLにて、CMS内に存在しないタグ名を指定した際でもステータス200が返却されるが、404ページに遷移してほしい

baserCMS version : 4.2.5

**Comment by gondoh** [comment]
こちら解決されていない状態を確認しました。

**Comment by ryuring** [comment]
@gondoh こちらの件ですが、次の２つのコミットにて改善が入っています。

https://github.com/baserproject/basercms/commit/8c6ec97d1b6de4be1ab9b819665ced2260da3808
https://github.com/baserproject/basercms/commit/6607510e6fdb6f27c271988971d0df849de75b80

その上で、実際に動作確認をしたのですが、再現できず、存在しないタグの記事一覧ページを表示しようとすると、BlogController の 333行目を通りNotFoundになります。

「解決されていない」というのは具体的にどういう状態を指すのでしょうか？？

**Comment by gondoh** [comment]
@ryuring 
最新版のデモで確認したところ404ステータスともならず、404ページともならないことを確認しました。
http://trial.basercms.net/news/archives/tag/%E5%AD%98%E5%9C%A8%E3%81%97%E3%81%AA%E3%81%84%E3%82%BF%E3%82%B0

**Comment by ryuring** [comment]
@gondoh デモサイトのバージョンは、4.3.1 だからだと思います。

**Comment by gondoh** [comment]
@ryuring oh..失礼しました。再度確認します。
