### ISSUE TITLE
コンテンツプレビュー時、アイキャッチ画像がプレビューで表示されない

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1321]
## 概要
各コンテンツにアイキャッチ画像が設定できて、プレビューボタンが表示されているコンテンツで確認。
・例: 固定ページのプレビュー、ブログコンテンツのプレビュー、メールコンテンツのプレビュー
プレビュー時、ファイルアップロード欄に設定した画像が表示されない。

baserCMS version : 4.3.1-dev
 
 
## 備考

- 固定ページの場合
    - ファイルボタンに設定した内容そのものが、プレビュー時に$this->request->params['Content']に送られてきていない
- ブログコンテンツの場合
    - ファイルボタンに設定した内容は、プレビュー時に$this->request->params['Content']に送られてきてはいる

**Comment by ryuring** [comment]
@materializing バグですね、修正可能であれば修正お願いします。
