### ISSUE TITLE
サンプルテーマにて、確認画面に遷移できなかった時に「必須」ボタンのスタイルが外れる

### ISSUE THREAD

**Issue by Diwamoto** [baserproject/basercms#1323]
## 概要
baserCMSのサンプルテーマにデフォルトで搭載されているお問い合わせについて、
何も入力せずに確認画面へと遷移しようとして失敗すると「必須」ボタンのスタイルが外れ、文字列がフィールドタイトルの後ろにくっつく形になります。

baserCMS version : 4.3.1
 
## TODO
- おそらくタグが原因だと思うので、該当箇所のタグを確認する
 
## 備考

trial.basercms.net
でも再現しました。

**Comment by Diwamoto** [comment]
追記です。

その状態で確認画面に遷移するとスタイルが当たっていない状態が引き継がれます。

**Comment by ryuring** [comment]
@Diwamoto バグですね、修正可能であれば修正お願いします。
