### ISSUE TITLE
ブログコンテンツ設定の一覧表示件数で、100より大きい件数した場合、100件迄しか記事が取得できない

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1331]
## 概要
利用ユーザからのフィードバック。
ブログコンテンツ設定の一覧表示件数で、100より大きい件数した場合、
公開側で取得するブログ記事データが、強制的に1ページずつ100件迄の取得動作となっている。

baserCMS version : 4.3.0
 
## 備考

CakePHP側の制限の影響。
https://book.cakephp.org/2/ja/core-libraries/components/pagination.html#id5
> CakePHP のデフォルトでは、一度に取り出せる行数を 100 に制限しています。

**Comment by ryuring** [comment]
@materializing バリデーションをかける方針になりましたのでクローズします。
https://github.com/baserproject/basercms/pull/1333
