### ISSUE TITLE
アップデート画面のレイアウトが旧管理画面になっている

### ISSUE THREAD

**Issue by Diwamoto** [baserproject/basercms#1334]
## 概要
画面が旧型のままになっています。
ユーザーの目に入る場所かと思いますので、更新した方がいいかと思いますが、どうでしょう。。？
後、もしかするとアップデートボタンが表示される条件式が合ってないかもしれません。
ご検討よろしくお願いします。

baserCMS version : 4.3.2
 
## TODO
アップデート画面を新管理画面に対応させる。
アップデートボタンの表示条件式を確認する。

 
## 備考
4.3.1-dev->4.3.2-devへとアップデートする際にアップデートするボタンがでらず、フロントはメンテナンス状態であった。devバージョンはフロントからのアップデートに対応していない可能性？

**Comment by ryuring** [comment]
@Diwamoto devバージョンは正常アップデートを保証できないため、ボタンを表示しないしようです。
デザインは変えないといけないですね。

**Comment by Diwamoto** [comment]
@ryuring 仕様の確認ありがとうございます。

こちらですが、軽く調査したところupdate画面のviewの変数`currentPrefex`は`front`、`layoutPath` は`admin`、`layout`は`default`となっておりました。
同じフロント側からadmin-thirdを利用していると思われるインストール画面では`currentPrefex`は`admin`、`layoutPath` は`admin`となっておりました。
どこのメンバがレイアウトを指定しているかわからなかったので、`$this->theme`や`$this->layout`などをいじってみましたが特に変化はなかったです。

引き続きどこのメンバがレイアウトを握っているのか調査します。
