### ISSUE TITLE
【ブログ】indexページのツールバーのエディターへのリンクを管理画面ブログ記事一覧にしたい

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1335]
## 概要
ログイン状態で、表示側のブログindexページのツールバーのエディターへのリンクが
現在、ブログコンテンツ編集画面へのリンクとなっているが、
ブログ記事一覧へのリンクに変えてほしいという要望が上がっています。

baserCMS version : 4.3.0

**Comment by ryuring** [comment]
@katokaisya 変更する方向ですすめてください

**Comment by kaburk** [comment]
baserCMS version : 4.3.2 で対応済みのようでしたのでクローズします。
