### ISSUE TITLE
フォームの設定画面にて、「送信先メールアドレス 」と「BCC用送信先メールアドレス」の項目が離れている

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1357]
## 概要
メールフォームを受信するメールアドレスの設定について、

- 「送信先メールアドレス 」と「BCC用送信先メールアドレス」の項目が離れているため、手順に抜けが発生する可能性がある。

- 「BCC用送信先メールアドレス」については初期表示状態では「オプション」（admin-thirdでは「詳細設定」）内に隠れているため、存在を認識しづらい

baserCMS version :

**Comment by ryuring** [comment]
@cu-morishita 開発方針としてできるだけシンプルにというのがあり、初期状態で表示するコントロールをできるだけ少ないしたいです。その上でBCCはオプション扱いという認識ですがいかがでしょう？

**Comment by cu-morishita** [comment]
@ryuring 

> 開発方針としてできるだけシンプルにというのがあり、初期状態で表示するコントロールをできるだけ少ないしたいです

方針について、承知しました。
個人的には、似た項目（ここではメールアドレス入力項目）はできるだけ近くにまとまった状態の方が、見た目上は初期表示項目が増えるものの手順としてはシンプルになるのではないかと思います。

- 「送信先メールアドレス 」と「BCC用送信先メールアドレス」はどちらも初期表示に

- 「送信先メールアドレス 」と「BCC用送信先メールアドレス」はどちらもオプション内に

のように、場所を統一したほうが良いのではないかと考えているのですが、いかがでしょうか？

**Comment by ryuring** [comment]
@cu-morishita おっしゃることもごもっともですね。

ただ、オプション（admin-thirdでは「詳細設定」）かそうでないかといった観点においては、サブかメインかという考え方になります。

そして「誰が」設定するかによって、サブかメインかを考えるべきかと思います。

例えば、新規構築をバンバンされる方（高度なユーザー）であれば、似た項目がまとまっていた方がいいかと思います。

ただ、リテラシーが高くない方からすると、メインのメールアドレスを変更する可能性とBCC設定を行う可能性を比べた場合、BCC設定を行う可能性が低いでしょう。

ユーザーインターフェイス設計の概念からいくと、高度なユーザーより、リテラシーが高くないユーザーに合わせたいと考えます。

つまり、詳細設定は、高度ユーザー向けの機能をまとめた設定と考えてください。

いかがでしょう？

**Comment by ryuring** [comment]
@gondoh こちらどう思います？

**Comment by gondoh** [comment]
@ryuring @cu-morishita 
感覚的にはBCCは初期項目ではないですね。
ただTO(別のメールアドレスに送信する)の近くに存在するべきだという意見ももっともだと思います。

> 「送信先メールアドレス 」と「BCC用送信先メールアドレス」の項目が離れているため、手順に抜けが発生する可能性がある。
この件について、近くに置くことで忘れにくくなる可能性もありますが防げるわけでは有りません。今回の件において要点から外して考えさせてもらいます。

> 「BCC用送信先メールアドレス」については初期表示状態では「オプション」（admin-thirdでは「詳細設定」）内に隠れているため、存在を認識しづらい
視認性については、初期表示にて重要度・利用率が低いものは表示しないという観点から、どちらを取るかという話になるかと思います。

TOについては、管理者用メールアドレスに送らない場合に表示される項目で、初期状態では非表示になっていることもあり、レイアウト上その下に配置できるのであれば送信先のチェックを変更した際に真下に表示できるとわかりやすいとも思いました。
ただ、管理者用メールアドレスに送り且つBCCに送ることも存在すると思います。

それらをぐるぐる考えると特殊な設定として、今のままのオプションのほうがいいのかなと思います。

**Comment by ryuring** [comment]
@cu-morishita いかがでしょう？
もし、今のままにするにしても、指摘頂いたお陰で、「どういうものをオプションにすべきか」というガイドができたかなと思っています。ドキュメントに明示化しておこうと思います。ありがとうございます。

**Comment by cu-morishita** [comment]
ご回答ありがとうございます。
現在の配置となっている経緯を再認識することができました。

@gondoh
> TOについては、管理者用メールアドレスに送らない場合に表示される項目で、初期状態では非表示になっていることもあり、レイアウト上その下に配置できるのであれば送信先のチェックを変更した際に真下に表示できるとわかりやすいとも思いました。
> ただ、管理者用メールアドレスに送り且つBCCに送ることも存在すると思います。

こちら、たしかにそのとおりですね！
様々なケースがある中で、現在の形が最適なのかな、という気もします。

 @ryuring 
> もし、今のままにするにしても、指摘頂いたお陰で、「どういうものをオプションにすべきか」というガイドができたかなと思っています。ドキュメントに明示化しておこうと思います。ありがとうございます。

そうですね、改めてオプションの基準を再認識できたので、今後の新メニューや新項目にも対応できるかと思います。ありがとうございます！

**Comment by ryuring** [comment]
@cu-morishita  了解しました。 ガイドラインにまとめておきました。
https://github.com/baserproject/basercms/wiki/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%82%A4%E3%83%B3%E3%82%BF%E3%83%BC%E3%83%95%E3%82%A7%E3%82%A4%E3%82%B9%E8%A8%AD%E8%A8%88%E3%82%AC%E3%82%A4%E3%83%89%E3%83%A9%E3%82%A4%E3%83%B3

こちらはクローズさせて頂きますね。
