### ISSUE TITLE
【システム】パスワードの変更処理の仕様改善

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1410]
## 概要
プルリクエスト  https://github.com/baserproject/basercms/pull/1409 よりの指摘として、現状の仕様としては、次のリスクが残っている。
- 任意のユーザのログインを妨害できる
- 複数アカウントが同じメールアドレスを登録している場合、予期しないアカウントのパスワード変更が起きる
baserCMS version : 4.3.3
 
## TODO
- [ ] タイムリミットを設けて変更URLを生成しその情報をメールで送る機能
- [ ] メールアドレスのユニーク化

**Comment by yama** [comment]
@ryuring こちらもしよければ実装します。

> タイムリミットを設けて変更URLを生成しその情報をメールで送る機能

よく見かけるアクティベーション手続きのイメージですが、メアドに紐付いた複数のアカウントそれぞれのアクティベーションURLを発行します。なので、

> メールアドレスのユニーク化

上記に関しては別課題として先送りにできると思います。いかがでしょうか？

**Comment by ryuring** [comment]
@yama ご提案ありがとうございます

> メアドに紐付いた複数のアカウントそれぞれのアクティベーションURLを発行するものとします。

これがちょっと気持ち悪い感じはありますね。

@gondoh @kaburk どう思います？？

**Comment by yama** [comment]
@ryuring 補足です。アカウントとメアドを1対1で紐付ける普通の運用をしている場合は、一般的な分かりやすいアクティベーションメールが送信されるだけなので、アクティベーションの仕組みだけでも先に実装してしまうのはアリかなと思ったのが、今回の提案の主な趣旨です。ほとんどのユーザにとっては普通の改善として受け入れられると思います。

とりあえず実装した後で、単一のメアドを複数のアカウントに割り当てられる仕様は考え直そう、と進め方もできると思います。いかがでしょうか？

**Comment by gondoh** [comment]
ユニーク化賛成です。

**Comment by ryuring** [comment]
> ユニーク化賛成です。

今回ユニーク化を後回しにしようという話なので論点がズレてますw

@gondoh

**Comment by gondoh** [comment]
あれ？ｗ
> メアドに紐付いた複数のアカウントそれぞれのアクティベーションURLを発行するものとします。
これの方でしょうか。

**Comment by ryuring** [comment]
@gondoh です！

**Comment by gondoh** [comment]
> メアドに紐付いた複数のアカウントそれぞれのアクティベーションURLを発行するものとします。

同じメールアドレスで登録されたユーザーそれぞれにパスワード変更のURLを発行してどういう方法でそのユーザに通知するのかという点について、私がイメージできてないです。

**Comment by yama** [comment]
@gondoh 了解です、のちほどサンプル文面書いてみますね

**Comment by yama** [comment]
メールアドレスに紐付いたアカウントがひとつの場合（普通はこちら）

```
タイトル：パスワード変更リクエストを受け付けました

https://example.com/?reset_token=d3e6d18850d23c6a17f8e46129c98406
パスワード変更リクエストを受け付けました。上記のリンクを
クリックしてパスワード変更画面を開いてください。
このリセットURLはmm月dd日H時M分まで有効です。
```

ひとつのメールアドレスに紐付いたアカウントが複数ある場合

```
タイトル：パスワード変更リクエストを受け付けました

パスワード変更リクエストを受け付けました。リクエストいただいた
メールアドレスに紐付いたアカウントが3つあるため、下記の3つの
リセットURLを発行いたします。

https://example.com/?reset_token=d3e6d18850d23c6a17f8e46129c98406
アカウント名 : xxx

https://example.com/?reset_token=d3e6d18850d23c6a17f8e46129c98406
アカウント名 : yyy

https://example.com/?reset_token=d3e6d18850d23c6a17f8e46129c98406
アカウント名 : zzz

パスワードをリセットしたいアカウントのリセットURLをクリックして
パスワード変更画面を開いてください。
これらのリセットURLはmm月dd日H時M分まで有効です。
```

複数ある場合は少し分かりにくくなりますが、仕方ないかな、、と思います。

**Comment by ryuring** [comment]
@gondoh 確認おなしゃす

**Comment by gondoh** [comment]
@ryuring @yama 
なるほど、同じメールアドレスなので一人（1アドレス）に送信するってことですね。
現在の最初の一つが変更され、想定しないアカウントのパスワードが変更されるという問題が解消されるのでいいと思います！

**Comment by yama** [comment]
@gondoh @ryuring 後ほどプルリクまとめます。工数多そうなので数日かかるかも。

**Comment by yama** [comment]
遅くなりましたが4.4.3目標で対応します。年内に出せるといいな。

**Comment by yama** [comment]
@ryuring @gondoh 

![image](https://user-images.githubusercontent.com/73999/104140755-4cc57000-53f6-11eb-8011-53b18e6e589a.png)

ただいま着手中です。送信されるメールの内容は上記のようなイメージです。

![image](https://user-images.githubusercontent.com/73999/104140606-95c8f480-53f5-11eb-8007-0a5033a788ff.png)

アクティベーションページを開いた時点で、パスワードは上記のようにシステム側で
自動生成し、同時にログインも完了する流れにしたいと思います。少し工夫すれば
二段階認証のように使うこともできると思います。

生成したパスワードをメールで送ると、本人のスマホやパソコンを見ることができる
人を通じて漏れてしまう可能性があるので、送信しないほうがいいと考えています。
いかがでしょうか？
