### ISSUE TITLE
Windwos環境でのSQLite対応を復活させる

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1427]
## 概要

![image](https://user-images.githubusercontent.com/73999/79988618-d12f3600-84e9-11ea-9eda-94775fc1321e.png)

https://github.com/baserproject/basercms/commit/027255ed779247bc49f88283a3f07275813bf663
上記で経緯など確認させていただきました。Windwos環境でのSQLite対応を
久しぶりに復活できればと思い、処理を追加します。
SQLiteはv3.7.16以降でWindows関連の累積の不具合をいくつか修正したという
ことを公式の情報で確認したので、Windows環境の場合は v3.7.16 より 新しい
SQLiteを使えるかどうかを判定することにしました。
後ほどプルリクをお送りします。

baserCMS version : 4.3.3dev
https://github.com/baserproject/basercms/tree/dev-4

**Comment by ryuring** [comment]
この件、 https://github.com/baserproject/basercms/commit/cd1413d9c7dde7272166666dd25919a4a62f3c93 で解決していますのでクローズします。

@yama プルリク送信する際、メッセージに 「fix #1427」と入れて頂ければマージされた際に、関連チケットが自動クローズしますのでよろしくお願いしますー
