### ISSUE TITLE
【システム】CakePHP 2.10.22 にアップデート / PHP 7.4 に対応

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1428]
## 概要
https://github.com/baserproject/basercms/pull/1004
以前に上記で CakePHP を v2.10.16 にアップデートさせていただきました。

https://github.com/cakephp/cakephp/releases/tag/2.10.20
現在、v2系の最新は2.10.20となっています。もしよければ今回も同様に
アップデートし、PHP7.4対応としたいと考えています。
もしよければ、マージ先のブランチなどご指定いただければ合わせます。
よろしくお願いいたします。

baserCMS version :

**Comment by ryuring** [comment]
@yama 助かります。
@gondoh プルリクはどうしましょうかね。マイナーアップデートとして dev-4.4 ブランチを切りますか？

**Comment by gondoh** [comment]
@ryuring ブランチマイナーバージョン変えましょう！

**Comment by ryuring** [comment]
@gondoh ですね
@yama dev-4.4 ブランチを作成しましたのでこちらにプルリクお願いします！
https://github.com/baserproject/basercms/tree/dev-4.4

**Comment by yama** [comment]
https://github.com/baserproject/basercms/commit/2fa2992d492067b3a7fe4517a671f055cca723df#diff-345f87b8460fdbef42297e7572366450
https://github.com/baserproject/basercms/commit/3e1646e87530de652d84f46ea01015e9ccc2f2be#diff-345f87b8460fdbef42297e7572366450
https://github.com/baserproject/basercms/commit/ea6a618a3192cebf6501f24ab242f42b2170beb7#diff-345f87b8460fdbef42297e7572366450
2013年の上記の改修が、同年内に元に巻き戻っているようです。
数年ぶりとなりますが、これらの改修も反映しましょうか？

**Comment by yama** [comment]
連投すみません。
https://github.com/baserproject/basercms/commit/e9d35c9288c675a2c3a9398a02a53b1bcab3d596
上記コミットですが、CakeRequest.phpはオリジナルパッケージの状態に戻しているようです。
これでよいのでしょうか？

**Comment by ryuring** [comment]
@yama 確認しました。Baserディレクトリに配置したCakeディレクトリ内のクラスと同名のクラスは、Baserディレクトリ内のクラスを優先する仕様となっていますので、変更点をBaserディレクトリ内のクラスに移動しています。

ですので、Cakeのアップデートの際に注意することとして、Cakeディレクトリ自体はまるごと上書きで大丈夫ですが、Baserディレクトリ内にカスタマイズしているクラスが存在しているので、Cake側の変更点をそちらのクラスに目視適用する必要があります。

変更しているクラスのリストは、lib/Baser/HACK.txt に入っています。

**Comment by yama** [comment]
遅くなっててすみません。連休中に対応しますね。

**Comment by yama** [comment]
https://github.com/yama/basercms/commit/aba7924bc7dbc2d0725ead4acc52bc8736293a29
https://github.com/yama/basercms/commit/91f5405259dbef7ce8c51f33f5c0bf68dde578a8

CakePHP側の直接修正が２件残りましたが、これはこのままでよいでしょうか？

**Comment by ryuring** [comment]
@yama CakePHPにプルリク送ってもらうのが一番でしょうが、取り込まれるのに時間がかかったりと大変でしょうから、lib/Baser/ 内に配置して優先させるようにしましょうか。
クラスの新しい参照先を追加するには、 `lib/Baser/Config/bootstrap.php` 27行目あたりで定義を追加する必要があります。 `App::build`

**Comment by yama** [comment]
https://github.com/cakephp/cakephp/releases/tag/2.10.22
数時間前に2.10.22がリリースされました。
もしよければマージしますが、いかがでしょうか？

**Comment by ryuring** [comment]
@yama https://github.com/baserproject/basercms/pull/1476 このプルリクもまだ確認できておらず申し訳ないですが、これにのっけてもらえますか？

**Comment by ryuring** [comment]
@yama 取り急ぎ、僕のレポジトリで、Docker を 7.4 に対応してユニットテストを通しました。
https://github.com/ryuring/basercms/commit/6fd872f5fe64d973ecfc4577727393ef1faaa963

あと、配列操作でWarningがかなり出てるので、実際にすべての画面の動作テストを行いたいと思います。
https://qiita.com/rana_kualu/items/2d71a88aab59b35cdcb8

一旦、cherry-pick とかでそちらの開発環境にマージしておいてもらった方がいいかもです。

**Comment by yama** [comment]
@ryuring 最近滞ってましたが、明日あたりから再開します。参考記事を拝見しましたが、
BaserCMSとしては「7.4に対応した」とは宣言しにくいみたいですね。気をつけて見てみます。

**Comment by ryuring** [comment]
@yama PHP7.4対応について致命的な問題はほとんどないので、CakePHP最新版対応より先にbaserCMS 4.3系で PHP7.4対応版をリリースするかもです。

**Comment by ryuring** [comment]
@yama PHP7.4 は別の開発ブランチ作って対応することにしました。遅くとも今週中には完了させます。そちらはCakePHPの対応に集中してください。
https://github.com/baserproject/basercms/tree/dev-php7.4

**Comment by ryuring** [comment]
@yama PHP7.4 への対応が完了し、dev-4 ブランチにマージしました。そちらの開発ブランチに、dev-4 を一度マージしておいて頂けると助かります。

**Comment by yama** [comment]
すみません、遅くなりました。2.10.21→2.10.22の差分はほんの少しでした。

https://github.com/cakephp/cakephp/pull/14624
コミット前のチェック漏れのためコミットログには記述できませんでしたが、
CakeText::uuid() の改修として上記も含まれています。
random_int()が使える場合はmt_rand()ではなくrandom_int()を使う、という
ことのようです。

**Comment by ryuring** [comment]
@yama ありがとうございます！確認しますね。
