### ISSUE TITLE
Windows版SQLiteの対応バージョンをconfig化する

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1430]
## 概要
https://github.com/baserproject/basercms/issues/1427
上記マージ対応、ありがとうございました。細かい話ですみませんが、利用を許可するSQLiteのバージョンはコード内に直書きせずにconfigにまとめたほうがよいかと思いました。

```
Configure::read('BcRequire.winSQLiteVersion');
```

もしよければ追加でプルリクを作成いたします。

baserCMS version : 4.3.x

**Comment by ryuring** [comment]
@yama 確かにそうですね。まとめお願いします！
