### ISSUE TITLE
ブログのカテゴリを子階層にした際に、カテゴリページで該当カテゴリの投稿が絞り込まれない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1433]
フォーラムからの不都合報告です。
baserCMS 4.3.4-dev で確認しました。
https://forum.basercms.net/t/topic/330

ブログのカテゴリを子階層にした際に、管理画面のカテゴリ一覧ページやブログウィジェットのカテゴリ一覧から遷移した際の、カテゴリページの表示が正しくありません。
親要素のカテゴリの記事も表示されているようです。

**Comment by ryuring** [comment]
@seto1 f2437a1fac063215b8f2f398ae3a1486718515af このコミットが影響しているようですね...

**Comment by ryuring** [comment]
@seto1 なおしときました。コントローラーのテストがいるな...
