### ISSUE TITLE
【コンテンツ】コンテンツ管理メニューからブログを追加しようとすると以下のエラーが発生

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1437]
エラー: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'comment_approve' at row 1
※画像参照

実案件で発生
サーバ: mysql5h (mysql5h via TCP/IP)
サーバのバージョン: 5.7.14-log
 
厳密 SQL モードだと、発生します。

原因：「mysite_blog_contents」テーブルの「comment_approve」カラムがint(2)になっているため、新規追加の際に空文字を突っ込んでしまって、エラーが吐き出される。
（「comment_use」カラムも同様）
対処：phpMyAdiminでint(2)をtinyint(1)に変更することで、正常に動作できるようになります。

**Comment by ryuring** [comment]
Redmine機能要望より転記

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/pull/726 にて解消済みなのでクローズします。
