### ISSUE TITLE
【ブログ】記事一覧でカテゴリ別の年一覧や年月一覧を表示したい

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1439]
Redmine機能要望より転記
http://project.e-catchup.jp/issues/14951

カテゴリ別一覧、年一覧、年月一覧はそれぞれ表示できるが、
カテゴリで絞り込んだ年一覧とかの表示ができると良いかも。

例えば、
カテゴリ一覧のURL /weblog/archives/category/cat1
年月一覧のURL /weblog/archives/date/2016/11
なので、カテゴリ別年月一覧は
/weblog/archives/category/cat1/date/2016/11
とか。

**Comment by kaburk** [comment]
現在は以下のようなURLで対応しているので、こちらのチケットはクローズしたいと思います。
https://trial.basercms.net/news/archives/category/release/year:2021/month:4

**Comment by ryuring** [comment]
@kaburk 確認ありがとうございます！
