### ISSUE TITLE
【システム】生成されるカノニカルURLがスマホ用ページのURLになっている

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1482]
## 概要
![image](https://user-images.githubusercontent.com/73999/82715575-b7dafe80-9cce-11ea-8bf8-a86eed27e404.png)

```
<link href="http://localhost/baser/02/s/service/service1" rel="canonical" media="only screen and (max-width: 640px)"/>
```

パソコン用のブラウザで開いたところ、上記のように、スマホ用のカノニカルURLが生成されます。

```
$agent = BcAgent::find('smartphone');
$subSite = BcSite::findCurrentSub(false, $agent);
if(!$subSite) {
	return;
}
$url = $subSite->makeUrl(new CakeRequest($pureUrl));
$this->_View->set('meta',
	$this->BcHtml->meta('canonical',
		$this->BcHtml->url($url, true),
		[
			'rel' => 'canonical',
			'media' => 'only screen and (max-width: 640px)',
			'type' => null,
			'title' => null,
			'inline' => false
		]
	)
);
```

該当部分の処理を見ると、上記のようになっていました。
このへん、どなたか事情が分かりますでしょうか？ できれば修正します。

baserCMS version : 4.3.4

**Comment by ryuring** [comment]
@yama サブサイトでスマホ用のサイトが存在する場合にカノニカルURLを生成する仕様になっています。
どういう風に修正したいですか？

**Comment by yama** [comment]
@ryuring https://www.seohacks.net/basic/qa/sites_tuning_sp/
PC用ページでは `rel="alternate"`、スマホ用では `rel="canonical"` でどうでしょう？

**Comment by ryuring** [comment]
@yama 確認しました。実装時、alternate は知られていなかったように思います。スマホかどうかというより、重複ページについてのSEO対策として実装されました。

> PC用ページでは rel="alternate"、スマホ用では rel="canonical" でどうでしょう？

こちらでお願いします。

**Comment by yama** [comment]
@ryuring 
https://github.com/baserproject/basercms/pull/1678
上記の改修により当issueも解決と思います。

**Comment by kaburk** [comment]
こちら https://github.com/baserproject/basercms/pull/1678 にてマージ済みのようでしたのでクローズしますね。
