### ISSUE TITLE
固定ページのプレビュー時、変更内容が反映されないケースがある

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1490]
## 概要
※前提事項: 少し特殊なケース
- webrootをドキュメントルート直下配置しているケース
    - http://wiki.basercms.net/%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%83%AB%E3%83%BC%E3%83%88%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6 の「ドキュメントルートに通常どおり静的ファイルを配置する」の状態
- コンテンツの構成がCMS側と静的ファイルが混在しているケース
    - CMS側の配置: コンテンツ内の直下に、フォルダ「directory」を持ち、中にindex固定ページを持つ
    - 実体となるフォルダ構成は以下の図となっている状態

```
.
├── index.php
├── lib
│   ├── Baser
│   └── Cake
├── directory（実体として設置。フォルダ内にindex.html、index.phpは存在しない）
└── theme
```

上記配置状態の際に、
CMS管理側の /directory/index の編集画面から「プレビュー」を実行しても、編集領域の内容が反映されない。
 
## 備考

調べてみてわかった事柄。
・プレビューは、URLに「?preview=default」のパラメータをトリガーとして動作発生するもの
・実ディレクトリが存在する場合、そちらへのアクセス処理が優先される、のは通常動作だが、
　挙げている配置構成の場合、プレビュー動作のために必要なパラメータが、プログラムの動作内ではなくなった状態となっているため動作しない

**Comment by materializing** [comment]
実体ディレクトリが存在する場合は、htaccess 側でプレビュー時にプログラム側優先とするとOKだとわかったためクローズします。

```
RewriteEngine on
RewriteBase /

# プレビューのときはbaserCMSを優先（実フォルダ、ファイルを無視）
RewriteCond %{QUERY_STRING} (^|&)preview=([^&]+)($|&)
RewriteRule ^(.*)$ index.php [QSA,L]

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php [QSA,L]
```

**Comment by ryuring** [comment]
@materializing baserのwiki か、Qiitaに書いておいてくださいー

**Comment by materializing** [comment]
@ryuring 了解ですー！

**Comment by materializing** [comment]
Qiitaに書いちゃいました！
https://qiita.com/materializing/items/6d171f046e06a87ab817
