### ISSUE TITLE
公開側検索のsubmitボタンがtype=imageで作成されている場合、座標情報が送信されエラーとなる

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1511]
## 概要
検索ボタンがinput type="image"で作られていてvalue指定がない場合、送信時に送信データとして座標情報が送信される。
それにより、セキュリティコンポーネントが有効な環境において black-hole に引っかかってしまう。

baserCMS version : 4.3.6

## 備考

メー不フォーム側では座標情報をunlockedFieldsに入れて回避策が取ってある。

**Comment by ryuring** [comment]
@materializing レビュー入れてます。 https://github.com/baserproject/basercms/pull/1512

**Comment by materializing** [comment]
@ryuring はい！ありがとうございます！
内容見直して再挑戦しますのでしばしお待ちくださいー！
