### ISSUE TITLE
【メール】全角カタカナチェックの際にスペースも許可したい

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1514]
## 概要
案件で発生。
フリガナの入力の際に姓・名の間にスペースを入れてもバリデーションが通るようにしたい。

例）タカヤマ タロウ
（現在はエラーになります。）

**Comment by beychanNs** [comment]
別案件でも要望が出ております。
スペースのみを入れた場合には、はじくような対応も併せて必要と思います。
