### ISSUE TITLE
【メール】フィールドタイプ「和暦日付」にて、未入力状態の場合完了画面で内部エラーとなる

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1516]
## 概要
フィールドタイプ「和暦日付」を使用したフォームにて、
フィールドが入力必須でない場合、
未入力にて送信すると内部エラーが発生します。
フィールドタイプ「カレンダー」の場合は未入力だと「1970/01/01」が設定されるので、そちらに合わせるべきでしょうか・・・

**Comment by kaburk** [comment]
こちらはhttps://github.com/baserproject/basercms/pull/1659 にて 解消済みみたいでしたのでクローズしますね。
