### ISSUE TITLE
サブサイト編集画面からサブサイトを削除するとコンテンツツリーチェックでエラーが検出される問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1519]
## 概要
baserCMSをインストール後、サブサイト（スマホ）などの初期に入っているサブサイトをサブサイト編集画面から削除すると、mysite_contentsテーブルのlftとrghtが更新されないため、欠番が出てしまい、コンテンツツリーチェックでエラーが検出される。（ツリーの操作は普通に行える）

**Comment by kaburk** [comment]
サブサイトを削除すると、削除したサブサイトに登録されていた固定ページやブログなどのコンテンツがゴミ箱に入る仕様のようなのですが、その際に mysite_contentsテーブルのlftとrghtが おかしな値になってしまってツリー構造のチェック時にエラーになるようですね。
一旦ゴミ箱をクリアすれば問題なさそうですが、ビミョーな感じですね、、、

**Comment by katokaisya** [comment]
@kaburk 
@ryuring 
https://github.com/baserproject/basercms/issues/1869
https://github.com/baserproject/basercms/pull/1870
こちらと関連はありそうですか？

**Comment by ryuring** [comment]
こちら、解消済なのか、再現できませんでしたのでクローズします。

**Comment by ryuring** [comment]
5系は再現したので修正しました。
https://github.com/baserproject/basercms/commit/ed39a9857bd2ed2c0e5d966fe8642465caa3401b
