### ISSUE TITLE
Cross Site Scripting(XSS) Vulnerability in Latest Release 4.3.6 Content list

### ISSUE THREAD

**Issue by Aquilao** [baserproject/basercms#1520]
I found it in the demo(https://trial.basercms.net/admin/contents/)

Add a alias
![BaserCMS1](https://user-images.githubusercontent.com/25531497/89129156-a499aa00-d52d-11ea-84d6-cb0d79268753.png)

Input payload
`<svg/onload=alert("Aquilao")><-xss test`
![BaserCMS2](https://user-images.githubusercontent.com/25531497/89129167-b54a2000-d52d-11ea-8bc1-2a779c7f22b3.png)

XSS success!
![BaserCMS3](https://user-images.githubusercontent.com/25531497/89129172-c2670f00-d52d-11ea-921f-c642537777df.png)
![BaserCMS4](https://user-images.githubusercontent.com/25531497/89129177-d579df00-d52d-11ea-8319-bdd593fe831b.png)
![BaserCMS5](https://user-images.githubusercontent.com/25531497/89129181-d874cf80-d52d-11ea-9e20-2be8bba22ae2.png)
![BaserCMS6](https://user-images.githubusercontent.com/25531497/89129182-dad72980-d52d-11ea-9905-5bf652a9eceb.png)

**Comment by ryuring** [comment]
@Aquilao 
Thank you for reporting.
This is a delicate issue. I would like to use the security advisory to exchange information. Is that okay?
https://github.com/baserproject/basercms/security/advisories/GHSA-cpxc-67rc-c775

**Comment by ryuring** [comment]
@Aquilao 
This issue will be closed because it has been moved to the security advisory.
