### ISSUE TITLE
Cross Site Scripting(XSS) Vulnerability in Latest Release 4.3.6 Site basic settings

### ISSUE THREAD

**Issue by Aquilao** [baserproject/basercms#1521]
I found it in the demo(https://trial.basercms.net/admin/site_configs/form)

Update Web site name

payload:
`<svg/onload=alert("Aquilao1")><-xss test`
![BaserCMS7](https://user-images.githubusercontent.com/25531497/89129291-c8112480-d52e-11ea-8874-90beab0ef3a6.png)

XSS success!
![BaserCMS8](https://user-images.githubusercontent.com/25531497/89129292-c9425180-d52e-11ea-9b9b-861ad9e9e60e.png)
![BaserCMS9](https://user-images.githubusercontent.com/25531497/89129295-cc3d4200-d52e-11ea-9023-cc1b236e82ca.png)

Affect the entire site
![BaserCMS10](https://user-images.githubusercontent.com/25531497/89129296-ccd5d880-d52e-11ea-97af-3002248c7040.png)

**Comment by ryuring** [comment]
@Aquilao 
Thank you for reporting.
This is a delicate issue. I would like to use the security advisory to exchange information. Is that okay?
https://github.com/baserproject/basercms/security/advisories/GHSA-4r3m-j6x5-48m3

**Comment by ryuring** [comment]
@Aquilao 
This issue will be closed because it has been moved to the security advisory.
