### ISSUE TITLE
Cross Site Scripting(XSS) Vulnerability in Latest Release 4.3.7 New category registration

### ISSUE THREAD

**Issue by Aquilao** [baserproject/basercms#1531]
baserCMS 4.3.7 and earlier is affected by Cross Site Scripting (XSS).

Impact: XSS via Arbitrary script execution.
Attack vector is: Administrator must be logged in.
Tested baserCMS Version : 4.3.7(Latest)

payload:
`"><svg/onload=alert(1)><--xsstest`
 
![image](https://user-images.githubusercontent.com/25531497/91703524-e65d5500-ebac-11ea-9a7c-3a677ae680f5.png)

![image](https://user-images.githubusercontent.com/25531497/91703591-03922380-ebad-11ea-9e0d-5cb245535c71.png)

![image](https://user-images.githubusercontent.com/25531497/91703224-6fc05780-ebac-11ea-9dcb-4b6b81dce214.png)

**Comment by ryuring** [comment]
@Aquilao Hi. Thank you for reporting.

I am sending you an email. Did you see it?

I will close this issue.
I'm writing the reason in the email.
