### ISSUE TITLE
Cross Site Scripting(XSS) Vulnerability in Latest Release 4.3.7 Sub site new registration

### ISSUE THREAD

**Issue by Aquilao** [baserproject/basercms#1532]
baserCMS 4.3.7 and earlier is affected by Cross Site Scripting (XSS).

Impact: XSS via Arbitrary script execution.
Attack vector is: Administrator must be logged in.
Tested baserCMS Version : 4.3.7(Latest)

payload:
`"><svg/onload=alert(1)><--xsstest`

![image](https://user-images.githubusercontent.com/25531497/91705539-afd50980-ebaf-11ea-891d-6821739537d9.png)

![image](https://user-images.githubusercontent.com/25531497/91705476-99c74900-ebaf-11ea-9c62-bcbe62925371.png)

![image](https://user-images.githubusercontent.com/25531497/91705169-32a99480-ebaf-11ea-8c93-8cf8577b23a1.png)

**Comment by ryuring** [comment]
@Aquilao Hi. Thank you for reporting.

I am sending you an email. Did you see it?

I will close this issue.
I'm writing the reason in the email.
