### ISSUE TITLE
Cross Site Scripting(XSS) Vulnerability in Latest Release 4.3.7 Edit widget area

### ISSUE THREAD

**Issue by Aquilao** [baserproject/basercms#1533]
baserCMS 4.3.7 and earlier is affected by Cross Site Scripting (XSS).

Impact: XSS via Arbitrary script execution.
Attack vector is: Administrator must be logged in.
Tested baserCMS Version : 4.3.7(Latest)

payload:
`"><svg/onload=alert(1)><--xsstest`

![image](https://user-images.githubusercontent.com/25531497/91709339-30e2cf80-ebb5-11ea-89d0-172bf649c1c7.png)

Reload

![image](https://user-images.githubusercontent.com/25531497/91715099-a0f65300-ebbf-11ea-9ed2-5de86473ebfd.png)

**Comment by ryuring** [comment]
@Aquilao Hi. Thank you for reporting.

I am sending you an email. Did you see it?

I will close this issue.
I'm writing the reason in the email.
