### ISSUE TITLE
Cross Site Scripting(XSS) Vulnerability in Latest Release 4.3.7 Edit feed settings

### ISSUE THREAD

**Issue by Aquilao** [baserproject/basercms#1534]
baserCMS 4.3.7 and earlier is affected by Cross Site Scripting (XSS).

Impact: XSS via Arbitrary script execution.
Attack vector is: Administrator must be logged in.
Tested baserCMS Version : 4.3.7(Latest)

payload:
`"><svg/onload=alert(1)><--xsstest`

![image](https://user-images.githubusercontent.com/25531497/91716794-e2d4c880-ebc2-11ea-8568-1ec134695c66.png)

![image](https://user-images.githubusercontent.com/25531497/91716483-5de9af00-ebc2-11ea-8517-f0e1679562d3.png)

![image](https://user-images.githubusercontent.com/25531497/91715853-16aeee80-ebc1-11ea-8775-9c5250cc1a7a.png)

**Comment by ryuring** [comment]
@Aquilao Hi.

I am sending you an email. Did you see it?

I will close this issue.
I'm writing the reason in the email.
