### ISSUE TITLE
【コンテンツ】ゴミ箱が空の状態でゴミ箱にアクセスするとロード画像が表示され続ける

### ISSUE THREAD

**Issue by uchin0** [baserproject/basercms#1552]
## 概要
ゴミ箱が空の状態で /contents/trash_index にアクセスするとロード画像が表示され続けて他の操作ができなくなる。

baserCMS version : 4.4.0

**Comment by ryuring** [comment]
@uchin0 報告ありがとうございます。こちら https://github.com/baserproject/basercms/commit/245529de410abe0ecfd8c2378accb4a98fd436db でフィックス済になってます。今月リリースされる次のバージョンで適用されます。
