### ISSUE TITLE
【コンテンツフォルダ】フロントで固定ページ追加できる機能

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1561]
## 概要
フロントにおいてコンテンツフォルダを開いている際に、固定ページを追加するボタンを配置し、ボタンをクリックすると固定ページの新規登録画面に遷移する仕様としたい。

baserCMS version : 4.4.1.1
 
## TODO
- [x] コンテンツフォルダテンプレートに固定ページ新規登録ボタンを配置
- [x] 固定ページ新規登録画面のアクション配置、実装
- [x] 引数でコンテンツフォルダを指定できるようにする

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/issues/1615 と同じく、
管理画面ログイン中のフロント側ツールバーに新規追加ボタンを追加する仕様でいかがでしょうか。

**Comment by ryuring** [comment]
@kaburk 提案ありがとうございます。こちらやりたい事が３つあるんですよね。
- コンテンツフォルダの配下で登録ボタンを配置して任意のページ名の固定ページを追加したい
- Not Foundページで新規追加ボタンを表示したい
- wiki のように [こんなやつ] でリンク追加できてクリックすると固定ページ登録画面に遷移するようにしたい
ようは固定ページがとにかく簡単に追加できるようになればwikiの代わりになるかなと。公式ガイドが使いにくいので baserに変えたく。

少しコードを書きかけてるものもあるのでインターフェイスも含め再考してみます。
