### ISSUE TITLE
【メール】フィールド名が長すぎるとエラーが発生

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#1568]
## 概要

メールフォームのフィールド名が長すぎると管理画面で保存時（またはコピー時）にエラーになるようです。

* 保存時
An Internal Error Has Occurred.
エラー: 内部エラーが発生しました。

* コピー時
処理に失敗しました。(500)
データベースに問題があります。メール受信データ保存用テーブルの更新処理に失敗しました。

モデルのバリデーションではMAX 255文字でチェックしているが、
MySQLのテーブル名、カラム名が上限が64Byte、
PostgreSQLのテーブル名、カラム名が上限が63Byteの為と思われます。

念の為、バリデーションをMAX 255文字 → 50文字ぐらいに変更すると良いかもしれません。

baserCMS version : 

baserCMS 2.0.5.1、baserCMS 4.4.1で確認。
（おそらく2系、3系、4系すべてのバージョンで発生すると思われます）
 
## 備考
※ CSVからMySQLへの移行時にエラーになり気が付きました。

**Comment by gondoh** [comment]
@kaburk 
マルチバイトがUTF8で最大4byte使うので50大丈夫かと思い、確認してみました。

カラム名の上限に引っかかっている状態だと思いますので、その場合半角文字しか許容されていないフィールドかと思います。その場合1文字1byteなので50文字であれば制限は切のいいところで丁度いいかと思います。

maxlength 50で制限かけるのいいと思います。
