### ISSUE TITLE
【システム】アップデート完了後のシステムメッセージの表示色について

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1569]
## 概要

![image](https://user-images.githubusercontent.com/73999/98600865-91169000-2321-11eb-9657-b2ef52d79a7a.png)

赤い枠線だと何か問題があったように見えるので、緑の枠線がよさそうに思います。

baserCMS version : 4.4.x

**Comment by kaburk** [comment]
クラス名はinfoであたっているみたいなので、標準テーマのCSS調整でなおせそうですね。
（bc_sampleのCSS見るとフロント側のflashメッセージが全て同じカラーになっているようでした…。）

<img width="1673" alt="スクリーンショット 2021-06-09 14 44 50" src="https://user-images.githubusercontent.com/310333/121300258-8fea2780-c931-11eb-8a4c-d07c3562598a.png">

<img width="1671" alt="スクリーンショット 2021-06-09 14 45 37" src="https://user-images.githubusercontent.com/310333/121300250-8bbe0a00-c931-11eb-953e-81403312eec2.png">
