### ISSUE TITLE
【アップデート】CMSアップデート完了時メッセージを表示する

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1586]
## 概要
現在はトップページに遷移しメッセージを出していないため

baserCMS version : 4.4.2

**Comment by kaburk** [comment]
baserCMS4.4.8にて確認したところ、下記のようにメッセージが表示されているようでした。
https://github.com/baserproject/basercms/commit/19564a9 の改修でメッセージも調整済みのようでしたので一旦クローズしたいと思います。

<img width="1362" alt="スクリーンショット 2021-07-15 20 32 32" src="https://user-images.githubusercontent.com/310333/125781339-01aa031c-9df8-497c-8014-d4cc7414cd4e.png">

**Comment by ryuring** [comment]
@kaburk 確認ありがとうございます〜
