### ISSUE TITLE
ブログ記事noが重複して保存されるケースがある

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1596]
## 概要
・ブログ記事URLに利用されるno値が重複することがある
　→ 2ユーザー同時保存で、重複が再現されることを確認
なので、noの割り振り処理に重複が発生しないようにして解消したい、です。

## これまで調査・確認してきたこと

- [重複してNG] ブログ記事NOの生成箇所と記事保存箇所をBlogPostsController->admin_addの中で近づける
- [重複してNG] ブログ記事NOの生成箇所をBlogPost->beforeSaveに移動
- [重複してNG] ブログ記事NOの生成箇所をBlogModelEventListener->blogBlogPostBeforeSaveに移動
- [重複してNG] ブログ記事NOの生成箇所と記事保存箇所をトランザクションの中に入れる
- [重複してNG] DBのテーブル単位でロックをかける
    - ```LOCK TABLES mysite_blog_posts write, mysite_blog_posts AS BlogPost write;```
- [重複は防げるが片方がエラーになる] blog_content_id と no をセットにしたmysqlのユニーク制約をかける
    - ```ALTER TABLE mysite_blog_posts ADD UNIQUE blog_content_id_no (blog_content_id, no);```

## 検討事項の案

- トランザクションのタイミングをもっと考える
- ロックのかけ方が間違っている可能性があるので教えてほしい
- トランザクションをかけつつ、データの保存とNOの生成を同時に行う
    - ```INSERT INTO mysite_blog_posts (no) (SELECT MAX(no) + 1 FROM mysite_blog_posts)```
    - 但し、上記の場合クエリを書く必要があるので、save関数が使えなくなる
- 重複を防ぐ確実な方法はmysqlでユニーク制約をかけること、だと考えてはいるところ

## アイデアで出たもの
最終noの値を持った行だけをロックすること。試してみたのは以下の内容。

```
$dataSource = $this->BlogPost->getDataSource();
$dataSource->begin();
$dataSource->query('SELECT * FROM mysite_blog_contents WHERE id = 1 FOR UPDATE');
$dataSource->commit();
```

NOは重複しなくなりましたが、使ったことがなく深く理解ある状態ではないので、
例えば InnoDB以外では動かない、とかの副作用が考えられる内容です。
また、他のDBどうすると良いんだろう？とかいろいろあるとは思うので、
まずはMySQL＋InnoDBの組み合わせ時の対応に絞って考える、でも良いと思うのでなんとかしたいのであります。
すみませんが、何卒baserCMS プロジェクト開発メンバーみなさんのご協力を得たいです！

baserCMS version : 4.4.2以下

**Comment by ryuring** [comment]
トランザクションでは、save() は普通に使えます。
また、MySQLは、最近は、MyISAMはなく、InnoDBのみです。
あと、ロールバックの処理も入れましょう。
@materializing

**Comment by materializing** [comment]
@ryuring ありがとうございます！！トライしてきます

**Comment by ryuring** [comment]
@materializing これ、先日権藤さんと話してたんですが、トランザクションだけでは、参照と更新の両方をロックすることはできないかもしれません。
LOCK TABLESを利用するか、複合キーを利用する必要があるかも。トランザクションだけでできれば一番いいのですが。

**Comment by gondoh** [comment]
トランザクションだけでは難しいって @materializing と @seto1 から聞いた話なんです。
上記のコードでcommitの間にアップデートすることでNOをロックしてるってことですよね。
