### ISSUE TITLE
メールフォームバリデーションメッセージに任意の言語を設定したい

### ISSUE THREAD

**Issue by t-uchiba** [baserproject/basercms#1598]
## 概要
メールフォームのバリデーションメッセージ出力の際に、ブラウザの言語設定に関わらず管理画面からどの言語を使用するかの選択機能が欲しいです。

baserCMS version : 4.x

**Comment by ryuring** [comment]
@t-uchiba 登録ありがとうございます。こちら少し急ぎますね。

**Comment by ryuring** [comment]
@t-uchiba /app/Config/setting.php で設定を変更できるようにしました。
https://github.com/baserproject/basercms/commit/99e5783a33400ecf71fb04a50dfdfcde1610d565

**Comment by t-uchiba** [comment]
@ryuring ありがとうございます・・・！
