### ISSUE TITLE
【admin-third】特に非公開中のブログやフォーム等のコンテンツについて、設定画面への導線が不便に感じる

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1611]
## 概要

旧管理画面の場合、設定画面には記事一覧等からの導線もあったので使いやすかったです。
admin-thirdでは設定画面への導線は、
①サイドバーで該当コンテンツにマウスホバーしたとき・該当コンテンツを開いたとき
②コンテンツ一覧で該当コンテンツを右クリックして「編集」を選択したとき
に表示されますが、コンテンツが非公開の場合は導線が②のみになり、割と慣れていても不便に感じます。
（コンテンツ一覧で右クリックした時の「管理」「編集」がしばしばこんがらがってしまうのもあります）

コンテンツの設定画面を開いている時に、
例えばブログであれば記事一覧、フォームであればフィールド一覧や受信メール一覧にアクセスできる、
また、ブログ記事一覧やフォームフィールド一覧や受信メール一覧を開いている時に設定画面にアクセスできる、
双方向にアクセスしやすい導線が画面上部にまとまっているとすごく扱いやすいと思います。

（考えがあって今のデザインになっているのであればご教授いただけると幸いです）

baserCMS version : 4.4.2

**Comment by ryuring** [comment]
@cu-morishita 全部出す方向にしましょう
