### ISSUE TITLE
各メニューの「制限」からアクセス制限登録をすると、_blackHoleCallback()が発生して不正なリクエストエラーになる

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1612]
## 概要
各メニュー右上の「制限」からアクセス制限登録をしようとしても、エラーが頻発します。（条件については確認中）
エラーログを確認すると、
/admin/permissions/ajax_add にて_blackHoleCallback('secure')が発生しているようです

baserCMS version : 4.4.2（結構幅広いバージョンにて発生しているようです）

**Comment by cu-morishita** [comment]
![Uploading スクリーンショット 2021-01-05 15.36.47.png…]()

**Comment by cu-morishita** [comment]
![スクリーンショット 2021-01-05 15 36 47](https://user-images.githubusercontent.com/60252780/103615615-38a0ef00-4f6e-11eb-99d1-3cabd3382fd8.png)

**Comment by kaburk** [comment]
admin-third については https://github.com/baserproject/basercms/commit/78145dc91e4ec09f15fd7b37c89a74e3561c7b2a にて解消済みの内容でしたが、admin-secondでは発生してますね、、、

@ryuring  これってどうしましょうか。

**Comment by ryuring** [comment]
@kaburk admin-second のメンテナンスをいつまでやるか対応方針を決めないといけないですね。
取り急ぎ、解消コミット送っておきました。
