### ISSUE TITLE
【システム】「最近の動き」専用の画面を作成

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1624]
## 概要

![image](https://user-images.githubusercontent.com/73999/104160948-51f5df80-5435-11eb-807b-5f47aeacb2e2.png)

ダッシュボードでしか閲覧できない「最近の動き」の専用画面を作成。
内容や担当者ごとに絞り込んだり並べ替えたりできるようにすると便利と思います。

baserCMS version : v4.4.x

**Comment by ryuring** [comment]
@yama 僕はいいと思います。
@gondoh @kaburk  いかがでしょう？

**Comment by yama** [comment]
@ryuring @goichi-m 

これを実装することで、ダッシュボードではページングを実装せずに
「すべてのログを見る」へのリンクを末尾に張るだけでよくなります。
そうするとダッシュボードの軽量化もしやすくなります。
今のダッシュボード、重いですよね、、

**Comment by yama** [comment]
@ryuring @gondoh @kaburk 
こちら、どうでしょう？
これを実装できると次はダッシュボードの表示速度改善がしやすくなります。

**Comment by kaburk** [comment]
いいとおもいます！

**Comment by gondoh** [comment]
いいと思います！

**Comment by ryuring** [comment]
@kaburk @gondoh ありがとうございます。
@yama では実装の方向ですすめましょう。
