### ISSUE TITLE
年月日archivesの数値判定の問題

### ISSUE THREAD

**Issue by mutosea** [baserproject/basercms#1632]
## 概要
/date/以降に自由な文字列を入力してアクセス可能な問題

/index.php/{blog}/archives/date/hoge/hoge/hoge

baserCMS version : 4系全般で発生確認

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/commit/380fef170c5ca83aa505d17e9a061e9825a38b40 の改修で修正済みのようでしたのでクローズしたいと思います。
