### ISSUE TITLE
【システム】rand()をmt_rand()に変更

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1647]
## 概要
rand()の使用箇所をmt_rand()に変更します。
rand()はPHP7.1以降はmt_rand()のエイリアスとなるので、実質的には
コード整形レベルの軽微な修正扱いになります。

baserCMS version : 4.4.x-

**Comment by yama** [comment]
エンジニアがbaserCMSのコードを見た時の印象を少しでも改善できれば
協力者も増えるかなー、という気がします。

**Comment by ryuring** [comment]
@yama よろしくお願いします。
