### ISSUE TITLE
メールフォーム設定の「送信先名」のデフォルト値にサイト名を設定したい

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1648]
## 概要
現状、デフォルト値が「送信先名を入力してください」となっており、設定し忘れを起こしがちです。
サイト名を設定することが多いので、デフォルトに設定したいです。

**Comment by ryuring** [comment]
デフォルト値のサイト名は、baserCMS inc とかになりますかね？

**Comment by yutorishine** [comment]
@ryuring 
インストールした直後はそんな感じになっちゃいますね。
ただ、開発の早い段階でサイト名はちゃんとしたものを登録しているという前提で、（というか、インストール時に設定できるようになったほうがいいかもしれませんね）

- メールフォーム作成時に「送信先名」は空の状態とし、「送信先名を入力してください」はプレースホルダーにする
- フォーム送信時に条件分岐
    - 空白の場合、サイト名を送信先名とする
    - 入力されている場合、そちらを送信先名とする

の、ようにすると、設定忘れによる「送信先名を入力してください」問題は解消するのではないかと思います。
