### ISSUE TITLE
MaildataHelper::control() の返り値におけるスペースの意図は？

### ISSUE THREAD

**Issue by tecking** [baserproject/basercms#1653]
## 概要

メールフォームプラグインの MaildataHelper::control() で

```
public function control($type, $value, $escape = true)
{
	$toDisplayString = $this->toDisplayString($type, $value);
	return $escape? ' ' . h($toDisplayString) : ' ' . $toDisplayString;
}
```

と、返り値にスペースが入っている理由って何でしょう？
クライアントから「行頭に半角スペースが入っているのが気になる」と言われまして…

何か意図があればご教示くださいませ。

**Comment by ryuring** [comment]
@tecking 箇条書きのインデント的なものだったと思います

**Comment by tecking** [comment]
``<input type="text">`` で入力するような1行テキストだとそんなに気にならないですけど（むしろあったほうがいい）、``<textarea>`` で入力する複数行テキストだと1行目だけインデントかかっちゃって

> クライアントから「行頭に半角スペースが入っているのが気になる」

みたいな話になっちゃいそうですね…

MaildataHelper::toDisplayString() の ``switch ($type)`` で textarea の処理切り離した方がよいんですかねー？

**Comment by ryuring** [comment]
@tecking おっしゃるとおりだったので調整しておきました〜
https://github.com/baserproject/basercms/commit/3999929bf13f554c7f25aeaf0876dfcfbbacadb8
