### ISSUE TITLE
【システム】セッションをDBに保存する場合のファイル関係の不都合

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1661]
## 概要

セッションをDBに保存する設定にしている場合に以下の不都合があります。

- フォームでファイルを選択した場合に送信に失敗する
- ブログ記事追加時にアイキャッチを設定した状態でプレビューを行うと管理画面からログアウトする

baserCMS version : baserCMS 4.4.5-dev
 
## 備考

BcUploadBehavior->saveTmpFiles を使用している箇所で問題が起きます。
バイナリデータをDBに保存しようとして失敗している可能性があります。
database.php の encoding が utf8 だと発生せず、 utf8mb4 だと発生することを確認しました。

**Comment by kaburk** [comment]
ソースを確認したら、確かに一時ファイル（バイナリ）をセッションに保存していました。

セッションをDBに保存する設定の場合、dataカラムをcakeで用意しているSQLではtext型になっているので、
バイナリ型 （MySQLだと longblob型とかかな）にすれば保存できるようになります。
これだと特に改修なしで対応できますが、何処かにノウハウとして書いておかないとわからなくなりそうですが…。
app/Config/Schema/sessions.sql ファイルにコメント追記とかかな？

それか、コアを修正してセッションに保存時にbase64エンコードして保存、読み出し時にデコードするようにすれば解決できそうですね。
