### ISSUE TITLE
【フォーム】サブサイト利用の英語言語設定において、メールフィールドの「都道府県リスト」が日本語のままになる

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1665]
## 概要
forumより指摘
サブサイト利用の英語言語設定において、メールフィールドの「都道府県リスト」が日本語のままになる
https://forum.basercms.net/t/topic/623/4
コードのリファクタリングが影響しているのでしょうか？

baserCMS version : 4.4.3以降

**Comment by kaburk** [comment]
調べてみたところ、フロント側で言語リソースの baser.poが読み込めてないみたいですね。
BcTextヘルパーの他のメソッドもフロント側で多言語化できてない感じでした。

NG： baser.po
 __d('baser', 'ほげほげ');

OK： defarult.po
 __d('default', 'ほげほげ');
 __('ほげほげ'); 

ちょっと根が深いかも…。

**Comment by kaburk** [comment]
baser.po 管理側で使う言語設定
default.po フロント側で使う言語設定

という感じの区分けみたいなので、baser.poを無理やり読み込むより
baser.poにある都道府県の一覧の設定をdefault.po に移すのが良さそうな感じですね、、、。

**Comment by yama** [comment]
https://github.com/baserproject/basercms/commit/99e5783a33400ecf71fb04a50dfdfcde1610d565
このへん関係ないでしょうか？
