### ISSUE TITLE
【ブログ】「新しいカテゴリを追加」ボタン押下時に、他項目にジャンプする

### ISSUE THREAD

**Issue by nmaru53** [baserproject/basercms#1668]
## 概要
「新規記事追加」ボタン押下後の新規記事登録画面にて、
「新しいカテゴリを追加」ボタンを押下すると、
「公開状態」までジャンプする。
登録作業を続けるためには、上までスクロールする手間が発生する。

baserCMS version : 4.4.5-dev

**Comment by ryuring** [comment]
@nmaru53 確認してみたのですが再現できませんでした。
新しいカテゴリを追加を押すとそのままポップアップが表示され、ポップアップの保存を押すとそのまま画面が閉じます。

![スクリーンショット 2021-03-29 11 18 37](https://user-images.githubusercontent.com/90106/112779014-c4637c80-9080-11eb-89a9-59712c6d725c.png)

**Comment by nmaru53** [comment]
Macで画面を収録してみました。

https://user-images.githubusercontent.com/20200177/112833021-16cc8980-90d1-11eb-87fc-33e5f54db000.mov

**Comment by ryuring** [comment]
@nmaru53 ありがとうございます。Chrome では再現できませんでしたが、Safariで再現できましたので直しておきました。
https://github.com/baserproject/basercms/commit/072b51f4afc02633c748f68c33a02c6ba13107d0

**Comment by nmaru53** [comment]
@ryuring 
承知しました、対応とご連絡ありがとうございます。
