### ISSUE TITLE
【ブログ】ゴミ箱に入れたブログコンテンツの記事が、サイト内検索の検索結果に表示されてしまう

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1669]
## 概要
Issueの概要を What・Why も含めて書きます。

baserCMS version : 4.4.4
 
コンテンツ一覧よりコンテンツごと削除したブログの記事が、サイト内検索にて表示されてしまいます。
一覧よりアクセスすると404エラーになります。

**Comment by materializing** [comment]
ブログコンテンツをゴミ箱に入れたタイミングで、検索データに入ってるブログ記事とブログコンテンツを削除し、
ゴミ箱から復帰した場合は、該当ブログコンテンツとその記事を再度検索データに入れる、という動作が良さそうですかねー。

**Comment by kaburk** [comment]
ブログコンテンツ は すぐ治せそうですが、ブログ記事が多い時どうるかが問題ですね。
やはり１記事づつチェックするしか無いのかなぁ。。

検索データ作成処理をバックグラウンド処理とかにできれば
いろいろなパフォーマンス改善できそうなんですけどね、、、

**Comment by materializing** [comment]
@kaburk ですよね。ちょっと考えてたんですが、処理としては一気にsaveAllでstatusを変えるとして、
1件ずつ回してってのは、ブログコンテンツをゴミ箱から戻すときにする、くらいでしょうかね。
ただそれでもそのタイミングで問題出やすくなっちゃいますよね。。うーん
