### ISSUE TITLE
ウィジェットエリア編集でドラッグ&ドロップできない

### ISSUE THREAD

**Issue by humuhimi** [baserproject/basercms#1671]
## 概要
Issueの概要を What・Why も含めて書きます。
[ページの下の方にあるウィジェットがドラッグ&ドロップできない]
https://e-catchup.backlog.com/view/BC_OFFICIAL-51

**Comment by kaburk** [comment]
リンク先が見れなかったのでおそらくウィジェットの数が多いときのはないだと思いますが、
タイトル部分をクリックで開閉できるようにすると少しは下のほうにアクセスしやすくなるのではないでしょうか？

![Screenshot_2021-05-12-1](https://user-images.githubusercontent.com/310333/117921036-f710be00-b32a-11eb-96b2-ee0d277d9457.png)
![Screenshot_2021-05-12-2](https://user-images.githubusercontent.com/310333/117921043-fa0bae80-b32a-11eb-8dda-fc8537aeddb0.png)

**Comment by ryuring** [comment]
@kaburk そのアイデアめっちゃいいですね！
