### ISSUE TITLE
【システム】パッケージサイズを削減

### ISSUE THREAD

**Issue by yama** [baserproject/basercms#1674]
## 概要

themeに含まれる画像を最適化するなどして、パッケージサイズを削減します。

baserCMS version :  v4.4.x最新版

**Comment by yama** [comment]
@ryuring 

/lib/Baser/webroot/js/
/app/webroot/theme/admin-third/js/
上記フォルダの内容がほぼ重複していて、前者を削除できればと考えています。
特にCKEditorが容量を占めています。

でもこれって、雛形として必要ということだったでしょうか？

**Comment by ryuring** [comment]
@yama 古い管理画面テーマ admin-second として後方互換が必要なため、まだ削除はできないです

**Comment by yama** [comment]
@ryuring 

了解です。ちなみに両者を見比べるとわずかに違いがあるのですが、
admin-secondとadmin-thirdの違いということでしょうか？

**Comment by ryuring** [comment]
@yama そうです

**Comment by yama** [comment]
@ryuring 

https://github.com/baserproject/basercms/pull/1675
あ、いったん上記で対応済みです。10MBくらい減りましたよ。
まだ整理の余地がありますが、別課題立てて対応しますね。

**Comment by ryuring** [comment]
ではこちらは一旦クローズしますね。
