### ISSUE TITLE
【フォーム】フィールド設定にて、「表示サイズ」に数値以外を入力するとシステムエラーになる

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#1692]
## 概要
width="100%" を設定しようと、「表示サイズ」に「100%」と入力した際に発覚（「表示サイズ」はcols属性を設定する項目のため数値以外は入力しない想定）

baserCMS version : 4.4.5
 
## TODO
-「表示サイズ=width」という勘違いは今後も発生しうる気がします。名称を変更したほうがいいかもしれません。ヘルプテキストもいいかもしれません。
-「表示サイズ」に数値以外を入れた際のバリデーションが必要かと思います

**Comment by kaburk** [comment]
こちら確認してみましたが、再現しないようでした。
cols属性を設定との記載があるので、テキストエリアの表示サイズのことかと思いますが、100% を入力して保存したら、100で保存されるようでした。

ただ、バリデーションは必要かと思われます。

<img width="1135" alt="スクリーンショット 2021-05-12 13 51 14" src="https://user-images.githubusercontent.com/310333/117920095-3b9b5a00-b329-11eb-850e-0d136fa17524.png">
<img width="1003" alt="スクリーンショット 2021-05-12 13 51 27" src="https://user-images.githubusercontent.com/310333/117920101-3f2ee100-b329-11eb-8ddc-6228bad7d18d.png">
<img width="1027" alt="スクリーンショット 2021-05-12 13 51 39" src="https://user-images.githubusercontent.com/310333/117920107-40f8a480-b329-11eb-95d6-7a8d3cd216a0.png">

**Comment by kaburk** [comment]
あ、MySQLとかでSQLモードをstrictモードで設定とかしてるとシステムエラーになりますね…。
