### ISSUE TITLE
【フォーム】Eメールチェックの機能追加

### ISSUE THREAD

**Issue by morishita1222** [baserproject/basercms#1700]
## 概要
Eメールチェックについて、全角文字を半角に変換
1. 認められない文字を明確に指摘する。例: 「*はEメールに利用できません。取り除いてください。」
2. @がない場合指摘する。例:「@が必要です。」

全角カタカナチェックについて、
1. 全角ひらがなは全角カタカナに変換
2. 半角カタカナは全角カタカナに変換
3. 認められない文字を明確に指摘する。例: 「ひらがなでない『漢字ABC』は〇〇に利用できません。ひらがなに変更してください。」
4. 変換できるのであれば自動で変換（確認ページで）

全角ひらがなチェックについて、
1. 全角ひらがなは全角ひらがなに変換
2. 半角カタカナは全角ひらがなに変換
3. 認められない文字を明確に指摘する。例: 「カタカナでない『漢字ABC』は〇〇に利用できません。ひらがなに変更してください。」
4. 変換できるのであれば自動で変換（確認ページで）

**Comment by kaburk** [comment]
https://github.com/baserproject/basercms/pull/1701 にてマージされてましたので、クローズします。
