### ISSUE TITLE
ヘルプのバルーンチップがサイドメニューに隠れて見れない

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#1704]
## 概要
管理画面で、ヘルプのアイコンが左側にある場合、ヘルプのバルーンチップがサイドメニューに隠れて見えなくなる。
表示順をサイドメニューよりもあとにする必要がある。

<img width="563" alt="スクリーンショット 2021-05-17 15 43 20" src="https://user-images.githubusercontent.com/84309553/118446777-fb721800-b72a-11eb-94c8-5b4a91e2ea49.png">

<img width="563" alt="スクリーンショット 2021-05-17 15 43 31" src="https://user-images.githubusercontent.com/84309553/118446819-0462e980-b72b-11eb-99bd-866958a71f66.png">

<img width="563" alt="スクリーンショット 2021-05-17 15 43 37" src="https://user-images.githubusercontent.com/84309553/118446838-07f67080-b72b-11eb-86c8-5ecc43e79289.png">

baserCMS version : 4.4.2

**Comment by kaburk** [comment]
すぐなおせそうな感じだったので見てみたのですが、うまくいかない、、、
