### ISSUE TITLE
インストールできない

### ISSUE THREAD

**Issue by yokoyamy** [baserproject/basercms#1722]
## 概要

「baserCMSのインストール」画面から「インストール開始」ボタンを押します。

「Not Found
The requested URL was not found on this server.」とメッセージが出ます。

アドレスバーに見えているURLは、
http://localhost/basercms/installations/step2　です。

baserCMS version : 4.4.8
PHP7.42
Apache2.4.41
Windows10　

## TODO
ダウンロードしZIP解凍したファイルをドキュメントルートに配置

## 備考

Windows10

**Comment by kaburk** [comment]
いくつかのWindows環境で試してみましたが、インストーラー自体には特に問題なさそうですね。
エラーメッセージからも、おそらくapacheの設定間違いなどではないかと思われます。

例えばXAMPP 7.x (8.x系はPHP8になるのでNGです) などですと、インストール後、特に設定変更なしで、C:¥xampp¥htdocsにbasercmsフォルダを設置しただけで、特に問題なくインストーラも動作しておりましたので試してみてください。

**Comment by yama** [comment]
@yokoyamy @kaburk 
Apacheのconfでmod_rewrite.soが有効になってないとこの状態になるような気がします。
(phpinfoを見ると分かります)

**Comment by yokoyamy** [comment]
@yama @kaburk 
回答ありがとうございます。

rewriteは有効です。
LoadModule rewrite_module modules/mod_rewrite.so

**Comment by yama** [comment]
@yokoyamy 
```
RewriteEngine on
#RewriteBase /
RewriteRule ^$ app/webroot/ [L]
RewriteRule (.*) app/webroot/$1 [L]
```

.htaccessの内容は上記のようになってますでしょうか？
「Not Found The requested URL was not found on this server」というエラーメッセージは
PHPではなくApache側が出力するものなので、サーバ側の設定に何か原因があるように思います。

**Comment by yokoyamy** [comment]
@yama 

.htaccessはダウンロードした解凍した状態のままで、以下のとおりです。
```
Allow from all
RewriteEngine on
#RewriteBase /
RewriteRule \.(ico|map)$ - [L]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php [QSA,L]
```

yama様の記述に変更してみましたが、結果変わらずでした。

**Comment by gondoh** [comment]
RewriteBaseにサブフォルダを指定しないとアクセスできない感じがします。
下記が参考になるかもしれません。
https://wiki.basercms.net/%E3%82%B5%E3%83%96%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%81%AB%E8%A8%AD%E7%BD%AE%E3%81%97%E3%81%9F%E3%81%84


下記かな？
```
Allow from all
RewriteEngine on
RewriteBase /basercms
RewriteRule \.(ico|map)$ - [L]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php [QSA,L]
```

**Comment by yokoyamy** [comment]
@gondoh 
ご助言ありがとうございます。
いただいた設定で変更しましたが、結果変わらずでした。

**Comment by yama** [comment]
@yokoyamy 
この件、現在も未解決でしょうか？
解決していない場合は、mod_rewriteの設定についてphpinfo()で確認することはできますか？
設定は合っているようですが、何らかの原因で動作していない可能性はあると思います。

**Comment by yama** [comment]
@yokoyamy 
https://forum.basercms.net/
いったん続きはフォーラムのほうで仕切り直していただいてよいでしょうか？
ここはbaserCMSの開発に関して利用しますが、今回はbaserCMSの問題では
なさそうなので、広い視点でいろいろ情報を集めたほうがよさそうです。

**Comment by yokoyamy** [comment]
ありがとうございました。お世話になりました。
