### ISSUE TITLE
$this->BcBaser->blogPosts() を管理画面で利用した場合に Noticeエラーとなってしまう

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1729]
## 概要
フォーラムより報告あり
https://forum.basercms.net/t/topic/728

baserCMS version : 4.4.9

**Comment by ryuring** [comment]
こちらのコミットで改善
https://github.com/baserproject/basercms/commit/a2444dca76b65fa5981957f2d1836901fc72f762

**Comment by kaburk** [comment]
dev-4にマージされているようでしたので、クローズします！

**Comment by ryuring** [comment]
@kaburk 確認ありがとうございます！
