### ISSUE TITLE
【フォーム】「入力チェック」に「Eメールチェック（任意入力）」を追加して欲しい

### ISSUE THREAD

**Issue by catchup-doi** [baserproject/basercms#1732]
## 概要
Issueの概要を What・Why も含めて書きます。

不具合の起きた状況：
「入力チェック」に「Eメールチェック（入力必須）」はあるが、「Eメールチェック（任意入力）」はない。

そのため、フォームのメールアドレスを任意入力にしている場合、Eメールとしては不正な文字列も受け付けてしまう。
その状態で、メールアドレスへフォームを送信すると「 500 An Internal Error Has Occurred. 」となってしまう。

現時点での回避策：
なし

現状で思い当たる対策：
「入力チェック」に「Eメールチェック（任意入力）」を追加してもらえれば、この問題を回避できると思います。

baserCMS version : 最新版
 
## TODO
- [ ]
  - [ ]
 
 
## 備考

別途記載する内容があれば書きます。

**Comment by gondoh** [comment]
現時点での回避策:
テキストフィールドにして、正規表現チェックを入れると一応可能ですね。

**Comment by catchup-doi** [comment]
大変良い対応策を示していただき、ありがとうございます。

この対応策で、問題が解決するので、この件についてはこれにてクローズいたします。
