### ISSUE TITLE
 【その他】baserCMS公式サイトの配布ファイルに不要なファイルが存在する

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#1735]
以下のファイルは配布ファイルに含めないほうがよいかと思いますのでご確認をお願いします。

- .github
- vagrant
- .editorconfig
- INSTALL.md
- LICENSE

**Comment by yama** [comment]
@seto1 
LICENSEは残しておくのがいいかも？（重要な情報だと思うので）

apple-touch-icon-precomposed.pngとfavicon.icoも削除できるのではと思います。
webrootにあるものがロードされるので、アーカイブのルートにはなくてもいいかなと。

**Comment by seto1** [comment]
lib/Baser や lib/Caka 配下にも存在するので不要かなと思ったのですが、ライセンス周りはちょっと分からないですね..

なぜこのissueをたてたかというと、baser公式からダウンロードしたファイルを丸ごとサーバーにアップする人がほとんどだと思うので、意図しないファイルが公開されてしまうのが気になるんですよね。

例: https://basercms.net/LICENSE.txt

**Comment by yama** [comment]
@seto1 

> 意図しないファイルが公開されてしまう

ですね、その点は同感です。

ライセンスに関してはGPLとMITは別格で、baserCMSがMITであることを
明確に示す必要があると思います。WordPressやJoomlaなどのメジャーな
CMSも参考になるかな？と思います。

Drupalみたいにreadmeに「ライセンスに関してはこちら」みたいなポインタを
置く方式もよいかも？自分だったら、.htaccessか、Drupalみたいにreadmeに書いて、
瀬戸さんの提案どおり、ルートにはLICENSE.txtも置かずすっきりまとめるのが
結果的には分かりやすく伝わってよい気もします。

> lib/Baser や lib/Caka 配下にも存在するので不要かなと

それは削除してもいいかも。それか、それらのファイルへのポインタを書くか。
つまりreadmeに「ライセンスに関してはlib/Baser/license.txtを参照してください」と
いう形です。

**Comment by yama** [comment]
baserCMSの場合は、readme.mdは存在しないのでinstall.mdですね。

**Comment by seto1** [comment]
> 結局、何かひとつは説明的なテキストファイルをルートに置いておくのが
よいかなと思います。

そのほうが親切ですね。
説明的なファイルは残した上で、.htaccessで制限をかけるのがよさそうです。

**Comment by seto1** [comment]
5系だとwebroot配下が公開されるようになるのでクローズします。
