### ISSUE TITLE
メールメッセージのアップデート中に処理が中断される問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1746]
## 概要
案件にて発生
baserCMS4.0.10以前のバージョンと以降のバージョンで、mail_messageテーブルのラジオボタンなどの保存方法が異なるため、DBのアップデートが発生するが、
メールフォームが複数あるときに、1つ目のメッセージテーブルの情報をキャッシュしてしまい、2つ目以降のメッセージテーブルがアップデートされなくなる

baserCMS version : 4.0.10　以前のバージョン→4.0.10以降のバージョンアップデート時

**Comment by kaburk** [comment]
複数のメールフォームがある場合に、MailMessageモデルが初期化されていない問題があったので修正しました。
よろしくお願いいたします。
