### ISSUE TITLE
マルチチェックボックスを選んだ状態で「入力チェック」に「入力必須」を選んだ場合、 拡張入力チェックの「チェックボックス未入力チェック」の利用を促す

### ISSUE THREAD

**Issue by materializing** [baserproject/basercms#1747]
## 概要
メールフォームのフィールド設定で、マルチチェックボックスを必須化するには、 入力必須の選択設定ではなく、
拡張入力チェックの「チェックボックス未入力チェック」の設定が必要なことをユーザに伝える必要があること。

baserCMS version : 4.5.1
 
## TODO
- ヘルプ文章の中に案内文を入れる
- マルチチェックボックスを選んでいる状態で、入力チェックを入力必須に選択した際に案内文章を表示する

![スクリーンショット 2021-09-04 20 40 56](https://user-images.githubusercontent.com/1115768/132093220-95357aa1-08ef-4632-9d3d-43f563b8dd25.png)

**Comment by kaburk** [comment]
説明追加は良さそうですが、そもそもマルチチェックボックスの入力必須チェックの仕様自体がわかりにくく使い勝手が良くないと思います。
（開発者じゃない人が設定するときに、なぜマルチチェックボックスだけ入力必須の設定項目が違うのかも謎ですし）

下位互換の為、これまで同様の設定でもOKにしておいて、
入力必須＝チェックボックス未入力チェック、という扱いに改修したほうがわかりにくさを解消できる気がします。

**Comment by materializing** [comment]
@kaburk ありがとございます。お話もっともで理解できました。ところが既にコミットまでしていただいてるという神ですね
