### ISSUE TITLE
mysql8.0環境でのインストールが失敗する。

### ISSUE THREAD

**Issue by Diwamoto** [baserproject/basercms#1758]
## 概要

mysql8.0.26環境でのインストールが失敗します。

インストールの途中でSQLのレコードのタイムスタンプ（おそらくcreated）として`"0000-00-00 00:00:00"`を保存する際に、mysql8.0のデフォルトの`sql_mode`の設定の`NO_ZERO_DATE`によって弾かれてしまい、インストールステップ4→5のタイミングで500エラー画面に遷移してしまいます。

改善方法として、使用するサーバーの`sql_mode`の設定を`NO_ENGINE_SUBSTITUTION`にする、もしくは`NO_ZERO_DATE`を削除すれば一次対応は問題ないですが、mysql8を利用する際のサーバの要件として追加する必要があります。

cakePHPの[要件](https://book.cakephp.org/4/ja/installation.html)の中にもPHP拡張を入れる必要があるというものがあるので、baserCMSの要件として追加してもいいかと考えます。

コードからのアプローチとしては、テスト含めてSQLの日付が`"0000-00-00 00:00:00"`で設定されているものを全て`now()`などに置換する必要があります。

baserCMS version : 4.5.2-dev
OS: Alpine 3.6.5
PHP version: 7.3.27
apache version: 2.4.39 (Unix)
mysql verson: 8.0.26
 
 
## 備考
参考:
[mysql8リファレンス](https://dev.mysql.com/doc/refman/8.0/ja/sql-mode.html)

**Comment by yama** [comment]
@Diwamoto 

> タイムスタンプ（おそらくcreated）として"0000-00-00 00:00:00"を保存する際に

たびたびすみません。上記の件、どのテーブルだったか覚えてますか？
baserではdatetime型のカラムに関してはデフォルトnullを許容しているようですが、
わざわざ `0000-00-00 00:00:00` をインサートしようとしているのはどこだろう？と思いました。
