### ISSUE TITLE
脆弱性適用の状態がわかる機能追加

### ISSUE THREAD

**Issue by gondoh** [baserproject/basercms#1763]
## 概要
Issueの概要を What・Why も含めて書きます。

baserCMS version : 
 
## TODO
- [ ]
  - [ ]
 
 
## 備考

別途記載する内容があれば書きます。

**Comment by kaburk** [comment]
#1752 の Issuesと同様でしょうかー？

**Comment by ryuring** [comment]
同様とみなしてクローズします。 @gondoh @kaburk
