### ISSUE TITLE
メールコンテンツのデータキャッシュが無限に生成されてしまう問題のリファクタリング

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1765]
## 概要
#1603 ブログコンテンツ、メールコンテンツのデータキャッシュが無限に生成されてしまう問題を修正
こちらのパッチに対し、Model/MailContent.php側で、キャッシュbehaviorsを使わない書き方にする

**Comment by kaburk** [comment]
こちらの件、マージ済みのようでしたのでクローズします。
