### ISSUE TITLE
BcUpload->uploadImage()で、'imgsize' => 'mobile_thumb'としても大きい画像が表示されてしまう問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1767]
## 概要
BcUpload->uploadImage()で、
optionでimgsizeを指定した場合、

'imgsize' => 'mobile_thumb'としても大きい画像が表示されてしまう。

（'mobile' => true にしないと__mobile_thumbの画像が取得できない）

そのため、imgsizeが正しく効いていないような挙動になってしまう。

**Comment by kaburk** [comment]
こちらの件、マージ済みのようでしたので、クローズしますね。
