### ISSUE TITLE
管理画面にてゴミ箱に入っているコンテンツがサイドナビに表示されてしまう

### ISSUE THREAD

**Issue by yutorishine** [baserproject/basercms#1793]
## 概要
管理画面にてゴミ箱に入っているコンテンツがサイドナビに表示されており、リンクが無効になっている箇所があったため「ゴミ箱に入ったコンテンツはサイドナビに表示させない」ように改修する必要があります。

baserCMS version : 4.5.5

**Comment by kaburk** [comment]
マージ済みなのでクローズします！
