### ISSUE TITLE
ブログタイプのアイコン（fontawesome）のみitalic表示になっている

### ISSUE THREAD

**Issue by GUSSAN-BEEDAN** [baserproject/basercms#1815]
## 概要
admin-third管理テーマにおいて、コンテンツ一覧を表形式でプレビューした場合、
ブログタイプのアイコン（fontawesome）のみitalic表示になってしまっています。

<img width="544" alt="スクリーンショット 2022-04-10 14 35 28" src="https://user-images.githubusercontent.com/96756270/162603404-85d26356-0639-4252-bc74-23ae2d995356.png">

baserCMS version : 4.5.6
 
## TODO
- [ ] basercms/app/webroot/theme/admin-third/css/admin/style.cssの404行目に.bca-icon--blog::beforeを加える。
 
 
## 備考
フォーラム（ https://forum.basercms.net/t/topic/866 ） より

**Comment by ryuring** [comment]
@GUSSAN-BEEDAN よく気づかれましたね〜😅

**Comment by GUSSAN-BEEDAN** [comment]
滅多に表形式でプレビューすることはなかったので、皆さん、きっとそうじゃないですかね^^;
