### ISSUE TITLE
baserCMSのインストール時に、PHPのメモリ判定に失敗する

### ISSUE THREAD

**Issue by ice-creamer** [baserproject/basercms#1816]
## 概要
baserCMS のインストール時に、PHP.iniに1Gの指定があってもメモリが不足していると判定される。

baserCMS version : 4.5.6
 
## 備考

```
$memoryLimit = (int)ini_get('memory_limit');
```

ここでメモリの判定に失敗しているのではないかとの情報提供を受けました。

https://forum.basercms.net/t/topic/876/2?u=doi

ご確認、お願いします。

**Comment by ryuring** [comment]
こちらに記載したとおり、サーバーの設定方法の問題のためクローズします。
https://forum.basercms.net/t/topic/876/4
