### ISSUE TITLE
ファイルアップロード時にセキュリティコンポーネントに引っかかってしまう問題

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#1820]
## 概要
ブログのアイキャッチなどのファイルのアップロード時、post_max_size をオーバーしてしまうと、SecurityComponentに引っかかりブラックホール（不正なリクエスト）入りしてしまう。

upload_max_filesize サイズをオーバーしただけの場合は、対象ファイル以外のデータは送信され、errorフラグが立つことにより、正常なバリデーションエラーを表示できるが、post_max_size をオーバーした場合は、ポストデータが空になってしまうというPHPの仕様がある。

ポストデータが空になってしまった場合、SecurityComponent の validatePost で、期待されたフィールドのデータが飛んでこないということで、ブラックホール入りしてしまう。

baserCMS version : 4.5.6

**Comment by gondoh** [comment]
一番簡単な対応は、セキュリティコンポーネントで引っかかった場合は、「システムが受信できるデータ上限より大きなデータが送信された可能性があります。」みたいなメッセージをつけるとかでしょうか。

**Comment by gondoh** [comment]
POST送信で、受信データが0バイトの場合がほぼそうなのでそれで判別して出す。
cc @ryuring

**Comment by ryuring** [comment]
@gondoh お、それがよさそう。リオープンします！

**Comment by ryuring** [comment]
@gondoh この件、もう一度調べてみると、validatePost ではなく、 validateCsrf で引っかかっていました。
つまり、トークンすら飛んできていないということです。
「POST送信で、受信データが0バイトの場合」を判別できたとしても、動作させるためには、SecurityComponent をオフにするしかなさそうです。いかがしましょうか。

**Comment by gondoh** [comment]
たしかにそうっすね。エラーメッセージでの一律対応了解しました！
