### ISSUE TITLE
【システム】インストール時のPHPのメモリ上限値の判定方法について、再検証のお願い

### ISSUE THREAD

**Issue by ice-creamer** [baserproject/basercms#1821]
## 概要

baserCMS version : 4系

baserCMS のインストールの際のシステム環境のチェックにおいて、下記の事例ように `G` という短縮表記が用いられている場合にPHPのメモリ上限値の判定を誤る場合がある。

`php.ini`

```ini
memory_limit = 1G
```

サーバー側の設定の問題とのことで先日クローズされましたPHPのメモリ判定の件について、改めて[公式マニュアル](https://www.php.net/manual/ja/ini.core.php#ini.memory-limit)を参照してみたところ、次の２点を確認しました。

 - `memory_limit` の指定に `G` という短縮表記が使えない旨の記述を確認できなかった
 - デフォルトの設定値は `128M` である

そこで、備考に記述した方法で再度検証してみました。

## 備考

baserCMS4.5.6のソースコードの内、 `memory_limit` からPHPのメモリ上限値を判定していると思われるファイルを2つ見つけました。他のバージョンでも同様でした。

 - `~/basercms/lib/Baser/Controller/Component/BcManagerComponent.php`
 - `~/basercms/lib/Baser/Config/bootstrap.php`

それぞれのファイルで `intval()` や `(int)` を用いて、キャストしているのですが、この際に `1G → 1` と変換されるために PHPのメモリ上限値を `1MB` と判定してしまい、結果的に `32MB` へ再設定されていることがわかりました。

そこで、それぞれのファイルを下記の通り修正の後、インストールを実行したところ、サーバー側の設定は1Gのままでも、インストールは無事に完了しました。

現時点では、問題なく動作しているようです。

ただし、私自身が baserCMSの動作を熟知しているわけではないので、今回の検証方法が正しい方法かどうか判断つきかねています。

改めて、ご確認のほどよろしくお願いします。

 - `~/basercms/lib/Baser/Controller/Component/BcManagerComponent.php`

```php
	/**
	 * 環境チェック
	 *
	 * @return array
	 */
	public function checkEnv()
	{
		if (function_exists('apache_get_modules')) {
			$rewriteInstalled = in_array('mod_rewrite', apache_get_modules());
		} else {
			$rewriteInstalled = -1;
		}

		$status = [
			'encoding' => mb_internal_encoding(),
			'phpVersion' => phpversion(),
//			'phpMemory' => intval(ini_get('memory_limit')),
			'phpMemory' => ini_get('memory_limit'),
```

 - `~/basercms/lib/Baser/Config/bootstrap.php`

```php
/**
 * メモリー設定
 */
// $memoryLimit = (int)ini_get('memory_limit');
// if ($memoryLimit < 32 && $memoryLimit != -1) {
  $memoryLimit = return_bytes(ini_get('memory_limit'));
  if ($memoryLimit < (32 * (1024 ** 2)) && $memoryLimit != -1) {
	ini_set('memory_limit', '32M');
}
/**
 * メモリー設定関連の文字列からバイト数を得る関数
 * php.ini ファイルから値を読み取る場合、値は常にトリムされるため、
 * trim()関数を呼び出す必要はない。
 */
function return_bytes ($size_str)
{
    switch (substr ($size_str, -1))
    {
        case 'M': case 'm': return (int)$size_str * (1024 ** 2);
        case 'K': case 'k': return (int)$size_str * 1024;
        case 'G': case 'g': return (int)$size_str * (1024 ** 3);
        default: return $size_str;
    }
}
```

**Comment by ryuring** [comment]
ありがとうございます。
おっしゃるとおり、php.ini の設定についてさらに動作検証しましたところ次のようになることがわかりました。

・MとGは認識する
・それ以外は認識せず128M変換される（KもKBもMBも認識しない）
・MもGもない場合は128Mに設定される
・1Mを設定すると128Mになる
※ 128Mの数値は環境によって32Mの場合もあり

つまり、 `ini_get('memory_limit')` で取得できる値は、MとGしかない

というわけで次のコードで改善を入れたいと思います。

```
function getMemoryLimit ()
{
	$size = ini_get('memory_limit');
    switch (substr ($size, -1)) {
        case 'M': case 'm': return (int) $size;
        case 'G': case 'g': return (int) $size * 1024;
        default: return $size;
    }
}
```
@ice-creamer

**Comment by ryuring** [comment]
@ice-creamer 追記です。
認識しない場合の変換先メモリは、7系で32M、８系で128Mでした。
また、PHP7環境では、Gは認識されず、32Mに変換されました。
