### ISSUE TITLE
【システム】クラス名が組込側と重複することがある

### ISSUE THREAD

**Issue by hiraokakoichi** [baserproject/basercms#1822]
## 概要
クラス名が組込側と重複することがあるので、システム側のクラスにはbcをつける

[ユーザーズフォーラムにて指摘あり](https://forum.basercms.net/t/topic/878/3)

**Comment by GUSSAN-BEEDAN** [comment]
まず今回の様なfontawsomeやその他の汎用的なモジュールを管理側利用の目的でフロントエンド側に読み込ませるケースでは、テーマ側でも汎用的に利用される可能性も考慮して、CSSにおいてはクラス名の命名規則に準拠するような配慮は、やはり必要ではないかと思います。

また、今回のケースに限定すれば、fontawsomeは、そもそもToolbarエリアでの利用しか考えていないわけなので、
```
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: auto;
  src: url("../../fonts/admin/fa-solid-900.eot");
  src: url("../../fonts/admin/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../../fonts/admin/fa-solid-900.woff2") format("woff2"), url("../../fonts/admin/fa-solid-900.woff") format("woff"), url("../../fonts/admin/fa-solid-900.ttf") format("truetype"), url("../../fonts/admin/fa-solid-900.svg#fontawesome") format("svg"); }

#ToolBar .fa, #ToolBar .bca-toolbar__tools-button-publish a::before, #ToolBar .bca-toolbar__tools-button-edit a::before, #ToolBar .bca-toolbar__tools-button-add a::before,
#ToolBar .fas {
  font-family: 'Font Awesome 5 Free';
  font-weight: 900; }
```
などとするなどの配慮があれば問題ないかと。
また、ほんの数個のアイコン表示の目的で、ほとんど利用していないクラス名を少し乱暴に放り込んでしまっている点が、問題かと。
実際、利用されているクラスは、別途、以下の様な記述がCSS後半に記述がありますし。
```
  .bca-toolbar__tools-button-publish a::before {
    content: "\f06e"; }
  .bca-toolbar__tools-button-edit a::before {
    content: "\f303"; }
  .bca-toolbar__tools-button-add a::before {
    content: "\f055"; }

.bca-toolbar__tools-button-publish a::before {
  font-weight: 400; }
```

**Comment by ryuring** [comment]
@GUSSAN-BEEDAN @hiraokakoichi こちらフォーラムのログなども改めて確認したのですが、Toolbarには、既に、`bca-` というプレフィックスを与えていますので、「クラス名が組込側と重複することがある」というわけではなく、下記の行にて、`@import 'theme/var/icons';` を記述してしまったという事が問題ですよね。

https://github.com/baserproject/basercms/commit/5f8c960557061af490592816a32e7038a207cc58#diff-acbf186c006b15a7a59df3d819a8f7ee5c7f45aa8c5065ca49e6838b203fab4fR3

なので、`@import 'theme/var/icons';` を除外して、 @GUSSAN-BEEDAN  がおっしゃるような対応を行おうかと思います。

**Comment by GUSSAN-BEEDAN** [comment]
@ryuring 
お手数ですが、ご対応よろしくお願いします。

**Comment by GUSSAN-BEEDAN** [comment]
@ryuring 
添付のとおり、4.6.1-devにて不具合が解消されていることを確認しました。
<img width="1028" alt="スクリーンショット 2022-06-12 18 30 08" src="https://user-images.githubusercontent.com/96756270/173226957-d47c16c2-fcf6-4f9d-b6fc-e99fe2ccf35c.png">

**Comment by ryuring** [comment]
@GUSSAN-BEEDAN 確認ありがとうございます〜
