### ISSUE TITLE
ブルグ記事をコピーする際にアイキャッチ画像がコピーされない

### ISSUE THREAD

**Issue by limnj** [baserproject/basercms#1838]
## 概要
ブルグ記事をコピーする際にアイキャッチ画像がコビー元の記事と同じ名前になってる
コピーした記事を削除したら画像も削除されますが、コピー元の記事のアイキャッチ画像がリンク切れになる。

baserCMS version : 4.6.1
 
## TODO
- [ ]
  - [ ]
 
 
## 備考

別途記載する内容があれば書きます。

**Comment by limnj** [comment]
ブルグ記事をコピーする際にアイキャッチ画像がコピーされない問題は改善されましたが、
コピー元記事のアイキャッチ画像が削除されます。

**Comment by ryuring** [comment]
@limnj こちらのコミットも必要となります、報告ありがとうございます。
https://github.com/baserproject/basercms/commit/fabb26b123e9b515f160727cffd583820ac9440b
