### ISSUE TITLE
【ユーザー】Users.afterLoginイベントが消えている

### ISSUE THREAD

**Issue by kk-uchino** [baserproject/basercms#1846]
## 概要
UsersController::admin_loginからafterLoginイベントが消えている

**Comment by GUSSAN-BEEDAN** [comment]
「消えている」というのは、いったいどういった事情なのでしょうか？

**Comment by gondoh** [comment]
@GUSSAN-BEEDAN 
表題の件についてログを確認したところ、Users.afterLoginイベントというものはなく、イベントの追加という形でmergeしてます。
releaseノートについても、追加と言う形で公表予定ですー。

**Comment by GUSSAN-BEEDAN** [comment]
@gondoh わざわざご確認いただきありがとうございます。承知いたしました。
