### ISSUE TITLE
固定ページ編集画面でデータピッカーが動かない

### ISSUE THREAD

**Issue by goichi-m** [baserproject/basercms#1859]
## 概要
固定ページの編集画面（管理画面のテーマがセカンドの時）で公開期限などを決めるinputにかかっているデータピッカーが動作しません。JSでエラーが出ているようです。

baserCMS version : 4.6.0以降の模様です

**Comment by GUSSAN-BEEDAN** [comment]
固定ページに限らず、timepicker.jsを使用しているadmin-secondのフィールドで発生していますが、以下の対応で動作はする様に対応済みです。
fix https://github.com/baserproject/basercms/issues/1857 admin-second テーマにおいてファイルアップロード管理で一覧が表示できない問題を改善(https://github.com/baserproject/basercms/commit/17ee013db034758bc5a1e2cbc5c24bcf2fca79d2)

ですが、一部、UIが崩れています。（画像参照）
<img width="1391" alt="スクリーンショット 2022-08-05 19 19 42" src="https://user-images.githubusercontent.com/96756270/183059152-588fd1a0-7222-44c9-8579-4661370ace59.png">

**Comment by GUSSAN-BEEDAN** [comment]
lib/Baser/View/Layouts/admin/default.php に admin/jquery.timepicker.cssを適用漏れの様です。

**Comment by ryuring** [comment]
@goichi-m @GUSSAN-BEEDAN がおっしゃるとおりです。次のバージョンでなおりますのでこちらはクローズしますね。

**Comment by GUSSAN-BEEDAN** [comment]
確かに「fix https://github.com/baserproject/basercms/issues/1857 admin-second テーマにおいてファイルアップロード管理で一覧が表示できない問題を改善」で、lib/Baser/View/Layouts/admin/default.phpへのadmin/vendors/jquery.timepicker.jsの適用はされてますが、
このままクローズしてしまうと、admin/jquery.timepicker.cssの適用漏れになってしまうかと。。。

**Comment by GUSSAN-BEEDAN** [comment]
↑
@ryuring

**Comment by ryuring** [comment]
@GUSSAN-BEEDAN CSSが漏れていたのですね、対応しておきました。
https://github.com/baserproject/basercms/commit/01e55164ea6b06c3c5e33be01aacfb985892bcfa
