### ISSUE TITLE
[要望]メールフォーム入力チェックに「数値とハイフン」のチェックを入れたい

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#1882]
## 概要
メールフォームの入力チェックに関して、

- 数値チェック
- 数値チェック（入力必須）

は存在するが、電話番号や郵便番号など「ハイフン」が入るパターンも使用頻度が高いので、
正規表現チェックではなく、入力チェックの項目に追加したい

### イメージ
<img width="603" alt="image" src="https://user-images.githubusercontent.com/15135892/202642759-f4f9e242-cbd4-46ce-a9f3-cd6cb463107f.png">

**Comment by ryuring** [comment]
- 電話番号チェック
- 郵便番号チェック
の方がわかりやすいと思うのですがいかがでしょうか？
@katokaisya
