### ISSUE TITLE
#1795 取込に伴う必須表示の変更

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#2037]
この Issue は、baserCMS５のフォークが作成された、baserCMSバージョン4.4.7以降に作成されたコミットを baserCMS５に移行するための Issue です。
移行が必要かどうか判断し必要な場合は、画面右の「Convert to Issue」をクリックして「ucmitz」を選択して Issue化した上で、ucmitz レポジトリに、移行版のプルリクエストを作成してください。そうでない場合はクローズしてください。
4月10日に移行が完了しないとbaserCMS５はデグレを起こしてしまいますのでご注意ください。
どうしていいかわからない場合は、@ryuring に連絡をお願いします。
移行元のコミットはこちらです。
https://github.com/baserproject/basercms/commit/14cd89b3fdda3a3e4ca22e84afcb4a56637d00f4

**Comment by ryuring** [comment]
こちらのコミットで対応
https://github.com/baserproject/basercms/commit/84042065aef239d08dbe5a7f39d59b4b35fa7b8f
