### ISSUE TITLE
Merge pull request #1795 from yutorishine/#1648

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#2038]
この Issue は、baserCMS５のフォークが作成された、baserCMSバージョン4.4.7以降に作成されたコミットを baserCMS５に移行するための Issue です。
移行が必要かどうか判断し必要な場合は、画面右の「Convert to Issue」をクリックして「ucmitz」を選択して Issue化した上で、ucmitz レポジトリに、移行版のプルリクエストを作成してください。そうでない場合はクローズしてください。
4月10日に移行が完了しないとbaserCMS５はデグレを起こしてしまいますのでご注意ください。
どうしていいかわからない場合は、@ryuring に連絡をお願いします。
移行元のコミットはこちらです。
https://github.com/baserproject/basercms/commit/37e5c103e91237b2ad8850d9a3d8d9af6eaf5384

**Comment by ryuring** [comment]
こちらのコミットで対応
https://github.com/baserproject/basercms/commit/9056aa7afb86b9d3ed98d45c219fae2069e70b1c
