### ISSUE TITLE
管理画面にてゴミ箱に入っているコンテンツがサイドナビに表示されてしまう #1793

### ISSUE THREAD

**Issue by cu-morishita** [baserproject/basercms#2040]
この Issue は、baserCMS５のフォークが作成された、baserCMSバージョン4.4.7以降に作成されたコミットを baserCMS５に移行するための Issue です。
移行が必要かどうか判断し必要な場合は、画面右の「Convert to Issue」をクリックして「ucmitz」を選択して Issue化した上で、ucmitz レポジトリに、移行版のプルリクエストを作成してください。そうでない場合はクローズしてください。
4月10日に移行が完了しないとbaserCMS５はデグレを起こしてしまいますのでご注意ください。
どうしていいかわからない場合は、@ryuring に連絡をお願いします。
移行元のコミットはこちらです。
https://github.com/baserproject/basercms/commit/e7e51340fa3cc15474ad074681faa5e039fa8179

**Comment by ryuring** [comment]
5系では論理削除の仕様が変わり、表示されなくなったためクローズ

**Comment by ryuring** [comment]
こちらの件は、baserCMS５で発生しないためクローズします。
