### ISSUE TITLE
ver5 【ブログ】記事一覧で公開期間外の記事の背景が灰色にならない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2048]
## 概要
記事一覧で公開期間外の記事の背景が灰色にならない

baserCMS version : 5.0.0-beta4

`ver5` ラベルが設定できないためタイトルに記載しています。

**Comment by ryuring** [comment]
いただきます

**Comment by ryuring** [comment]
<img width="761" alt="スクリーンショット 2023-04-18 15 39 46" src="https://user-images.githubusercontent.com/90106/232692659-82f71d7f-39ce-4f1f-8fff-9cffb3a8b7ea.png">
<img width="997" alt="スクリーンショット 2023-04-18 15 39 14" src="https://user-images.githubusercontent.com/90106/232692689-32e696e1-319b-4a41-a6e2-1ea671b8d057.png">

@seto1 再現できないですね。やり方を教えてくださいー

**Comment by seto1** [comment]
@ryuring  ありがとうございます。公開状態を「公開」でお願いします。
