### ISSUE TITLE
【システム】 サブフォルダへの設置ができない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2128]
## 概要

サブフォルダへbaserを設置した場合、設置URLにアクセスするとNOT FOUNDになる

baserCMS version : 5.0.1-dev
 
## TODO
- .htaccees と webroot/.htaccess の以下の行をコメントアウトすると動作するため、外した場合の影響の調査
    - `RewriteBase /`

**Comment by ryuring** [comment]
@seto1 基本的に下記のページの処理で大丈夫なはずです。
https://baserproject.github.io/5/ucmitz/etc/subfolder

**Comment by seto1** [comment]
@ryuring ドキュメントありがとうございます!
インストールページなど関連しそうなページからリンク貼っておきます。

**Comment by ryuring** [comment]
> インストールページなど関連しそうなページからリンク貼っておきます。
ありがとうございます！
