### ISSUE TITLE
updateコマンドの実行に失敗した際、プラグインが無効になる

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2130]
## 概要

以下のコマンドを実行した際にエラーが発生した場合、各種プラグインが無効になる

```
./bin/cake update
```

baserCMS version : 5.0.1-dev
 
## TODO
- プラグインを無効化している箇所
    - https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/src/Service/PluginsService.php#L184
- アップデート時にプラグインを無効化しない場合の動作
- エラー時にプラグイン有効化
    - 全て もしくは エラーが発生したプラグイン以外

**Comment by ryuring** [comment]
@seto1 ちなみにエラーはどこで発生したのでしょう？スクリプトの実行ですか？

**Comment by seto1** [comment]
@ryuring 問題が起きたのが先月のことであまり詳細な状況を記録できていないのですが、もう少し詳しく記載すると以下の状況です。

1. 初期インストールを行った環境とは別の環境のbaserのアップデートを試みる
2. baser関連のファイルをSFTPで上書き
3. `./bin/cake update` コマンドでDBの更新を行う
    - ここでエラー
    - 全てのログは記録できていないものの以下のエラーが含まれていたことは確認

```
Invalid datetime format: 1292 Incorrect datetime value: ‘0000-00-00 00:00:00’ for column ‘created’ at row 1
```

4. 該当環境のTOPページが開けなくなり調査したところプラグインが無効になっていたことを確認

事前にローカル環境で実行したときは上手くいきました。
ローカルと別の環境とで、mysqlのsqlmodeが異なっていたことが原因ではとは考えています。

エラーの発生元としては何かのマイグレーションファイルのSQLでした。

**Comment by ryuring** [comment]
@seto1 情報ありがとうございます。
マイグレーションファイルなんですね、再現できたらロールバック処理を書きたいと思います。

**Comment by ryuring** [comment]
@seto1 同じエラーの再現はできませんでしたが、取り急ぎ、不正なマイグレーションファイルを配置するテストを書いて解決しています。
https://github.com/baserproject/basercms/commit/31562361d41cf8648d5419b86d8325e8ba3495a8
