### ISSUE TITLE
【カスタムコンテンツ】カスタムエントリーAPIの index で custom_table が取得できてしまう

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#2199]
## 概要
index の場合、データ量を減らすために、関連デーブルのデータを取得しない仕様が前提だが取得できてしまうのが問題

baserCMS version : 5.0.0
 
## 補足
CustomEntriesService::createIndexConditions() にて、select メソッドでフィールド指定をしているがそれが効いてない様子

**Comment by ryuring** [comment]
@nghiem-mb こちらの件、`Api/CustomEntriesController` と `Api/Admin/CustomEntriesController` の両方について、まずは再現性の確認からお願いします。

index メソッドでは、関連データを取得しないという仕様が正しいです。

**Comment by nghiem-mb** [comment]
> @nghiem-mb こちらの件、`Api/CustomEntriesController` と `Api/Admin/CustomEntriesController` の両方について、まずは再現性の確認からお願いします。
> 
> index メソッドでは、関連データを取得しないという仕様が正しいです。

はい。対応します。
