### ISSUE TITLE
アップデートの際に書き込み権限が必要なファイルが存在する

### ISSUE THREAD

**Issue by gondoh** [baserproject/basercms#2225]
## 概要
baserCMS5でアップデートを行うと下記ファイルの書き込み権限が必要になる。
composer.json
composer.lock

アップデート実行ボタンがクリック可能なため、書き込み権限を確認して実施したほうがいい

baserCMS version : 5.0.0
 
## TODO
- ファイルのパーミッションチェックの実装
- パーミッションチェックに許可された場合のみアップデートが実行できるように改善

**Comment by ryuring** [comment]
vendor も確認した方が良さそうですね。

**Comment by ryuring** [comment]
@gondoh こちらのコミットで解消しましたのでクローズします。
https://github.com/baserproject/basercms/commit/3861c5af8d3912b74670e6e8d326359d39e43579
