### ISSUE TITLE
JWT認証が必要な領域でも、認証チェックが無効になっているURLはCSRF制限をかけたい

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2302]
## 概要

コントローラーでallowUnauthenticatedを設定している状態
JWT認証が必要な領域でログイン・未ログインどちらでもアクセス可能なAPIが存在する場合に制限が必要

baserCMS version : 5.0.0

**Comment by seto1** [comment]
ここを外してどうなるか要確認

https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/src/Plugin.php#L312

```
// 認証できていない場合、領域がJwt認証前提の場合はスキップ
if($authSetting['type'] === 'Jwt') return true;
```

影響出るのはログインだが、スキップ設定されているので問題ないはず
https://github.com/baserproject/basercms/blob/14c527a002fc18d054f91ee7637aa9df4a28d21b/plugins/baser-core/src/Plugin.php#L304
https://github.com/baserproject/basercms/blob/14c527a002fc18d054f91ee7637aa9df4a28d21b/plugins/baser-core/config/setting.php#L354

**Comment by ryuring** [comment]
@seto1 こういう文献もあるんですがどうですかね？
https://qiita.com/mejileben/items/ae7b346f0fc4a59101b5

**Comment by seto1** [comment]
@ryuring Authorizationヘッダが必要な場合はCSRF対策用のトークンは不要だと思いますが、allowUnauthenticatedの対象の場合はAuthorizationヘッダが無くてもアクセスできちゃうんですよね。

**Comment by ryuring** [comment]
@seto1 あああ、なるほどケースが違うのか。理解できました。
