### ISSUE TITLE
テーマ内に設置したBlog/default/posts.php が $this->BcBaser->blogPostsで読み込まれない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2303]
## 概要

テーマ（初期状態だと BcThemeSample ）内 plugins/BcThemeSample/templates/plugin/BcBlog/Blog/default 内に
ブログのテンプレート各種ファイルを設置しても $this->BcBaser->blogPosts で posts.phpが正しく読み込まれず、
bc-frontの posts.php が優先されて読み込まれてしまっているようです。

plugins/bc-front/templates/plugin/BcBlog/Blog/default/posts.php
plugins/BcThemeSample/templates/plugin/BcBlog/Blog/default/posts.php

baserCMS version : 5.0.1
  
## 備考

index.php、archives.php、single.php については テーマ内に設置したものが優先されるようです
（正しい動作）

**Comment by ryuring** [comment]
ちょっと見てみますね @kaburk

**Comment by ryuring** [comment]
@kaburk こちらの件、確認しました。
baserCMS4の時も同様の仕様だったのですが、`element` ディレクトリが必要となるようです。

このパスに配置する場合は
```
plugins/BcThemeSample/templates/plugin/BcBlog/Blog/default/posts.php
```
次の element ディレクトリが必要になります。
```
plugins/BcThemeSample/templates/plugin/BcBlog/element/
```

次のパスに配置する場合は
```
plugins/BcThemeSample/templates/Blog/default/posts.php
```
次の element ディレクトリが必要になります。
```
plugins/BcThemeSample/templates/element/
```

**Comment by ryuring** [comment]
@kaburk 公式ガイドに記載しておきました。問題なければクローズお願いします。
https://baserproject.github.io/5/theme/customizing_template#postsphp-%E3%82%92%E8%A8%AD%E7%BD%AE%E3%81%97%E3%81%A6%E3%82%82%E5%8F%8D%E6%98%A0%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88
