### ISSUE TITLE
RSSフィードにてブログ記事へのURLが正しく生成されない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2368]
## 概要
フロントエンドでブログのURL末尾を /index.rss にすると表示されるRSSフィード
例えば /news/ の場合 /news/index.rss
のRSS内のブログ記事へのURLが正しく生成されないようです。
ただブログ記事のスラッグが設定されているときは正しいURLのようですのでスラッグがないときのみ記事URLが生成されていない感じでした。
 
■ baserCMS 5系のRSS  /news/index.rss を整形したもの

<img width="836" alt=" baserCMS5 blog RSS" src="https://github.com/baserproject/basercms/assets/310333/c53ada63-4597-44a9-90e4-4a45df46cc45">

■ baseCMS 4系のRSS  /news/index.rss を整形したもの

<img width="827" alt=" baserCMS4 blog RSS" src="https://github.com/baserproject/basercms/assets/310333/709ac59f-315b-4cc3-aa65-6b24321caefc">

baserCMS version :  5.0.2-dev

**Comment by ryuring** [comment]
@kaburk 報告ありがとうございます。バグですね、対応できますか？
