### ISSUE TITLE
特定の文字を送信すると文字化けする

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2483]
## 概要

例: 「瞭」を送信すると「迸ュ」に変換される

<img width="925" alt="スクリーンショット 2023-06-22 20 52 20" src="https://github.com/baserproject/basercms/assets/30764014/d58483fa-deca-42e9-b213-bc7ab3cba32e">

送信データを変換している箇所で文字化けする
https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/src/Controller/AppController.php#L254

BcEncode.detectOrderから「SJIS-win」を削除すると文字化けしない
https://github.com/baserproject/basercms/blob/dev-5/plugins/baser-core/config/setting.php#L734

PHP8.1だとmb_detect_orderの仕様が変更されていることが原因の可能性
https://speakerdeck.com/pakutoma/how-we-have-responded-to-the-php-8-dot-1-mbstring-specification-changes

baserCMS version : 5.0.2-dev
 
## TODO
- BcEncode.detectOrderから「SJIS-win」を削除して問題ないかの確認
- そもそも送信データをUTF-8に変換する処理が必要かの確認

**Comment by ryuring** [comment]
@seto1 こちら最新の開発版で確認したところ再現できませんでした。一度確認して頂いてもいいですか？

**Comment by seto1** [comment]
@ryuring 環境の違いでしょうか。
再度ローカルの最新版で確認したところ再現したほか、デモサイトでも再現しました。
https://trial.basercms.net/baser/admin/bc-blog/blog_posts/add/1

ブラウザは以下で確認しました。

- Chrome
- Chrome シークレットモード
- Safari

**Comment by seto1** [comment]
「瞭」だけ送信するかによっても変わりますね。
「明瞭」だと正常に保存できました。

**Comment by seto1** [comment]
EUC-JP: `大槻`

**Comment by kaburk** [comment]
[https://trial.basercms.net/](https://trial.basercms.net/)にて　幾つか試しましたが、現象が再現しました。
<p>タグとかで囲われると大丈夫な場合があったり、幾つか条件ありそうではあります。

保存前
<img width="1077" alt="スクリーンショット 2023-11-02 10 18 33" src="https://github.com/baserproject/basercms/assets/310333/62610289-5551-43ae-8fb1-eea58a66c169">
保存後
<img width="1111" alt="スクリーンショット 2023-11-02 10 18 47" src="https://github.com/baserproject/basercms/assets/310333/76754da6-e0bc-4a79-b368-644c573de709">
<img width="1022" alt="スクリーンショット 2023-11-02 10 18 55" src="https://github.com/baserproject/basercms/assets/310333/d9c5b2e9-8563-4df5-a11c-bcc87028e29d">

**Comment by ryuring** [comment]
@seto1 @kaburk 確認ありがとうございます。
加賀澤さんとも話したのですが、今どき送信データがUTF-8でないこと自体が問題だろうということになったので、変換処理を削除しました。
