### ISSUE TITLE
isCurrentUrlが機能していない

### ISSUE THREAD

**Issue by teratai3** [baserproject/basercms#2502]
## 概要
一致しているurlでもisCurrentUrlが機能していません。

baserCMS version : 5.0.1

 
## 備考
BcBaserHelper.phpの処理のタイプミスで機能していないのではないかと思います。
```
//BcBaserHelper.php 現在の処理
$shortenedHere = preg_replace($pattern, '/index', $this->_View->getRequest()->here);

//変更
$shortenedHere = preg_replace($pattern, '/index', $this->_View->getRequest()->getAttribute('here'));
```

**Comment by ryuring** [comment]
@teratai3 ご報告ありがとうございます。おそらくCake2系からCake4系への移行漏れだと思います。

**Comment by ryuring** [comment]
@HungDV2022 こちら確認お願いします。テストも動作すりょうに調整してください。
