### ISSUE TITLE
bcmailプラグインapi新規追加が機能していない

### ISSUE THREAD

**Issue by teratai3** [baserproject/basercms#2503]
## 概要
bcmailプラグインapi新規追加が機能していない

baserCMS version : 5.0.1
 
 
## 備考
メールメッセージの新規追加
https://baserproject.github.io/5/web_api/baser_api/bc-mail/mail_messages/add

mailContentIdをgetQueryParamsでとらず、引数で取得しようとしている？ので機能していない気がします。
(baser Admin APIの方のaddメソッドはおそらく機能しています。

↓BcApiControllerを継承したMailMessagesController抜粋
```
 public function add(
        MailMessagesServiceInterface $service,
        MailContentsServiceInterface $mailContentsService,
        int $mailContentId
    )
```

**Comment by ryuring** [comment]
@teratai3 ご報告ありがとうございます。調査要ですね。

**Comment by teratai3** [comment]
@ryuring 
後すみません関連して、↑の問題を解消していても入力必須項目がapi側から送信する場合は未入力でも値が記録される気がします。
(これはbaser Admin APIの方もそうかと思います。)
![test1](https://github.com/baserproject/basercms/assets/52107087/076bd2cd-f3cd-40d0-aaf6-d401bef7c80d)

![test2](https://github.com/baserproject/basercms/assets/52107087/850cbc53-6f83-4ecf-8d5a-80fef6961b78)

**Comment by ryuring** [comment]
> 後すみません関連して、↑の問題を解消していても入力必須項目がapi側から送信する場合は未入力でも値が記録される気がします。

こちらの件、もしかしたら下記のコミットで解消されているかもしれません。開発環境を最新にして試して頂けますか？
https://github.com/baserproject/basercms/commit/01ce3bca79352c0cf885d73d3e9ac7e4e0b3bd6a

**Comment by teratai3** [comment]
@ryuring 
すみません見逃していました。確認して修正されてました。

**Comment by ryuring** [comment]
@teratai3 お、よかったです😊
