### ISSUE TITLE
管理画面 ブログ記事一覧のタイトル部分をクリックしても並び順が切り替わらない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2527]
## 概要
管理画面 ブログ記事一覧のタイトル部分をクリックしても並び順が切り替わらないようです。
URLのクエリパラメータも direction=ascのままで direction=desc にならない状態でした。

（ただし、 カテゴリの列だけは切り替わる状態 :-) ）

<img width="1672" alt="スクリーンショット 2023-06-29 20 36 58" src="https://github.com/baserproject/basercms/assets/310333/d4697c82-114e-4bba-af77-99387de8870b">

baserCMS version :  5.0.2-dev

**Comment by ryuring** [comment]
こちらのコミットで改善してくれましたのでクローズします。
https://github.com/baserproject/basercms/pull/2714
