### ISSUE TITLE
【メール】メールメッセージの新規追加APIにバリデーションのみを実行するオプションがほしい

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2551]
もしくはバリデーション用の別API
確認画面を実装する場合に必要

https://baserproject.github.io/5/web_api/baser_api/bc-mail/mail_messages/add

baserCMS version : 5.0.2

**Comment by ryuring** [comment]
@HungDV2022 こちら次の前提条件の元実装をお願いします。

- POSTでデータを受け付ける
- CSRFトークン必要
- MailMessagesControllerに実装
- メソッド名を validate とする
- 成功時は `succsess` => true を返却
- 失敗時は、`success` => false とエラーメッセージを配列で返却
- テストを追加する
- APIドキュメントを追加する

**Comment by ryuring** [comment]
@seto1 こちら解決しています。ドキュメントはこちらです。
https://baserproject.github.io/5/web_api/baser_api/bc-mail/mail_messages/validate
