### ISSUE TITLE
[カスタムコンテンツ] カスタムテーブルの編集画面で同じ利用中のフィールドを削除して、追加したら、エラーが表示されます。

### ISSUE THREAD

**Issue by HungDV2022** [baserproject/basercms#2586]
![image](https://github.com/baserproject/basercms/assets/110375578/6d7a6eb6-2140-451a-8ae3-f4eacee3cfd4)

**Comment by ryuring** [comment]
@HungDV2022 こちらについて再現ができません。

試した手順は次のとおりです。

1. 求人情報テーブルを開く
2. 求人分類を削除
3. 求人分類を追加
4. 保存

正常に保存できます。

再現手順を具体的に教えてください。

**Comment by ryuring** [comment]
再現ができないということで、一旦、クローズにしますね。
