### ISSUE TITLE
【システム】ログアウトしても代理ログイン情報が記録されたまま

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2630]
baserCMS version: 5.0.2

1. 管理者でログイン
2. 適当なユーザーに代理ログイン
3. ログアウト
4. 管理者でログイン
5. 再度適当なユーザーに代理ログインしようとすると「既に代理ログイン中のため失敗しました。」と表示される

**Comment by ryuring** [comment]
@HungDV2022 手があいたら確認お願いします。
