### ISSUE TITLE
【システム】管理画面「パスワードを忘れた場合はこちら」存在するメールアドレスと存在しないメールアドレスを入力した場合とで挙動が異なる

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#2678]
baserCMS version : 5.0.3
 
/baser/admin/baser-core/password_requests/entry

■存在するユーザーのメールアドレスを入力した場合のメッセージ

> パスワードのリセットを受付ました。該当メールアドレスが存在した場合、変更URLを送信いたしました。

入力したメールアドレスが使われているかが分からないように考慮されている

■存在しないユーザーのメールアドレスを入力した場合

エラーになる

**Comment by ryuring** [comment]
挙動あわせないとですね
