### ISSUE TITLE
フィールド設定の全角ひらがなチェックに"ー”(長音符)が含まれていない

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2720]
## 概要
フィールド設定の全角ひらがなチェックに"ー”(長音符)が含まれていない
理由:公文書規定では外国人名などのカナ書で長音符を含む名称などはひらがなで長音符を使っても良いことになっています

baserCMS version : 全バージョン

**Comment by ryuring** [comment]
@rabbitchang こちらはメールプラグインのメールフィールドですか？
カスタムコンテンツもフィールドを持っているので念のため確認です。

**Comment by rabbitchang** [comment]
@ryuring はい！気づいたのはメールフォームのテストをしている時です。

**Comment by ryuring** [comment]
@rabbitchang 了解です！

**Comment by ryuring** [comment]
@HungDV2022 メールフィールドのバリデーションを調整してください。
全角ひらがなチェックのバリデーションが入っている時に「ー」が含まれているとエラーとなっている。
「ー」が含まれている際もエラーとならないようにしてください。

「マーク」OK
「ma-ku」NG

**Comment by HungDV2022** [comment]
@ryuring 
ローカル環境でテストしてみましたが、問題なかったです。確認お願いします。
<img width="952" alt="スクリーンショット 2023-09-19 9 25 14" src="https://github.com/baserproject/basercms/assets/110375578/6c5bd620-8bb0-4c56-9344-8aa3a88e6bad">
<img width="1119" alt="スクリーンショット 2023-09-19 9 26 06" src="https://github.com/baserproject/basercms/assets/110375578/d68ffd90-94d1-48b5-bbca-87997c2120ba">

**Comment by ryuring** [comment]
@HungDV2022 確認ありがとうございました。
@rabbitchang ということは、５系では発生せず、４系のみの問題ということだと思います。
４系ラベルを貼っておきます。

**Comment by katokaisya** [comment]
@ryuring プルリク送りました。
https://github.com/baserproject/basercms/pull/2787

**Comment by ryuring** [comment]
こちらのプルリクで解決
https://github.com/baserproject/basercms/pull/2787
