### ISSUE TITLE
【カスタムコンテンツ】カスタムフィールド編集においてラジオやマルチチェックで同じ値を複数定義できてしまう

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#2744]
## 概要
例えば、次のようなラジオボタンを作成した際に、保存できてしまう。

- 選択１
- 選択２
- 選択３
- 選択１

## 対策
バリデーションエラーを表示する
「選択リストに同じ項目を複数登録できません。」

baserCMS version : 5.0.4

**Comment by nghiem-mb** [comment]
@ryuring 
セレクトボックスもバリデーションしないといけませんね

**Comment by ryuring** [comment]
@nghiem-mb そうですね！
