### ISSUE TITLE
[baserCMS4系]メールとブログの説明文について rubyタグが除外されてしまう問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#2860]
## 概要
[メールとブログの説明文について script タグを除外](https://github.com/baserproject/basercms/commit/5a20626d91ce3f3f77aceb60ee08ba73fd83ce16)

こちらの変更で、<ruby>・<rt>・<rp>タグが使用できなくなりました。

baserCMS version : 4.8.0

**Comment by seto1** [comment]
https://github.com/baserproject/basercms/pull/2861
