### ISSUE TITLE
FixtureManager を FixtureFactory に変更する

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#2883]
## 概要
CakePHP5にて、FixtureManager が除外されるため、ユニットテストで、FixtureManager を利用している箇所について、FixtureFactory に変更する。

[dev-cake5](https://github.com/baserproject/basercms/tree/dev-cake5) ブランチよりトピックブランチを作成し、`dev-cake5` ブランチにプルリクエストを送信する。

baserCMS version : 5.0.6

**Comment by HungDV2022** [comment]
@ryuring こちらは対応しましたのでクローズします。
