### ISSUE TITLE
[baserCMS5系]管理画面のサイト管理において、「識別名称」のフィールドヘルプの内容から期待される動作と実際の動作が異なる為、仕様を確認したい

### ISSUE THREAD

**Issue by ice-creamer** [baserproject/basercms#2906]
## 概要

「管理画面」の「サイト管理」において、「識別名称」のフィールドヘルプの文章は次の通りです。

```
サブサイトを特定する事ができる識別名称を入力します。半角英数とハイフン（-）・アンダースコア（_）のみが利用できます。エイリアスを入力しない場合は、URLにも利用されます。
```

この内容から「識別名称」はエイリアスが空欄でも設定可能であると解釈しました。

しかし実際には、エイリアスを空欄のまま「保存」ボタンを押すと

「入力エラーです。内容を修正してください。」と表示され、「エイリアスを入力してください。」とエイリアスの入力を促される。

## 質問事項

この動作について、下記の２つは、どちらの解釈が正しいのでしょうか？

1. 「識別名称」のフィールドヘルプの文章に誤りがある
2. フィールドヘルプの文章が正しく、「識別名称」のエイリアスを空欄にして保存できない方がおかしい

baserCMS version : 5.0.6

**Comment by ryuring** [comment]
@ice-creamer 確認したところ、どちらも正しくないというのが正解でした。

「エイリアスは空にできるが、空にした場合、識別名称が自動的にセットされる」というのが正しい仕様です。
それに伴い、コミットを作りました。
https://github.com/baserproject/basercms/commit/643b00f6aff80f5ea62fc200a7bb905b10cf177a

問題なければクローズお願いします。

**Comment by catchup-doi** [comment]
本来の仕様通りに、ヘルプや機能が修正されていることを確認しましたので、この件はクローズします。

**Comment by ice-creamer** [comment]
本来の仕様通りに動作していることを確認しましたので、この件はクローズします。

**Comment by ryuring** [comment]
@ice-creamer 確認ありがとうございました！
