### ISSUE TITLE
【テーマファイル管理】コピーができない

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2908]
## 概要
サンプルでコピーができるものとできないものがある。
サンプルテーマ  ( BcThemeSample )はコピーできるが、BcColumnはコピーできない。

baserCMS version : 5.0.7-dev

**Comment by ryuring** [comment]
@kaburk 確認ありがとうございます。

> plugins/baser-core/config/setting.php とか見るとコアパッケージやコアプラグイン一覧に bc-column は入ってないのでフォルダ名を plugins/BcColumn にするのが良い気がしますがどうしましょうか？？

確かにそうですね。BcThemeSample と同じような位置づけでもありますのでその方向でお願いします。
