### ISSUE TITLE
【アップロード管理】長いカテゴリ名が見切れてしまっている

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2910]
## 概要

◾️アップロード管理→アップロードファイルの絞り込み検索

カテゴリの文字が見切れてしまっている。（枠の横幅が固定されている）

![スクリーンショット 2023-12-01 15 17 30](https://github.com/baserproject/basercms/assets/84309553/86941b69-45cf-4b98-8ff0-186794b88a96)

◾️アップロード管理→アップロードカテゴリ一覧→アップロードカテゴリ編集

長い文字を入力すると見切れてしまう。

![スクリーンショット 2023-12-01 15 25 42](https://github.com/baserproject/basercms/assets/84309553/f0931651-77f2-4679-9deb-26d3f80d1cf3)

baserCMS version : 5.0.7-dev

**Comment by ryuring** [comment]
@HungDV2022 こちら、横幅100%に変更でお願いします。
