### ISSUE TITLE
【アップロード管理】削除時のダイアログの文言が統一されていない

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2911]
## 概要
アップロード管理の「アップロードファイル」画面と「アップロードカテゴリ」画面での削除時のダイアログの文言が異なっています。

アップロードファイル画面「本当に削除しても『よろしいですか？』」

![スクリーンショット 2023-12-01 15 42 52](https://github.com/baserproject/basercms/assets/84309553/22bab600-0967-43fa-a4a2-f6560dec1760)

アップロードカテゴリ画面「●●を本当に削除しても『いいですか？』」

![スクリーンショット 2023-12-01 15 43 57](https://github.com/baserproject/basercms/assets/84309553/16ded8d3-6812-43e7-9e86-3dc84b15b58c)

baserCMS version : 5.0.7-dev

**Comment by ryuring** [comment]
いろんなところで統一されていない様子。一括置換を検討する。

**Comment by ryuring** [comment]
@HungDV2022 アップロード一覧における削除について、「●●を本当に削除してもいいですか？」に変更お願いします。
