### ISSUE TITLE
固定ページ内などでショートコード Mail.getForm がエラーになる

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2915]
## 概要

固定ページにショートコード [ Mail.getForm 1 ] という感じでメールフォームを呼び出そうとすると、エラーになるようです。

※ settings.phpにショートコードの設定やHelper自体はあるのけど、固定ページやLayout、elementなどメールフォーム以外の箇所でMailヘルパーがうまく読みこめてない感じがします。

<img width="1101" alt="スクリーンショット 2023-12-04 21 04 33" src="https://github.com/baserproject/basercms/assets/310333/d5955d0f-8c7f-4b41-b431-eb73a5a624a4">

<img width="705" alt="スクリーンショット 2023-12-04 21 04 23" src="https://github.com/baserproject/basercms/assets/310333/714ccdd4-d1e9-4579-9476-8337354a177f">

<img width="1333" alt="スクリーンショット 2023-12-04 21 05 04" src="https://github.com/baserproject/basercms/assets/310333/30ab4384-cc1a-41d8-b030-98c3e9c941e3">

baserCMS version :  5.0.7

**Comment by ryuring** [comment]
@kaburk こちら、CakePHPから、requestActionがなくなってしまったため、なかなか苦戦しましたが、なんとか対応できました。
