### ISSUE TITLE
$this->BcBaser->pageが動作していない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2916]
## 概要
Layoutやelementなどで$this->BcBaser->page('/urlhoge')とかで別の固定ページを呼び出すとエラーになるようです。
baserCMS5系になって固定ページの内部動作仕様が変わっていることが原因かと思われます。

<img width="1017" alt="スクリーンショット 2023-12-04 21 49 00" src="https://github.com/baserproject/basercms/assets/310333/ca71cfbb-893e-46a0-b94e-cba816f14701">

<img width="1327" alt="スクリーンショット 2023-12-04 21 50 00" src="https://github.com/baserproject/basercms/assets/310333/b927f9ee-7f18-40c4-8257-059bb0d98ead">

baserCMS version : 5.0.7

**Comment by ryuring** [comment]
@kaburk 移行できてなかったので移行しました。
