### ISSUE TITLE
baserCMS5をサブフォルダに設置した際に発生したバグについてです

### ISSUE THREAD

**Issue by shosinnshasann** [baserproject/basercms#2920]
## 概要
Issueの概要を What・Why も含めて書きます。

baserCMS version : 5.0.7
 
baserCMS5を利用させて頂き、感謝しております

バグの報告です

baserCMS5をサブフォルダに設置しております

(さくらサーバーで使用しております)

その際、ブログのカレンダの日付のリンクをクリックすると

https://▲▲▲▲▲.sakura.ne.jp/●●●●●/●●●●●/news/archives/date/2023/12/1

のように、サブフォルダ名が二重に並び、表記エラーとなります

同様に年別アーカイブでも

https://▲▲▲▲▲.sakura.ne.jp/●●●●●/●●●●●/news/archives/date/2023

月別アーカイブ一も同じく

https://▲▲▲▲▲.sakura.ne.jp/●●●●●/●●●●●/news/archives/date/2023/11

と二重に並び、エラーとなります

ご対処頂けますと、幸いです

**Comment by ryuring** [comment]
@shosinnshasann バグフィックスのご協力ありがとうございます。

確認したところ、一般的な環境では再現できないようですので、調査が必要となります。
お手数ですが、以下の情報をお教えいただけますでしょうか。

1. フォルダの階層
サブフォルダに設置しているということですが、サブフォルダが何回層になっているか教えてください。
/sub/ ・・・1階層
/sub/sub/ ・・・2階層

2. baseの確認
テンプレートのどこかに次のコードを貼り付けてどう表示がでるか教えてください。
```php
var_dump($this->getRequest()->getAttribute('base'));
```

**Comment by eucreate** [comment]
現在、ローカル環境のWindows Xampp PHP8.1で、サブフォルダに設置してVer5.0.10で構築中で、同様の現象になっております。

> 1.フォルダの階層
> サブフォルダに設置しているということですが、サブフォルダが何回層になっているか教えてください。
> /sub/ ・・・1階層
> /sub/sub/ ・・・2階層

私の場合は
/base/ ・・・1階層
で設置しています。

> 2.baseの確認
> テンプレートのどこかに次のコードを貼り付けてどう表示がでるか教えてください。
> 
> `var_dump($this->getRequest()->getAttribute('base'));`

`D:\vhosts\basercms.example.com\web\base\plugins\BcThemeSample\templates\element\top_info.php:32:string '/base' (length=5)`

ご参考になれば幸いです。

**Comment by ryuring** [comment]
@eucreate 
`$this->getRequest()->getAttribute('base')` の出力結果は問題ありませんでした。

ただ、どうしても再現することができません。（こちらの環境では正常なリンクとなります）

`plugins/baser-core/src/Service/ContentsService.php` の845行目あたりに、次の行があるのですが、変更した上で、年別アーカイブのタイトルの上に表示される出力結果を教えて頂くことはできますか？

```php
$url = Router::url($url);
↓
var_dump($url);
$url = Router::url($url);
var_dump($url);
```

**Comment by ryuring** [comment]
@eucreate ちなみに、こちらの環境では、/base/sub というフォルダ配下内にて動作確認をしており、次のような出力結果となります。

```
/var/www/html/base/sub/plugins/baser-core/src/Service/ContentsService.php:845:string '/news/' (length=6)
/var/www/html/base/sub/plugins/baser-core/src/Service/ContentsService.php:847:string '/base/sub/news/' (length=15)
```

これが正しい出力結果です。

**Comment by eucreate** [comment]
@ryuring 
> `plugins/baser-core/src/Service/ContentsService.php` の845行目あたりに、次の行があるのですが、変更した上で、年別アーカイブのタイトルの上に表示される出力結果を教えて頂くことはできますか？
> 
> ```
> $url = Router::url($url);
> ↓
> var_dump($url);
> $url = Router::url($url);
> var_dump($url);
> ```

> ちなみに、こちらの環境では、/base/sub というフォルダ配下内にて動作確認をしており、次のような出力結果となります。
> 
> ```
> /var/www/html/base/sub/plugins/baser-core/src/Service/ContentsService.php:845:string '/news/' (length=6)
> /var/www/html/base/sub/plugins/baser-core/src/Service/ContentsService.php:847:string '/base/sub/news/' (length=15)
> ```
> これが正しい出力結果です。

出力結果は
```
D:\vhosts\basercms.example\web\base\vendor\baserproject\baser-core\src\Service\ContentsService.php:845:string '/news/' (length=6)
D:\vhosts\basercms.example\web\base\vendor\baserproject\baser-core\src\Service\ContentsService.php:847:string '/base/news/' (length=11)
```
となりました。

**Comment by ryuring** [comment]
@eucreate 原因がわかりましたので、修正を入れいています。
https://github.com/baserproject/basercms/commit/d83ef14d0e44ae0c0ef404baa21a633a904da132

問題解決のご協力ありがとうございました。
