### ISSUE TITLE
管理画面URLを /baser/admin から別の文字にすると、ログイン画面、ログアウト処理がリダイレクトループする

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2925]
## 概要

セキュリティ対策の為、管理画面のURLを変更しようとして .env の BASER_CORE_PREFIX、ADMIN_PREFIX を baser、admin から別の文字にすると、ログイン画面、ログアウト処理がリダイレクトループしてしまうようです。

一旦ログインしている状態で変更すると管理画面は正常動作している感じだったので、ログインログアウトまわり何かありそうです。

<img width="554" alt="スクリーンショット 2023-12-07 14 40 14" src="https://github.com/baserproject/basercms/assets/310333/5a7c1054-6895-4fe7-9f52-782da2aaddab">
<img width="973" alt="スクリーンショット 2023-12-07 14 41 14" src="https://github.com/baserproject/basercms/assets/310333/f17a6074-b09d-4315-afb5-036866f97e37">

baserCMS version : 5.0.7

**Comment by ryuring** [comment]
@kaburk なおしておきました
