### ISSUE TITLE
webroot内のシンボリックリンクが絶対パスになっているのを相対パスにしたい

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2926]
## 概要
プラグインやテーマをインストールすると、webrootフォルダ内にプラグインやテーマフォルダ内のwebrootへのシンボリックリンクが作成されるのですが、これが絶対パスになっているようで、ローカルで構築→サーバへファイルをアップという時に、パス位置が変わりCSSなどにアクセスできずスタイル全滅となったりします。

サーバアップ時にパス変わると思うのでほぼシンボリックリンクは全部作成し直しする必要があるので、相対パスにしたいです。

それか絶対パスにする仕様が変更できない場合は、自動で一括で張り替えてくれる機能（管理画面の機能、シェルスクリプトなどなど）があれば良いかと思います。（一定の名前の変換ルールもあるようですので、、、）

現状の例（/Volumes/Projects/basercms5にbaserCMS5を設置）

<img width="1005" alt="スクリーンショット 2023-12-07 17 18 38" src="https://github.com/baserproject/basercms/assets/310333/9c2a3a11-d65e-41e0-b63c-c34b48f8a1a9">

上記の理想系

<img width="1039" alt="スクリーンショット 2023-12-07 17 18 50" src="https://github.com/baserproject/basercms/assets/310333/96ec5f2b-7c21-40dc-9716-674c07ad97b3">

手作業で相対パスに変えても動作している感じかと思いますのでご検討ください。

baserCMS version :  5.0.7

**Comment by kaburk** [comment]
@ryuring 

> docker exec -it bc-php /bin/bash
> bin/cake plugin assets symlink

なるほど、cakeのコマンドあるんですね！

https://baserproject.github.io/5/operation/move_to_another
にそってサーバにアップしていたので気が付きませんでした。
そっちの方にも記載が必要そうですね。
ただ、サーバによってSSH使えない時に困りそうなんで、やはりGUIが欲しいかもですねー。

**Comment by ryuring** [comment]
@kaburk こちらに記載お願いしてもいいですか？
https://baserproject.github.io/5/operation/move_to_another

**Comment by kaburk** [comment]
https://github.com/baserproject/baserproject.github.io/pull/116
マージされたみたいでしたのでクローズします！
