### ISSUE TITLE
固定ページ オプション欄のアイキャッチが保存されない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#2927]
## 概要

固定ページ オプション欄のアイキャッチが保存されないようです。
環境依存かとも思いましたので、Docker、MAMPそれぞれで試してみましたが保存されていないようでした。

<img width="1348" alt="スクリーンショット 2023-12-07 20 29 16" src="https://github.com/baserproject/basercms/assets/310333/a94dc73b-ae8e-44e1-8849-a7345fc63468">
<img width="1352" alt="スクリーンショット 2023-12-07 20 29 28" src="https://github.com/baserproject/basercms/assets/310333/0e6a6fb0-5a7a-4367-898a-1a5f7a892df2">
<img width="1348" alt="スクリーンショット 2023-12-07 20 29 35" src="https://github.com/baserproject/basercms/assets/310333/ea38c86d-b723-4b09-92a8-2fc86863007a">
<img width="1351" alt="スクリーンショット 2023-12-07 20 29 44" src="https://github.com/baserproject/basercms/assets/310333/1c39d103-4e4e-455d-ab41-7348c58dbecb">

ファイルとDB両方空のようです。

<img width="504" alt="スクリーンショット 2023-12-07 20 32 41" src="https://github.com/baserproject/basercms/assets/310333/e27b4ad2-a66f-4665-af16-17800007bb20">
<img width="1097" alt="スクリーンショット 2023-12-07 20 31 07" src="https://github.com/baserproject/basercms/assets/310333/b682614c-5668-4cf1-8f4f-8c31b9c9663f">

エラーログなどログが出なくてちょっと保存されない理由が不明でした。

<img width="470" alt="スクリーンショット 2023-12-07 20 35 48" src="https://github.com/baserproject/basercms/assets/310333/d0c03978-f51e-4bd6-859e-5d7334c5fcb0">

ただ、ブログ設定のアイキャッチなども同様だったのでcontentsテーブルの保存処理あたりが怪しそうです。

baserCMS version :  5.0.7

**Comment by ryuring** [comment]
@kaburk 問題自体は解決しましたが、仕様的な課題が残っているためオープンします。

@seto1 こちらの件ですが、以前、`BcFileUploader` に、`_bc_upload_id` をエンティティに組込処理があったと思いますが、その際、エンティティの `$_accessible` プロパティに、`*` または、`_bc_upload_id` を明示していないと、配列をエンティティ化する際に、消えてしまうようです。

仕様的にわかりにくいので、他にいい方法ないですかね？？

**Comment by seto1** [comment]
@ryuring なるほど... ブログ記事のアイキャッチしか動作確認できてませんでした。

未検証ですがぱっと思いついたのは以下です。
Bが実現性が高そうです。

- A. BcUploadBehaviorからエンティティの_accessibleに動的に_bc_upload_idを追加する
    - エンティティに変更を加える方法が問題
        - beforeMarshalから$event->getSubject()->getEntityClass()やsetEntityClass?
- B. BcUploadBehaviorのbeforeMarshalからafterMarshalに一時変数使って_bc_upload_idを渡す
- C. リクエストデータやエンティティに_bc_upload_idをもたせるのをやめる
    - その場合はキーにする値が問題
        - 更新時はidを使えるが作成時はidが存在しない

**Comment by ryuring** [comment]
@seto1 悩ましいですね

- A：_accessible へ外部から介入するのが気持ち悪い
- B：バグ生みそう
- C：そもそもの問題

実行時というより実装時の問題なので、実装時に、_bc_upload_id にアクセスできるようになってなかったら例外投げるってのはどうでしょう？

「ファイル保存対象のエンティティについて、_bc_upload_id フィールドをアクセスできるようにしてください。」など

**Comment by seto1** [comment]
@ryuring あまりルールは増やしたくないですね...

BcUploadBehavior->beforeMarshal に以下の変更を加えると対応できそうなのですがいかがでしょう。

- 引数追加
    - `ArrayObject $options`
- 一行追加
    - `$options['accessibleFields']['_bc_upload_id'] = true;`

**Comment by ryuring** [comment]
@seto1 おー、マジっすか、それでいけるなら一番良さそうですね。お手隙でいいのでお願いしていいですか
