### ISSUE TITLE
【ウィジェットエリア】新規登録　スペースが登録できてしまう

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2946]
## 概要
ウィジェットエリア：新規登録でウィジェットエリア名にスペースが登録できてしまう。

![スクリーンショット 2023-12-15 12 26 08](https://github.com/baserproject/basercms/assets/84309553/bffc06a6-55b4-4df5-8622-7f107ed5991e)

baserCMS version :  5.0.7-dev

**Comment by ryuring** [comment]
@nghiem-mb Xin vui lòng !

**Comment by rabbitchang** [comment]
@ryuring 
すみません！同じ現象がアップロードカテゴリ一覧の新規追加でも起こりました！
ご確認よろしくお願いします！

**Comment by ryuring** [comment]
@rabbitchang ありがとうございます！
別途、issue作ってくださいー

**Comment by ryuring** [comment]
@HungDV2022 こちら空文字が登録できないようにバリデーションの実装をお願いします。
dev-5 でお願いします。

**Comment by HungDV2022** [comment]
https://github.com/baserproject/basercms/pull/2989
こちらコミットで修正しました。
確認お願いします。

**Comment by ryuring** [comment]
@HungDV2022 ありがとうございました、クローズします。
