### ISSUE TITLE
アップロード管理：アップロードカテゴリ新規登録　スペースが登録できてしまう

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2947]
## 概要
https://github.com/baserproject/basercms/issues/2946
↑こちらと同じ現象

アップロードカテゴリ新規登録でカテゴリ名にスペースが登録できてしまう。

baserCMS version : 5.0.7-dev

**Comment by ryuring** [comment]
@HungDV2022 空文字が登録できないように dev-5 でバリデーションの実装をお願いします。
