### ISSUE TITLE
【メール基本設定】各項目にスペースが登録できてしまう

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2951]
## 概要
プラグイン管理→メール基本設定で各項目にスペースが登録できてしまう。

![スクリーンショット 2023-12-18 12 23 02](https://github.com/baserproject/basercms/assets/84309553/7b0fb8bf-f1af-41ae-a49b-3d6f213c0c75)

baserCMS version : 5.0.7-dev

**Comment by ryuring** [comment]
空文字が登録できないように dev-5 でバリデーションを実装お願いします。 @HungDV2022
