### ISSUE TITLE
アップローダープラグイン設定：数字以外の文字＆マイナスが登録できてしまう

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#2954]
## 概要
アップローダープラグイン設定：数字以外の文字＆マイナスが登録できてしまう。画像参照下さい。

保存した後の状態↓

![スクリーンショット 2023-12-18 15 55 03](https://github.com/baserproject/basercms/assets/84309553/e24523ce-f047-4fe1-adc0-8eadb82f6234)

**この影響でファイルアップロードができなくなります。**

baserCMS version : 5.0.8-dev

**Comment by ryuring** [comment]
@HungDV2022 数値のバリデーションを追加してください。
KeyValueBehaviorを利用しているので、`validationDefault` ではなく `validationExpanded` を定義して、保存前にチェックするようにしてください。
