### ISSUE TITLE
コンテンツ管理で固定ページを複製するとタイトルが消えて_copyだけのタイトルになってしまう

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3009]
## 概要
コンテンツ管理で固定ページを複製してタイトルを変更しないと元のタイトルが消えて_copyだけになってしまうようです。

<img width="705" alt="スクリーンショット 2024-01-04 19 06 07" src="https://github.com/baserproject/basercms/assets/310333/34df1551-571a-45db-a2cb-d2e0b0e687ba">
<img width="649" alt="スクリーンショット 2024-01-04 19 06 15" src="https://github.com/baserproject/basercms/assets/310333/0d43b433-92cd-49f5-b266-0c3f9568f298">
<img width="754" alt="スクリーンショット 2024-01-04 19 06 25" src="https://github.com/baserproject/basercms/assets/310333/b6564c4d-e3b9-42f6-b5ee-3e74f5ba012e">
<img width="692" alt="スクリーンショット 2024-01-04 19 06 32" src="https://github.com/baserproject/basercms/assets/310333/1a0b5b40-0507-4b22-8498-540fc2f68c8d">

baserCMS4系の場合は元のタイトル＋のコピーという形になってましたので、挙動をあわせておいた方が良さそうです。
<img width="688" alt="スクリーンショット 2024-01-04 19 23 52" src="https://github.com/baserproject/basercms/assets/310333/ce75277b-264a-44bf-8824-5ab437ab8dc2">
<img width="914" alt="スクリーンショット 2024-01-04 19 28 17" src="https://github.com/baserproject/basercms/assets/310333/4c13910f-4e4e-4f3b-8c53-42f6e7aa0296">

baserCMS version : 5.0.7,  5.0.8-dev

**Comment by ryuring** [comment]
@kaburk 報告ありがとうございます。こりゃ良くないですね。余力できたら調査お願いしてもいいですか？
