### ISSUE TITLE
[新規カテゴリ登録]カテゴリ名エラーメッセージの記載ミスがある

### ISSUE THREAD

**Issue by matsunaga-y** [baserproject/basercms#3018]
## 概要
[新規カテゴリ登録]カテゴリ名エラーメッセージの記載ミスがある
<img width="1195" alt="スクリーンショット 2024-01-10 16 04 33" src="https://github.com/baserproject/basercms/assets/144435709/4c9a2381-366c-424d-8ac3-b3bdc142147b">
カテゴリ名はは半角英数字とハイフン、アンダースコアのみが利用可能です。
の「は」が２つ記載されています。

baserCMS version : 5.0.8-dev
 
## 備考
ヘルプに「半角のみで入力してください」とありますが、エラーメッセージと同じく「半角英数字とハイフン、アンダースコアのみが利用可能」と記載されているとわかりやすいと思いました。（記号も一部使えると思っていなかったので）

**Comment by ryuring** [comment]
@matsunaga-y 報告ありがとうございます。確かにそうですね。
@katokaisya こちら調整お願いしてもいいですか？

**Comment by seto1** [comment]
以下の変更と合わせて対応しました。

> alphaNumericDashUnderscore削除
https://github.com/baserproject/basercms/pull/3042/files#diff-ebe7ff52735475049b793a8e1cab5a3f47226111cb4fe4a7c603bad1dd395806
