### ISSUE TITLE
ViewEventListenerにて管理画面だと header, footer などのイベントが発生しない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3021]
## 概要

管理画面のレイアウト
plugins/bc-admin-third/templates/Admin/layout/default.php
を確認すると、

$this->BcBaser->element('header')
this->fetch('content')
$this->BcBaser->element('footer')

となっているので、BcBaserヘルパーの関数内でイベント発火しているので、

$this->BcBaser->header()
$this->BcBaser->content()
$this->BcBaser->footer()

を使うようにすると良さそうです。

baserCMS version : 5.0.7

**Comment by ryuring** [comment]
@kaburk なるほど、その方向でお願いします！
