### ISSUE TITLE
データベースのフィールド名に key という名称が使われていると insert に失敗する

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#3037]
## 概要
PetitCustomFieldのデータをデータメンテナンスでレストアしようとしたところ insert が失敗してしまう。
key は、MySQLの予約語らしく、バッククォートで囲まないと Syntax Error となってしまう。
CakePHP側の問題の可能性あり。

baserCMS version : 5.0.7

**Comment by seto1** [comment]
@ryuring `option` というカラム名で同様の現象が起きたことがあります。
その際は `param` に変更して対応しました。

バッククォートを使わなくなったのはパフォーマンス面で問題があるためのようです。

- [CakePHP3のfindではバッククォートが使われない対応](https://kojirooooocks.hatenablog.com/entry/2018/08/31/003434)
- [引用識別子](https://book.cakephp.org/4/ja/orm/database-basics.html#identifier-quoting)

> デフォルトのCakePHPでは、生成されるSQL文は引用符で囲まれていません。その理由は、引用識別子はいくつかの問題があるためです。
> パフォーマンスへの負荷 - 引用符を使うと、使わない時よりずっと遅く、複雑になります。
> ほとんどの場合に不要 - CakePHP の規約に従う新しいデータベースでは、引用符で囲む必要はありません。

**Comment by ryuring** [comment]
@seto1 おおお！素晴らしい！その情報が欲しかったです。
移行ガイドに後で記載しておきます。

**Comment by ryuring** [comment]
こちらに記載しましたのでクローズします。
https://baserproject.github.io/5/migration_db_from_ver4
