### ISSUE TITLE
【要望】ユーティリティ機能にシンボリックリンク作成機能する問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#3050]
## 概要
 baserCMS5系のプラグイン/webloot （シンボリックリンク）について、
sshが使える環境では
`bin/cake plugin assets symlink`
似て対応が可能だが、
レンサバなどsshが使えない場合、管理画面から再作成できるようにする必要があります。

baserCMSのユーティリティ機能にシンボリックリンク作成機能を作れると良いと思います。

**Comment by ryuring** [comment]
加藤さんこちらレビューしますんでやってみましょう。 @katokaisya
