### ISSUE TITLE
コンテンツ管理でブログ、メールフォームをコピーするとエラーが発生する

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3058]
## 概要
コンテンツ管理にてブログ、メールフォームを右クリックメニュー→コピーで複製するとエラーになるようです。

ブログの場合
<img width="1482" alt="スクリーンショット 2024-01-22 16 15 37" src="https://github.com/baserproject/basercms/assets/310333/4d98101a-ebbe-42d5-aa28-cbbb24aeff85">

メールフォームの場合
<img width="1461" alt="スクリーンショット 2024-01-22 16 15 51" src="https://github.com/baserproject/basercms/assets/310333/a67f8a5e-e1d6-4100-baba-573d90c295da">

baserCMS version : 5.0.7, 5.0.8-dev

**Comment by ryuring** [comment]
@kaburk 悲しす

**Comment by matsunaga-y** [comment]
5.0.9-devでも同様です。
