### ISSUE TITLE
【メールフォーム】インストール時にDBのプレフィックスありで作成した環境だと追加したメールフォームが正常動作しない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3064]
## 概要
インストール時にプレフィックスありで作成した環境だと管理画面で追加したメールフォームのmail_message テープルがプレフィックスなしで生成されてしまうようです。（DBがmysqlの場合に現象を確認、それ以外のDBは未確認です。）

※ あと、インストール直後にメールフォームが１つしかないけど、mysite_mail_message_1, mysite_mail_message_2 のように２つ生成されている点も気にはなります・・・。

インストール直後(プレフィックスはmysite_)
<img width="1460" alt="スクリーンショット 2024-01-22 18 34 17" src="https://github.com/baserproject/basercms/assets/310333/c5b07f40-1aaf-4c7b-9637-2be30c37662c">

管理画面よりメールフォーム作成
<img width="1116" alt="スクリーンショット 2024-01-22 18 36 37" src="https://github.com/baserproject/basercms/assets/310333/e3733fca-fa9a-46d7-a70a-da4df1b85508">

プレフィックスなしmail_message_2が生成される
インストール時にmysite_mail_message_2ができていたので管理画面上はフィールドなど追加できるが、
mail_message_2にフィールドが足されてメールフォームでDBに送信データが保存できない
<img width="1471" alt="スクリーンショット 2024-01-22 18 36 47" src="https://github.com/baserproject/basercms/assets/310333/01d85dfd-299e-46be-89b0-fed2f4fab0d5">

管理画面よりもう一つメールフォーム作成
<img width="1042" alt="スクリーンショット 2024-01-22 18 37 03" src="https://github.com/baserproject/basercms/assets/310333/45ca0cd0-5dbf-489d-bd6f-45bd15af0a2a">

プレフィックスなしmail_message_3が生成される
<img width="1464" alt="スクリーンショット 2024-01-22 18 37 15" src="https://github.com/baserproject/basercms/assets/310333/16358fc3-24bc-49b9-90ca-33f37b2040b8">

メールフィールドなど追加できない（エラー発生）
<img width="1680" alt="スクリーンショット 2024-01-22 18 48 53" src="https://github.com/baserproject/basercms/assets/310333/87dc0b88-a83c-41b7-b7ce-ff204cb304e9">

baserCMS version : 5.0.8-dev

**Comment by ryuring** [comment]
@kaburk インストール時はマイグレーションファイルから作成しているので、ファイルを削除するだけで解消しそうです。
インストール後は、テーブル名の生成処理を調整すると解消できそうですね。
