### ISSUE TITLE
【テーブル編集】フィールドを追加すると増殖していく

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#3078]
## 概要
【テーブル編集】
利用できるフィールドを利用中のフィールドに追加していくと、1回目は1個、2回目は2個、3回目は3個に増殖していく。（動画参照ください）

https://github.com/baserproject/basercms/assets/84309553/8694a20a-b1a2-45c2-bc7a-3bef6eaa2dde

baserCMS version : 5.0.9-dev

**Comment by ryuring** [comment]
こちらのコミットで解消
https://github.com/baserproject/basercms/commit/e6267d802684930ea399672700df55c3a34b395e
