### ISSUE TITLE
【カスタムコンテンツ】フィールド名部分の不具合

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#3079]
## 概要
【利用中のフィールド】
フィールド名にスペースが登録できてしまう。＆フィールド名が長くなるとレイアウトが崩れてしまう。

https://github.com/baserproject/basercms/assets/84309553/51c74fad-1920-44dc-a194-c5463ecf2bd1

baserCMS version : 5.0.9-dev

**Comment by ryuring** [comment]
@HungDV2022 こちら対応お願いします。

**Comment by HungDV2022** [comment]
@ryuring 

> フィールド名が長くなるとレイアウトが崩れてしまう

こちらの対応方法は文字列の長さを制限するのか、CSSが崩れないように調整するのか、どうちのほうがいいですか。

**Comment by HungDV2022** [comment]
> CSSが崩れないように調整

こちらは文字列の長さは255まで制限しましたのでCSSが崩れないように調整しました。確認お願いします。

**Comment by ryuring** [comment]
@HungDV2022 スクリーンショットを見せてください

**Comment by HungDV2022** [comment]
![スクリーンショット 2024-04-22 12 49 20](https://github.com/baserproject/basercms/assets/110375578/1f1b9eb7-1da0-4332-8750-0854ed1939fb)
スペースだけ入力する場合、

**Comment by HungDV2022** [comment]
![スクリーンショット 2024-04-22 12 50 59](https://github.com/baserproject/basercms/assets/110375578/77f48ade-0571-4e24-bde1-153a79c0813a)
フィールド名が長くなる場合。
@ryuring こちらです。確認お願いします。

**Comment by ryuring** [comment]
@HungDV2022 `overflow:hidden` でお願いします。

**Comment by HungDV2022** [comment]
<img width="1434" alt="スクリーンショット 2024-04-23 7 56 26" src="https://github.com/baserproject/basercms/assets/110375578/32be2989-467e-4a6c-befc-5d9b4329349c">
こちらです。大丈夫ですか。
@ryuring https://github.com/baserproject/basercms/pull/3366

**Comment by ryuring** [comment]
@HungDV2022 ありがとうございます。大丈夫です。
