### ISSUE TITLE
【ブログ設定編集画面】アイキャッチ画像サイズの不具合

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#3081]
## 概要
アイキャッチ画像サイズ：数値チェックになってしまっていてマイナスや小数点のものが入力できてしまいます。

![スクリーンショット 2024-02-05 11 22 07](https://github.com/baserproject/basercms/assets/84309553/b4c7080a-50c1-4f11-aba5-11ab5c2e3383)

baserCMS version : 5.0.9-dev

**Comment by ryuring** [comment]
マイナスはすでに対応済です。
小数点は入力できてしまいますが、許容します。
