### ISSUE TITLE
【カスタムコンテンツ】「関連データ」を設定しても関連先フロントではタイトルしか取得できない問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#3084]
## 概要
カスタムコンテンツの「関連データ」を設定しても
`$this->BcBaser->getCustomFieldValue($customEntry, 'フィールドname');`
で、フィールド編集で設定したカスタムテーブルの「タイトル」しか取得できない。
Front側にて$customEntry変数にセットされている形跡もないです。

baserCMS version : 5.0.8

**Comment by ryuring** [comment]
@HungDV2022 こちら実装お願いします。
