### ISSUE TITLE
composer install で失敗する問題

### ISSUE THREAD

**Issue by ibananlife** [baserproject/basercms#3137]
ユーザーズフォーラムに登録できませんでしたのでこちらへ(アクティベーションメールが送られてきません、アクティベーションメールの再送を何度か試しましたが駄目でした gmail のアドレスです。迷惑メールも確認しました。)

 https://forum.basercms.net/t/topic/1215/8

この問題は、ひょっとすると Xdebug が無効になっている PHP 環境の問題だと思われます。

- Ubuntu 20.04
- Server version: Apache/2.4.41 (Ubuntu)
- PHP Version 8.2.15
- basercms-5.0.8.zip (使用パッケージ)

上記のローカル環境で Xdebug を無効にした場合に、質問者と同じエラーメッセージで composer install (ライブラリのインストール) が失敗します。

Xdebug を有効にして再度インストール作業を行うと正常にインストールを完了しました。

いくつかの共用レンタルサーバーでは Xdebug が無効になっている場合があると思われます。

ご参考までに。

**Comment by ryuring** [comment]
@ibananlife 報告ありがとうございます。ちと確認してみますね。

**Comment by ryuring** [comment]
@ibananlife  再現しました。解決方法もわかったので改善します。

**Comment by ryuring** [comment]
アクティベーションメールの件も運営に伝えて調査中です。少しおまちください @ibananlife
