### ISSUE TITLE
【プラグイン管理】管理画面からプラグインをアップロードできない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3140]
## 概要

管理画面 プラグイン一覧の新規追加ボタンからプラグインをアップすると処理は正常終了したメッセージが表示されるが、正しくインストールされないようです。

例

Banner-5.0.0.zip
(フォルダ名Banner/)

<img width="956" alt="スクリーンショット 2024-02-21 10 56 54" src="https://github.com/baserproject/basercms/assets/310333/d9039a40-b892-42c0-bff4-3b5784eb0372">

管理画面から新規追加

<img width="832" alt="スクリーンショット 2024-02-21 10 54 43" src="https://github.com/baserproject/basercms/assets/310333/2d8d1d49-220f-4f92-abac-4a32d1b3ef1f">

新規プラグイン「Banner-5.0.0」を追加しました。と出るが一覧にない

![Screenshot 2024-02-21 at 10-54-57 プラグイン一覧](https://github.com/baserproject/basercms/assets/310333/b00221ef-e98d-4142-ad06-aeb3eaea1a99)

tmpフォルダ内には残っているみたいなので、zip解凍はできているがpluginsフォルダに移動できていない感じのようです。

<img width="707" alt="スクリーンショット 2024-02-21 11 01 04" src="https://github.com/baserproject/basercms/assets/310333/c66a7899-619d-49af-90f6-414672b2a48a">

試しに、

Banner.zip
(フォルダ名Banner/)

とすると正しくインストールできるようでした。

インストール処理内でZIP内フォルダ名ではなくZIPファイル名で判別してしまっている感じなので、
baserCMS4系以前の動作にあわせてアーカイブ内フォルダ名で判別する必要がありそうです。

確認していませんが、おそらくテーマも同様な状態ではないかと思います。

baserCMS version :  5.0.8, 5.0.9-dev

**Comment by kk-uchino** [comment]
@ryuring 
承知しました！

**Comment by seto1** [comment]
プラグインとテーマどちらも対応済みのためクローズします。
https://github.com/baserproject/basercms/commit/02fb2787ebc3cbd2c82365fefb775f85af619e4b
https://github.com/baserproject/basercms/commit/dc567b92817f5b7ec6dc86c1c951ab75102e85e3
