### ISSUE TITLE
アクセスルールグループ編集画面で保存ができない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3171]
## 概要
アクセスルールグループ編集画面で編集時に画面上エラーがない状態ですが「 入力エラーです。内容を修正してください」となって保存できないようです。

<img width="1235" alt="スクリーンショット 2024-02-27 18 42 14" src="https://github.com/baserproject/basercms/assets/310333/67cc83ef-1858-4a83-8961-1ffacac30414">

ダンプしてみると、URLのバリデーションに引っかかっているっぽいです。
<img width="1076" alt="スクリーンショット 2024-02-27 18 45 12" src="https://github.com/baserproject/basercms/assets/310333/847b424e-82df-49ab-a915-ca1e5c3874e2">

<img width="1680" alt="スクリーンショット 2024-02-27 18 44 58" src="https://github.com/baserproject/basercms/assets/310333/8c9a11b6-3a4c-4dd9-abab-d917d64620cd">

baserCMS version :  5.0.11-dev

**Comment by ryuring** [comment]
@kaburk うぉ、、、 @seto1 さんのコミットが影響してるみたい、テストないと気付けないですね、、、

**Comment by ryuring** [comment]
@kaburk urlがない場合のテストを追加しておきました　https://github.com/baserproject/basercms/commit/bf0dd9a4f520eb5d13812c1c6c242125be5bf002

**Comment by kaburk** [comment]
@ryuring ありがとうございます！
