### ISSUE TITLE
テーマの初期データ読込を行うとコンテンツ管理の作成日が空欄になる

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3183]
## 概要

テーマの初期データ読込を行うとコンテンツ管理の作成日が空欄になるようです。

BcThemeSample：初期データ読込後のcontentsテーブル
![スクリーンショット 2024-02-29 11 08 51](https://github.com/baserproject/basercms/assets/310333/463bdb83-a0b0-4425-9a1a-e1f292a09368)

BcColumn：初期データ読込後のcontentsテーブル
![スクリーンショット 2024-02-29 11 09 18](https://github.com/baserproject/basercms/assets/310333/16b87a39-4120-4483-8de4-06857f5963fe)

上記の状態でそのまま固定ページなど編集して保存すると入力エラーになるのですが
オプション欄の中で隠れてエラーが表示されていてどこが入力エラーなのか気づけない状態になってしまいました。
（これはこれでUI的にどこがエラーなのかわかりにくいので別の問題ではありますが…）

![スクリーンショット 2024-02-29 11 09 53](https://github.com/baserproject/basercms/assets/310333/e26d42b2-bfb5-4e30-803d-ad74bba4ff87)

![スクリーンショット 2024-02-29 11 10 02](https://github.com/baserproject/basercms/assets/310333/720af9b0-f210-4fed-94df-a5b27a693725)

ちなみに、初期インストール時は作成日は正常に入っている状態でした。

インストール直後：contentsテーブル
![スクリーンショット 2024-02-29 11 08 21](https://github.com/baserproject/basercms/assets/310333/deb11f84-5f92-4d93-8ebf-06e74a2f41c2)

baserCMS version :  5.0.11-dev

**Comment by kaburk** [comment]
ブログの投稿日なども同じ状態でした。
テーマの初期データに日付が入っていないのが原因のようです。

**Comment by kaburk** [comment]
インストール時は Contentsテーブル created_date、BlogPostsテーブルのpostedを追加で更新する処理が入っているので、
初期データ読み込み時も同じようにするか、初期データに予め日付を入れておく感じですかね、、、

**Comment by ryuring** [comment]
@kaburk ちょっと後で細かく見てみますね
