### ISSUE TITLE
News 記事の本文が保存されない問題

### ISSUE THREAD

**Issue by ibananlife** [baserproject/basercms#3189]
ユーザーズフォーラムに登録できませんでしたのでこちらへ(アクティベーションメールが送られてきません、アクティベーションメールの再送を何度か試しましたが駄目でした gmail のアドレスです。迷惑メールも確認しました。)

上記の状態のままなのでこちらへ

- Ubuntu 20.04
- Server version: Apache/2.4.41 (Ubuntu)
- PHP Version 8.2.15
- Xdebug: enabled
- mysql  Ver 15.1 Distrib 10.3.39-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- basercms-5.0.10.zip (使用パッケージ)

上記のローカル環境で実行しました。

新規インストール作業を普通にデフォルトのまま完了しました。

インストール完了画面からダッシュボードへ移動しました。

そのまま News >> 記事 >> 新規記事追加 画面へ

NEWS｜新規記事登録 フォームで「タイトル」と「概要」と「本文」のみを入力して「公開状態を公開」にして「保存」を押しました。

- タイトル: タイトルです
- 概要: 概要です。
- 本文: 本文です。

入力したテキストの内容は上記のとおりです。

問題は、本文に入力したテキストが保存されません。

データベースの blog_posts テーブルの内容を確認すると detail フィールドが空になっています。

プレビュー画面でも本文の値が空になっています。

ちなみに composer.json の "baserproject/baser-core": "5.0.8" と固定してバージョンを現在の 5.0.10 から 5.0.8 にしてインストールしても同じ問題が発生しました。

この現象は私だけですかね？

誰か報告するだろうと放っておいたのですが、一応ご参考までに。

**Comment by ryuring** [comment]
@ibananlife 報告ありがとうございます。ちょっと致命的なものが 5.0.10 で混入してしまったようですね、、、
修正いたしました。早めにリリースするようにしたいと思います。

あと、アクティベーションメールの件、２日前ほどにDMARC の設定をしたという話だったのですが、まだ届かないんですね、、、こちらも確認しておきます。
