### ISSUE TITLE
【カスタムコンテンツ】Wysiwyg エディタ設定の横幅と高さもひらがなや漢字で保存できてしまう

### ISSUE THREAD

**Issue by ryuring** [baserproject/basercms#3196]
## 概要
タイプ：Wysiwyg エディタのWysiwyg エディタ設定の横幅と高さもひらがなや漢字で保存できてしまう

baserCMS version : 5.0.10
 
## TODO
- [ ] BcCcWysiwyg プラグインにて、カスタムフィールドの beforeMarchal イベントを横取り
- [ ] バリデーションを追加する

**Comment by ryuring** [comment]
@HungDV2022 ちょっと確認です。こちら修正完了してますか？

**Comment by HungDV2022** [comment]
@ryuring 
https://github.com/baserproject/basercms/pull/3595/files
こちらPRで対応しています。確認お願いします。
