### ISSUE TITLE
【ファイルアップロード：5.1】BcValidation::fileCheck が動作していない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3202]
ブランチ: dev-5.1

cake5でファイルが配列でなくなったことが原因?
https://github.com/baserproject/basercms/blob/dev-5.1/plugins/baser-core/src/Model/Validation/BcValidation.php#L180

**Comment by ryuring** [comment]
こちらのコミットで解消
https://github.com/baserproject/basercms/commit/1935c273f47e12d786c06a39f55bffb7e6a2680f
