### ISSUE TITLE
BcColumnテーマのブログ記事詳細にてコメントが送信できない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3212]
## 概要
テーマをBcColumnに設定するとブログのコメント機能を有効化していても、ブログ記事詳細画面にてコメント送信ボタンが表示されないようです。

<img width="1441" alt="スクリーンショット 2024-03-07 19 10 55" src="https://github.com/baserproject/basercms/assets/310333/3ea5a08e-fe75-4177-933d-b15129327516">

コンソール見るとJSのエラー「Uncaught ReferenceError: bcI18n is not defined」が何度か出ているので、その影響かもしれません。
<img width="650" alt="スクリーンショット 2024-03-07 19 11 14" src="https://github.com/baserproject/basercms/assets/310333/f21f2f95-f018-4c15-a9a4-6eebd06acac6">

サンプルテーマ  ( BcThemeSample ) だと問題なく送信ボタンが表示されているので、テーマの組み方か5系化した時の移行漏れではないかと思われます。

<img width="1049" alt="スクリーンショット 2024-03-07 19 18 59" src="https://github.com/baserproject/basercms/assets/310333/88566d2f-d021-4305-834c-bbf3d1712f48">

baserCMS version : 5.0.11-dev

**Comment by ryuring** [comment]
こちら完了しましたのでクローズします。
