### ISSUE TITLE
【お気に入り】お気に入り一覧に別のユーザーのデータまで表示される

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3226]
## 概要
お気に入り一覧に別のユーザーのデータまで表示されてしまうようです。
user_idの絞り込みがうまくできていない感じです。

user_id = 1 (admin) ユーザーの表示
 
<img width="1680" alt="スクリーンショット 2024-03-12 18 25 45" src="https://github.com/baserproject/basercms/assets/310333/6a850d18-4a48-4382-8123-5657bed8ca7b">

user_id = 2 (test) ユーザーの表示

<img width="1680" alt="スクリーンショット 2024-03-12 18 25 55" src="https://github.com/baserproject/basercms/assets/310333/7eae4763-3036-43c5-a8bb-4417524811e7">

データベースの値

<img width="1058" alt="スクリーンショット 2024-03-12 18 24 45" src="https://github.com/baserproject/basercms/assets/310333/5c43b587-a28a-4a4e-a1c7-0c6c1f1417b3">

baserCMS version : 5.0.11

**Comment by ryuring** [comment]
@HungDV2022 こちらの対応をお願いします。

**Comment by ryuring** [comment]
@HungDV2022

 @kaburk がやってくれているみたいです。アサインを切り替えます。

**Comment by kaburk** [comment]
@ryuring @HungDV2022 なんかテストうまくとおらないのとちょっと手一杯なのでお願いできますでしょうか、、、

**Comment by ryuring** [comment]
@kaburk あ、フンさんが今プルリク送ってくれたみたいです。ちょうどよかった。
https://github.com/baserproject/basercms/pull/3228/files
こちらをマージしますね。
@HungDV2022

**Comment by kaburk** [comment]
ありがとうございます！
