### ISSUE TITLE
【サイト内検索】フロントエンド 検索結果画面の表示件数切り替えが動作していない

### ISSUE THREAD

**Issue by kaburk** [baserproject/basercms#3245]
## 概要

検索結果画面の表示件数の切り替えが動作していないようです。

<img width="1402" alt="スクリーンショット 2024-03-15 16 12 58" src="https://github.com/baserproject/basercms/assets/310333/2990dd50-642a-4d9e-9ca1-961f6304e0df">

ソースのリンク先見るとクエリパラメータがない状態でした。
<img width="712" alt="スクリーンショット 2024-03-15 16 14 47" src="https://github.com/baserproject/basercms/assets/310333/4b129724-0a9c-4398-8b54-9b70f816b598">

4系の場合だとクエリパラメータがある
<img width="687" alt="スクリーンショット 2024-03-15 16 14 25" src="https://github.com/baserproject/basercms/assets/310333/99e7dc1f-62e1-4a3f-95be-56b3bf691131">

baserCMS version : 5.0.11

**Comment by ryuring** [comment]
@HungDV2022 こちらお願いしていいですか？
対象のテンプレートは、次になります。
```
plugins/bc-front/templates/element/list_num.php
```

管理画面用の下記のテンプレートを参考に調整をお願いします。
```
plugins/bc-admin-third/templates/Admin/element/list_num.php
```
