### ISSUE TITLE
【カスタムコンテンツ：5.1】フィールド　バリデーション不具合

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#3249]
## 概要

【5.1-dev カスタムコンテンツ：フィールド　タイプ：Eメール】
項目：Eメール比較先フィールド名
→フィールド名なので半角英数字とアンダースコアのみ利用可能のはずが漢字仮名が入力できてしまいます。

![スクリーンショット 2024-03-04 11 05 37](https://github.com/baserproject/basercms/assets/84309553/49e2116f-a00e-44ac-84b4-af52e246b49c)

**Comment by ryuring** [comment]
@HungDV2022 こちらについて、「半角英数字とアンダースコア（ _ ）のみ利用可能」という前提でバリデーションの追加をお願いします。

**Comment by ryuring** [comment]
@HungDV2022 間違えました。「半角小文字英数字とアンダースコア（ _ ）のみ利用可能」という前提でお願いします。

**Comment by ryuring** [comment]
@HungDV2022 こちら meta フィールドで、json となっているため工夫が必要となりそうです。
難しそうだったら他のものを優先したいので教えて下さい。
