### ISSUE TITLE
baserCMS4系  メールフォームで半角変換を有効にしても全角ハイフンが半角ハイフンにならない問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#3275]
## 概要
案件にて、電話番号などをすべて全角でも受け入れるようにしたいという要望あり。
数値ハイフンチェック・桁数チェック・半角変換で、基本的には対応可能ですが、
全角ハイフンだけは、半角変換できないため、数値ハイフンチェックで弾かれてしまいます。
半角変換時に全角ハイフンを半角ハイフン変換できれば、問題が解消できると思います。

baserCMS version : 4.8.0

**Comment by momofff** [comment]
dev-4 ブランチにプルリクエストをマージ済みの為クローズします。
対応ありがとうございました！
