### ISSUE TITLE
【テーマ：BcColumn　dev-5.1】エントリー詳細でエントリー名が二つ表示される

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#3363]
## 概要
テーマ：BcColumn
カスタムコンテンツのエントリー詳細をみにいくと、エントリー名が二つ表示されています。

baserCMS version : 5.1
 
<img width="1138" alt="スクリーンショット 2024-04-19 11 19 59" src="https://github.com/baserproject/basercms/assets/84309553/49c76c44-f4ba-4283-83cb-096c728c52b9">

**Comment by HungDV2022** [comment]
@rabbitchang @ryuring 
https://github.com/baserproject/basercms/pull/3365
こちらコミットで修正しました。確認お願いします。
