### ISSUE TITLE
【baserCMS 5.0.15】エディタ設定の不具合

### ISSUE THREAD

**Issue by ibananlife** [baserproject/basercms#3418]
- Ubuntu 20.04
- Server version: Apache/2.4.41 (Ubuntu)
- PHP Version 8.2.18
- Xdebug: enabled
- mysql  Ver 15.1 Distrib 10.5.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- basercms-5.0.15.zip (使用パッケージ)

上記のローカル環境で実行しました。

新規インストール作業を普通にデフォルトのまま完了しました。

インストール完了画面からダッシュボードへ移動しました。

そのまま 「設定 >> システム基本設定 >> エディタ設定 >> エディタタイプ => なし」を選択して「保存」

### コンテンツ管理 >> コンテンツ >> トップページ >> 編集

```
内部エラーが発生しました
An Internal Error Has Occurred.
エラー: アドレス '/baser/admin/baser-core/pages/edit/1/content_id:4/parent_id:1' に送信されたリクエストは無効です。
```

### コンテンツ管理 >> コンテンツ >> 会社案内 => 編集

```
内部エラーが発生しました
An Internal Error Has Occurred.
エラー: アドレス '/baser/admin/baser-core/pages/edit/2/content_id:5/parent_id:1' に送信されたリクエストは無効です。
```

### コンテンツ管理 >> コンテンツ >> 固定ページ(新しい 固定ページ) => 編集

```
内部エラーが発生しました
An Internal Error Has Occurred.
エラー: アドレス '/baser/admin/baser-core/pages/edit/8/content_id:14/parent_id:1' に送信されたリクエストは無効です。
```

### News >> 記事 >> 新規記事追加

```
内部エラーが発生しました
An Internal Error Has Occurred.
エラー: アドレス '/baser/admin/bc-blog/blog_posts/add/1' に送信されたリクエストは無効です。
```

News 記事の編集も同じです。

この不具合はたぶん baserCMS 5.0 がリリースされてからずっと続いていると思います。

誰か報告するだろうと放っておいたのですが、一応ご参考までに。

**Comment by ryuring** [comment]
@ibananlife 報告ありがとうございます。修正しておきました
