### ISSUE TITLE
 【システム】管理画面ログイン後のリダイレクトが動作していない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3523]
## 概要

- 以下のURLにアクセス
    - https://trial.basercms.net/baser/admin/baser-core/contents/index
- 以下のURLにリダイレクトされる
    - https://trial.basercms.net/baser/admin/baser-core/users/login?redirect=%2Fbaser%2Fadmin
- ログインするとダッシュボードが表示される
    - https://trial.basercms.net/baser/admin
 
baserCMS version : 5.1.0-dev

## TODO

- 管理画面ログイン後、当初アクセスしたページにリダイレクトするようにする

**Comment by ryuring** [comment]
@seto1 redirectパラメーターが間違ってそうですね。調査お願いしてもいいですか？
