### ISSUE TITLE
【システム】管理画面でお気に入りの削除を行った直後にお気に入りの追加を行えない

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3537]
お気に入り追加モーダルではなく編集モーダルが表示される
そこで確定ボタンを押しても何も起きない

baserCMS version : 5.1.0-dev

**Comment by ryuring** [comment]
@seto1 報告ありがとうございます！

**Comment by ryuring** [comment]
@seto1 対応できます？できなかったら、 @HungDV2022 にお願いします。

**Comment by seto1** [comment]
@ryuring お願いします！

**Comment by ryuring** [comment]
@HungDV2022 こちら dev-5で開発お願いします。

**Comment by HungDV2022** [comment]
@ryuring 
https://github.com/baserproject/basercms/pull/3544
こちらPRで修正しました。確認お願いします。
