### ISSUE TITLE
【サブサイト】サブドメイン利用サイトの場合にもサブフォルダ形式でアクセスできる

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3540]
サイトを追加

- エイリアス: test
- 公開状態: 公開する
- 外部ドメイン利用: 利用する
- ドメインタイプ: サブドメイン

どちらの場合にもページが表示される

https://localhost/test/
https://test.localhost/

ドメインタイプが「外部ドメイン」の場合には発生しない

baserCMS version : 5.1.0-dev

**Comment by ryuring** [comment]
@seto1 これは良くないですね
@HungDV2022 こちら確認してもらってもいいですか？再現方法がわからなかったら言ってください。
