### ISSUE TITLE
エイリアスを削除すると、元コンテンツのアイキャッチ画像が削除される問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#3542]
## 概要
ブログコンテンツなどのエイリアスを作成し、
その後、エイリアスのみを削除すると、元コンテンツに登録していたアイキャッチ画像が削除されます。

baserCMS version : 5.0.11 で確認
 
## TODO
- [ ] 5.0.19で再現するか要確認

**Comment by ryuring** [comment]
@HungDV2022 こちら一度見てもらえますか？

**Comment by ryuring** [comment]
@HungDV2022 仕様確認しました。
エイリアスを作成する際、contents テーブルの eyecatch フィールドの値をコピーする仕様となってましたが、これが仕様として間違いでした。
eyecatch フィールドをコピーしないようにしてください。
