### ISSUE TITLE
【システム】システム基本設定から「WebサイトURL(SSL)」を削除したい

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3576]
baserCMS version : 5

- SSLではない方のWebサイトURLにまとめたい
- あまり必要性がなさそう
- 現状「webサイトurl」にhttpsのURLが設定できたり、「webサイトurl(ssl)」にhttpのURLが設定できたりする
- SSLを使わないサイトでも入力必須

<img width="1223" alt="スクリーンショット 2024-07-03 11 34 29" src="https://github.com/baserproject/basercms/assets/30764014/52a8c019-9575-4d5c-8d35-748763b0f2d0">

---

現在の利用箇所は以下

- https://github.com/baserproject/basercms/blob/5.1.x/plugins/bc-mail/src/Model/Table/MailContentsTable.php#L181
    - メールコンテンツ設定で「SSL通信」を有効にするためのバリデーションとしてSSL用のURLが設定されているかのチェックを行っている
    - site_urlがhttpsから始まるかの判定で代用可能
    - また、この設定自体機能しておらずhttpでもフォームから送信可能
    - この設定も削除したい
- https://github.com/baserproject/basercms/blob/5.1.x/plugins/baser-core/src/Service/PermissionsService.php#L444
    - URLからドメインの削除のために利用
- https://github.com/baserproject/basercms/blob/5.1.x/plugins/baser-core/src/View/Helper/BcSmartphoneHelper.php#L65
    - スマートフォン用にURLを変換するために利用
- https://github.com/baserproject/basercms/blob/5.1.x/plugins/baser-core/src/View/Helper/BcBaserHelper.php#L2363
    - WebサイトURLを取得するために利用
- https://github.com/baserproject/basercms/blob/5.1.x/plugins/baser-core/src/Controller/Admin/BcAdminAppController.php#L193
    - 管理画面に正しくないURLでアクセスした場合のリダイレクトに利用

関連issue: https://github.com/baserproject/basercms/issues/3558

**Comment by ryuring** [comment]
こちらのプルリクで対応済み
https://github.com/baserproject/basercms/pull/3575
