### ISSUE TITLE
【インストーラー 5.0.x】ライブラリインストール後に500エラーとなりインストールが進まない

### ISSUE THREAD

**Issue by cu-akasakay** [baserproject/basercms#3679]
## 概要
ユーザーズフォーラムに挙げられた内容になります。

[バージョン5.1.0アップデート途中でサイトが表示できなくなりました。](https://forum.basercms.net/t/topic/1334)

5.0系のダウンロード版を元にインストールを行うと、ライブラリインストールの後、
500エラーとなり先に進めなくなります。

baserCMS version : 5.0.17、5.0.19、5.0.20

## エラー内容

その1）
 Fatal error: Type of BcInstaller\ServiceProvider\BcInstallerServiceProvider::$provides must not be defined (as in class Cake\Core\ServiceProvider) in /var/www/html/vendor/baserproject/bc-installer/src/ServiceProvider/BcInstallerServiceProvider.php on line 26

その2）
Fatal error: Type of BcBlog\View\Helper\BlogHelper::$helpers must not be defined (as in class Cake\View\Helper) in /var/www/html/vendor/baserproject/bc-blog/src/View/Helper/BlogHelper.php on line 62

以降、解消しても同様のエラーが続きます。

## 原因について
vendor内にインストールされたコアプラグインを見る限り、「5.1系」のものになっていることが原因と思われます。
5.0系のソースでは本来型定義が存在しないはずなので上記エラーも起こり得ないかなと思います。

5.1系
https://github.com/baserproject/basercms/blob/16e8b41bde5f879ee7c28462d83f5ecb94885144/plugins/bc-blog/src/Model/Entity/BlogPost.php#L53

5.0系
https://github.com/baserproject/basercms/blob/fe1577272a4a619bb918fcc3f910453e36de7c66/plugins/bc-blog/src/Model/Entity/BlogPost.php#L53

ライブラリインストール時のログを貼り付けておきます。
<img width="572" alt="image" src="https://github.com/user-attachments/assets/a13c9054-b2cf-4479-a0cd-2cf816df1ab1">

**Comment by ryuring** [comment]
@cu-akasakay 報告ありがとうございます、調査、対応、動作確認まで行い、フォーラムに回答しておきました。

**Comment by cu-akasakay** [comment]
私の方でも正常にインストールできることを確認しました。
質問者の方も当該事象が解決されたみたいですので、クローズします。
