### ISSUE TITLE
【baser5.1.0】管理画面のテーマ設定で保存実行時にエラーが発生

### ISSUE THREAD

**Issue by maenoasuka** [baserproject/basercms#3683]
## 概要
フォーラムに投稿されたバグ報告に再現性を確認できたので起案させていただきます。
[テーマ画像の差し替えでエラーがでる。](https://forum.basercms.net/t/topic/1337)

管理画面から「テーマ管理」→「設定」と進み、「保存」ボタンを押すと以下エラーが出力され、ロゴ・画像の更新ができない
```
 データベース処理中にエラーが発生しました。pathinfo(): Argument #1 ($path) must be of type string, Laminas\Diactoros\UploadedFile given
```

baserCMS version : 5.1.0
設定しているテーマ：サンプルテーマ  ( BcThemeSample )（BcColumnでも同様の現象発生）
 
![スクリーンショット 2024-08-07 17 24 06](https://github.com/user-attachments/assets/31ccf8f9-f5cf-4a5a-a5b2-0d35079e920f)

 
## 備考
ロゴ・画像ファイルを選択しているかどうかに関わらず、保存実行時にエラーが発生します。
また、詳細追いきれていませんが、エラーから推察するにアップロード時のパス名処理に問題がありそうです。

baser5.0.21にて同手順を実行した場合エラーは発生せず、問題なくロゴ・画像の更新ができました。

ご確認よろしくお願いいたします。

**Comment by ryuring** [comment]
@maenoasuka 調査チャレンジお願いします！

**Comment by GUSSAN-BEEDAN** [comment]
本件、issue化されてから、かれこれひと月になりますが何か進展はありますでしょうか？
直接DBをさわれないユーザーの場合、困っていると思うのですが。。。

**Comment by ryuring** [comment]
@GUSSAN-BEEDAN お待たせしました、改善しました。

**Comment by GUSSAN-BEEDAN** [comment]
@ryuring ありがとうございます。更新した設定が保存できることを確認いたしました。
