### ISSUE TITLE
【システム】install.php内のDB情報を.envに移動できるか検討

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3702]
baserCMS version : 5

認証情報は.envにまとめてinstall.phpをコミットできるようにしたいため
移動した結果install.php自体が不要になる可能性もあり

**Comment by seto1** [comment]
install.phpの役割

- インストール時に設定値書き込み
    - Security.salt
    - Datasources.default
    - Datasources.test
- インストール判定

**Comment by seto1** [comment]
.envではなくapp_localの方がいい?

> CakePHP3.5以降の設定情報の切り替えで .env を使うべきか app_local.php を使うべきか
> https://coodip.com/articles/3649

> https://github.com/cakephp/app/blob/5.0.2/config/.env.example
> Having this file in production is considered a **SECURITY RISK** and also decreases

**Comment by seto1** [comment]
ざっくりと動作するところまで
https://github.com/seto1/basercms/commits/fix-3702/
影響範囲大きいのとbaserバージョンアップ時用の対応が必要なのが課題

**Comment by seto1** [comment]
メリット

- 設定ファイルが1ファイル減る
- app_localとinstall.phpの重複した記述がなくなる
- 構築済みの環境を構築する際にちょっと楽

コード的にはまとめたいところだけど、メリットの割には影響大きいので保留

**Comment by ryuring** [comment]
@seto1 app_local.php は、CakePHP側の提供で触りたくないので、install.php を利用しています。

ちなみに、install.php を .env で上書きしている実案件の事例があるので、別途送っておきます。
