### ISSUE TITLE
【テーマ】テーマテンプレートの編集設定の名称にブレがある

### ISSUE THREAD

**Issue by seto1** [baserproject/basercms#3745]
baserCMS version :  5.1.0
 
https://github.com/search?q=repo%3Abaserproject%2Fbasercms%20allowedThemeEdit&type=code

- BcThemeFile.allowedThemeEdit
- BcThemeEdit.allowedThemeEdit

**Comment by kawaseryoma** [comment]
対応します！

**Comment by RyoK513** [comment]
対応します
