### ISSUE TITLE
コンテンツ管理でゴミ箱に入れた際、ツリー構造が壊れてしまう問題

### ISSUE THREAD

**Issue by katokaisya** [baserproject/basercms#3813]
## 概要
ゴミ箱がから出ない状態でツリー構造を操作すると
ツリー構造が壊れます。

再現手順
ゴミ箱にコンテンツが有る状態で
<img width="535" alt="image" src="https://github.com/user-attachments/assets/8f93edbd-3cc1-4e25-991e-699ee4bca6fe">
ツリー構造を移動すると
<img width="983" alt="image" src="https://github.com/user-attachments/assets/a4c855a9-6332-436e-9e74-92a75231f6b4">

ツリー構造が壊れます。
<img width="559" alt="image" src="https://github.com/user-attachments/assets/f6b7a3be-bea3-45ea-a68a-7a5723f5fa3a">

```
2024-09-13 12:40:48 error: index, 11, duplicate
2024-09-13 12:40:48 error: index, 12, duplicate
2024-09-13 12:40:48 error: node, 14, The parent field is blank, but has a parent

```

因みに
https://github.com/baserproject/basercms/commit/2a40035daf92c3c00fb71c14d280301f64d16876
のコミットは適用済みでも発生します。

baserCMS version : 5.1.2

**Comment by ryuring** [comment]
@katokaisya こちらのコミットで解消しました。
https://github.com/baserproject/basercms/commit/6a8511db3d938a9030ce040ba8ca935074548207
