### ISSUE TITLE
【カスタムコンテンツ】ファイル項目を含むエントリーをプレビュー時にエラーとなる

### ISSUE THREAD

**Issue by cu-akasakay** [baserproject/basercms#3828]
## 概要
フォーラムにて挙げられた内容になります。
https://forum.basercms.net/t/topic/1381
 
baserCMS version: 5.1.0

## エラー内容
pathinfo(): Argument #1 ($path) must be of type string, Laminas\Diactoros\UploadedFile given

ROOT/plugins/baser-core/src/Model/Validation/BcValidation.php at line 278 [(edit)](phpstorm://open?file=/var/www/html/plugins/baser-core/src/Model/Validation/BcValidation.php&line=278)

## 原因について
CustomContentFrontServiceの「setupPreviewForView」でEntityを生成する際、
リクエスト内のデータをそのままセットしているため、ファイル項目がUploadedFileの状態で渡り、
結果的にバリデーション処理側で例外が発生しているようです。

**Comment by ryuring** [comment]
@HungDV2022 こちら一度確認してもらますか？
