### ISSUE TITLE
【管理画面設定】管理画面テーマの選択の不具合

### ISSUE THREAD

**Issue by ibananlife** [baserproject/basercms#3884]
こんにちは。

## baserCMS の実行環境

- Ubuntu 20.04
- Server version: Apache/2.4.41 (Ubuntu)
- PHP Version 8.2.24
- PHP 8.2.24 (cli) (built: Sep 27 2024 04:04:15) (NTS)
- Xdebug: enabled
- mysql  Ver 15.1 Distrib 10.5.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- 使用パッケージ: basercms-5.1.2.zip

### ローカル環境での baserCMS 配置 URL

http://bc4default.local

http://bc5default.local

上記のローカル環境で実行しました。

システム基本設定 >> 管理画面設定 >> 管理画面テーマの選択に不具合があります。

以下に画像を添付します。

baserCMS 5.1.2 の場合

![bc5default_admin_baser-core_site_configs_index](https://github.com/user-attachments/assets/fc2c652b-b95f-4d00-9c65-37e2dcb0eae8)

baserCMS 4.8.1 の場合

![bc4default_admin_site_configs_form](https://github.com/user-attachments/assets/6576e24b-753e-4c35-a2a5-05762022b1ee)

取り敢えずご報告まで。

**Comment by ryuring** [comment]
@ibananlife 報告ありがとうございます。対応しておきました！
