### ISSUE TITLE
既定テンプレートの固定ページをエレメントとして読み込めない

### ISSUE THREAD

**Issue by MKGaru** [baserproject/basercms#3903]
## 概要
既定テンプレートの固定ページをエレメントとして読み込むと、  
`エレメントテンプレート「/../Pages/」が見つかりませんでした。`  
 となり、期待するように出力されない。

```php
$this->BcBaser->page('/test');
```

baserCMS version : 5.1.2
PHP 8.2.12 (Windows と FreeBSDにて確認）
 
## 備考
https://github.com/baserproject/basercms/blob/5.1.x/plugins/baser-core/src/View/Helper/BcBaserHelper.php#L2112

## 状態
page_template が 空文字になってしまう。  

## 期待する挙動
* page_template は 親階層から継承されたテンプレート名　または default に解決される。  
* 固定ページのコンテンツが`templates/Pages/default.php`等の規定レイアウトによって描画される。

**Comment by ryuring** [comment]
@MKGaru ご報告ありがとうございます、なおしておきました
