### ISSUE TITLE
【プラグイン管理】開発者の表記にbrタグが入ってる＆リンク先がおかしい

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#3918]
## 概要
ローカル環境でテスト中に発見。

プラグイン管理→プラグイン一覧⇨baserマーケットタブで開発者の名前にbrタグが表示されてしまっている部分があります。

株式会社ディーゼロ<br />（ 開発：株式会社キャッチアップ ）

![スクリーンショット 2024-10-16 15 13 22](https://github.com/user-attachments/assets/e37e95f0-2294-4771-8b7b-cf74f466d6fe)

また、ここの部分のリンクをクリックすると変なページに飛んでいきます。（他のリンクは会社さんのHPなどちゃんとしたところに飛びます）
リンク先URL：https://localhost/baser/admin/baser-core/plugins/get_market_plugins

![スクリーンショット 2024-10-16 15 19 29](https://github.com/user-attachments/assets/9ea7a386-d84e-40df-a1ac-90b400c06d35)

baserCMS version : 5.1.3

**Comment by maenoasuka** [comment]
こちら確認します
