### ISSUE TITLE
【テーマ設定】URL形式以外の文字が入力できてしまう

### ISSUE THREAD

**Issue by rabbitchang** [baserproject/basercms#4021]
テーマ設定　リンク先URLにURL形式以外の文字も入力できてしまう

baserCMS version : 5.1.3

<img width="877" alt="テーマ設定リンク先URL" src="https://github.com/user-attachments/assets/d7d1176c-d953-4960-a821-2892746f4aa4">

**Comment by IwasakiRyuichi** [comment]
対応します
