### ISSUE TITLE
独自プラグインの初期データが復元されない

### ISSUE THREAD

**Issue by binbin4649** [baserproject/basercms#4023]
独自プラグインと独自テーマを作成し、テーマ管理から「テーマ用初期データダウンロード」。
ダウンロードしたdefaultを入れ替えて、「初期データ読込」をすると、独自プラグインの初期データが復元されない。
なおダウンロードしたdefaultには、独自プラグイン名のディレクトリがあって、中身のcsvもあることは確認しました。

basercms/plugins/baser-core/src/Service/BcDatabaseService.php
```php
public function loadDefaultDataPattern(string $theme, string $pattern, string $dbConfigKeyName = 'default'): bool
    {
        $plugins = array_merge(
            ['BaserCore'],
            Configure::read('BcApp.corePlugins'),
            BcUtil::getCurrentThemesPlugins()
        );
```
調べてみたところ、コアとコアプラグインと、テーマ内プラグインだけ読み込んでる。
つまり独自プラグインは読み込んでない。ように見えます。

「テーマ用初期データダウンロード」で独自プラグインのデータもダウンロードできて、
「初期データ読込」で独自プラグインのデータも削除しているので、読み込みもできた方が良いのではないかと思うのですがどうでしょう？

独自プラグインとか独自テーマとか、有効化する順番とか考えるとキリがないので、
```php
$folderUtility = new \BaserCore\Utility\BcFolder('/plugins/' . $theme . '/' . $pattern . '/');
$plugins = $folderUtility->getFolders();
```
こんな感じで、defaultに入ってるものはとりあえず全部読み込めば良いんじゃないかと、
（まだ試してないです。）

@ryuring 
どうでしょう？

**Comment by ryuring** [comment]
@binbin4649 そちらの方が良さそうですね。

プラグインの配置場所が変わることがありますので　`Plugin::path()` を利用してください。

```
$folderUtility = new \BaserCore\Utility\BcFolder(Plugin::path($theme) . 'config' . DS . 'data' . DS . $pattern);
$plugins = $folderUtility->getFolders();
```

**Comment by binbin4649** [comment]
@ryuring 
了解しました！
動作確認してからPR出します、

**Comment by binbin4649** [comment]
PR送ったので一旦閉じます。
