### ISSUE TITLE
ブログのフロントページでfind処理がある場合にWarning

### ISSUE THREAD

**Issue by CUkomori** [baserproject/basercms#4080]
BcThemeSamapleテーマのブログ詳細で、複数Warnigが出ている。

**Comment by kk-uchino** [comment]
@CUkomori 
Issueの発行ありがとうございます！
baserCMSのバージョンとWarningのログの情報などいただけますでしょうか？

**Comment by CUkomori** [comment]
@kk-uchino 
すみません、昨日プルリクしてもらいました。
https://github.com/baserproject/basercms/pull/4081
