### ISSUE TITLE
独自テーブルでのマイページについて

### ISSUE THREAD

**Issue by binbin4649** [baserproject/basercms#4098]
独自プラグインにて独自テーブルを用意してのマイページ開発で躓いてます。
やり方、ヒントなどご教授いただけると助かります。

１）プレフィックス認証
独自プラグインの独自テーブルに、「user_groups」をアソシエーションしないと、パーミッションが通過できない。

具体的には、
basercms/plugins/baser-core/src/Controller/AppController.php
```php
private function checkPermission()
    {
        $user = BcUtil::loginUser();
        if ($user && $user->user_groups) {
            $userGroupsIds = Hash::extract($user->toArray()['user_groups'], '{n}.id');
        } else {
            $userGroupsIds = [];
        }
        /* @var PermissionsServiceInterface $permission */
        $permission = $this->getService(PermissionsServiceInterface::class);
        $request = $this->getRequest();
        return $permission->check($request->getPath(), $userGroupsIds, $request->getMethod());
    }
```

$user->user_groupsのエンティティを持っていないと、$userGroupsIdsに値が入らず通過できない。
checkPermissionを通過させるためだけにuser_groupsを持つのは無駄な感じがするし、
独自マイページでも独自のグループ管理をしたいので、user_groupsというややこしい名前を使いたくない。

ちなみに、BcPermission.defaultAllowsを使うと、認証自体をスルーしてしまうので、マイページとして機能しない。
さらにちなみに、独自エンティティには以下の設定が必要のようでした。
```php
public function isAdmin(): bool
    {
        return false;
    }

    public function getDisplayName()
    {
        return $this->name;
    }

    public function getAuthPrefixes(): array
    {
        $prefixes = ['membership'];
        return $prefixes;
    }
```

２）プラグインで独自に認証を設ける
できればこちらの方を採用したいのですが、
独自プラグインのコントローラーで認証を設定しても、BaserCoreの認証に吸い込まれて認証できない。
BaserCoreのミドルウエアを上書きしたり、スキップさせたり試してみましたが、謎のエラーで上手くできませんでした。
そもそもミドルウエアを後からスキップできるのか疑問ですが、（ChatGPTに教えてもらった方法は一通り試してみました、、、）

こんな感じでやれば良いんじゃない？みたいなヒントでも頂けると嬉しいです。
またよければ、途中まで作ったプラグインをアップします。
よろしくお願いします。

**Comment by ryuring** [comment]
@binbin4649 独自テーブルの場合に色々問題出たみたいですね。
本体側を改修しました。こちらを確認してみてください。
https://github.com/baserproject/basercms/commit/bb4d496365b3c91bd3075be416c729c9b8b155a4

**Comment by ryuring** [comment]
@binbin4649 マニュアルも更新しておきました。
https://baserproject.github.io/5/plugin/mypage

**Comment by binbin4649** [comment]
@ryuring 
ありがとうございます！

requirePermission => false
この設定は、プレフィックス認証で指定したプレフィックスは、BcPermissionを無視する。
という設定になるんでしょうか？

**Comment by ryuring** [comment]
@binbin4649 試してみてw

**Comment by binbin4649** [comment]
了解です。一旦閉じます。
