### ISSUE TITLE
Mail field problem

### ISSUE THREAD

**Issue by syokkendesuyo** [baserproject/basercms#545]
メールフィールド機能のボタンの不具合を報告します。
入力欄にデータを入力し、「入力内容を確認する」をクリック、「/contact/confirm」へ遷移した後「書き直す」を選択するとメールが送信される不具合を確認しました。

・環境
セーフモード：Off
データベース： MySQL
baserCMSバージョン： 4.0.1
CakePHPバージョン： 2.8.5

他にも必要な情報があればお知らせください。

・使えそうなリンク
https://github.com/baserproject/basercms/blob/f3c8543c259909f2d0c5e2a72824759259677222/lib/Baser/Config/theme/bc_sample/Elements/mail_form.php

https://github.com/baserproject/basercms/commit/af3be4fdf2f6fb7a16e82442a37d9cc73fd8ebfe

**Comment by ryuring** [comment]
@syokkendesuyo 症状を再現できずにいます。
「メールが送信される」とありますが、その時のブラウザ上の画面はどうなっていますか？
送信完了画面に遷移してしまってますか？

**Comment by syokkendesuyo** [comment]
@ryuring 
お尋ねの件「送信完了画面に遷移してしまってますか？」についてご回答します。
表示される画面は完了を示す画面へ遷移します。「書き直す」が「送信」ボタンとして機能してしまっています。

私も再度確認を行いました。どうやら自作したテーマに問題があるようで、デフォルトで存在する3つのテーマでは再現ができませんでした。
おおまかに変更した点は「PHP_EOL」を挿入したことと、class名を変更した程度です。

質問的な形となってしまいましたので必要であればフォーラムへ移動します。



--添付--
カスタマイズ後のmail_form.php
http://pastebin.com/mAdzXAFn

デフォルトのmail_form.php(こちらを元にカスタマイズ)
https://github.com/baserproject/basercms/blob/f3c8543c259909f2d0c5e2a72824759259677222/lib/Baser/Config/theme/bc_sample/Elements/mail_form.php

**Comment by kaburk** [comment]
横からすみません。
http://pastebin.com/mAdzXAFn 
こちら↑見たところ、「書き直す」「送信する」のボタンのクラスform-submitを削除してしまったからだとおもいます。
元ソース含めJSの、 $(".form-submit").click(function(){  ..  のところでsubmitのmode判別しているようです。

**Comment by ryuring** [comment]
@syokkendesuyo 提示頂いた、以下URLのコードで、再現性を確認しました。
http://pastebin.com/mAdzXAFn

そのコードに、 @kaburk さんの指摘のとおり、form-submit を追加したところ、改善を確認できました。

```
<?php echo $this->Mailform->submit('　書き直す　', array('div' => false, 'class' => 'btn btn-default form-submit', 'id' => 'BtnMessageBack')),PHP_EOL ?>
<?php echo $this->Mailform->submit('　送信する　', array('div' => false, 'class' => 'btn btn-default form-submit', 'id' => 'BtnMessageSubmit')),PHP_EOL ?>
```

上記のコードを利用しました。

もしかしたら、キャッシュ等の問題の可能性があるので、ブラウザを再度リロードして試してみて下さい。

**Comment by syokkendesuyo** [comment]
@ryuring 
シークレットモード等を利用し、キャッシュ対策をしましました。が現状は変わりませんでした。
またソースを確認し、「form-submit」やjavascriptの存在も確認しています。

**Comment by ryuring** [comment]
@syokkendesuyo そうですか、これ以上のヒントがなければ、こちらで再現性を確認できず、解決が難しそうです。
例えば、Javascriptのコンソールでエラー等が表示されていたりはしませんか？

**Comment by syokkendesuyo** [comment]
@ryuring 返信遅れて申し訳ありません。
jQueryの読み込みに失敗していました。その個所を修正した結果、jQueryは動作したものの下記のようなエラーが発生しました。その結果が2枚目の画像でフォームを埋めても動作しませんでした。
jQueryの推奨バージョンはありましたか？
![fail](https://cloud.githubusercontent.com/assets/5967134/22770902/0280993a-eed7-11e6-8f65-2464cf627edf.png)
![honoka_baser](https://cloud.githubusercontent.com/assets/5967134/22770862/d0ae5b68-eed6-11e6-93d3-cbf970921b04.png)

**Comment by ryuring** [comment]
@syokkendesuyo jQuery 2系で試していただけますか？ 2.1.4 だと間違いないと思います。

**Comment by syokkendesuyo** [comment]
@ryuring 
jquery-2.2.4.min.js を利用したところ正常に動くことを確認しました。
対応ありがとうございました。

**Comment by ryuring** [comment]
@syokkendesuyo 解決されたとの事でよかったです ＾＾
